r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Messaging
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""


from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator, Protocol
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse

from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version









class DomainCertsInstance(InstanceResource):



    """
    :ivar domain_sid: The unique string that we created to identify the Domain resource.
    :ivar date_updated: Date that this Domain was last updated.
    :ivar date_expires: Date that the private certificate associated with this domain expires. You will need to update the certificate before that date to ensure your shortened links will continue to work.
    :ivar date_created: Date that this Domain was registered to the Twilio platform to create a new Domain object.
    :ivar domain_name: Full url path for this domain.
    :ivar certificate_sid: The unique string that we created to identify this Certificate resource.
    :ivar url: 
    :ivar cert_in_validation: Optional JSON field describing the status and upload date of a new certificate in the process of validation
    """

    def __init__(self, version: Version, payload:Dict[str, Any], domain_sid: Optional[str] = None):
        super().__init__(version)

        
        self.domain_sid: Optional[str] = payload.get("domain_sid")
        self.date_updated: Optional[datetime] = deserialize.iso8601_datetime(payload.get("date_updated"))
        self.date_expires: Optional[datetime] = deserialize.iso8601_datetime(payload.get("date_expires"))
        self.date_created: Optional[datetime] = deserialize.iso8601_datetime(payload.get("date_created"))
        self.domain_name: Optional[str] = payload.get("domain_name")
        self.certificate_sid: Optional[str] = payload.get("certificate_sid")
        self.url: Optional[str] = payload.get("url")
        self.cert_in_validation: Optional[Dict[str, object]] = payload.get("cert_in_validation")

        
        
        self._solution = { 
            "domain_sid": domain_sid or self.domain_sid,
        }
        
        
        
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = ' '.join('{}={}'.format(k, v) for k, v in self._solution.items())
        return '<Twilio.Messaging.Users_manisingh_codehq_open_api_spec_messaging_v1_openapi_yaml.DomainCertsInstance {}>'.format(context)




class DomainCertsList(ListResource):
    
    def __init__(self, version: Version, domain_sid: str):
        """
        Initialize the DomainCertsList

        :param version: Version that contains the resource
        :param domain_sid: Unique string used to identify the domain that this certificate should be associated with.
        
        """
        super().__init__(version)

        
        # Path Solution
        self._solution = { 'domain_sid': domain_sid,  }
        self._uri = '/LinkShortening/Domains/{domain_sid}/Certificate'.format(**self._solution)
        
        
    
    def _delete(self) -> tuple:
        """
        Internal helper for delete operation

        Returns:
            tuple: (success_boolean, status_code, headers)
        """
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        
        
        return self._version.delete_with_response_info(method='DELETE', uri=self._uri, headers=headers)

    def delete(self) -> bool:
        """
        Delete the DomainCertsInstance

        
        :returns: True if delete succeeds, False otherwise
        """
        success, _, _ = self._delete()
        return success

    def delete_with_http_info(self) -> ApiResponse:
        """
        Delete the DomainCertsInstance and return response metadata

        
        :returns: ApiResponse with success boolean, status code, and headers
        """
        success, status_code, headers = self._delete()
        return ApiResponse(data=success, status_code=status_code, headers=headers)

    async def _delete_async(self) -> tuple:
        """
        Internal async helper for delete operation

        Returns:
            tuple: (success_boolean, status_code, headers)
        """
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        
        
        return await self._version.delete_with_response_info_async(method='DELETE', uri=self._uri, headers=headers)

    async def delete_async(self) -> bool:
        """
        Asynchronously delete the DomainCertsInstance

        
        :returns: True if delete succeeds, False otherwise
        """
        success, _, _ = await self._delete_async()
        return success

    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronously delete the DomainCertsInstance and return response metadata

        
        :returns: ApiResponse with success boolean, status code, and headers
        """
        success, status_code, headers = await self._delete_async()
        return ApiResponse(data=success, status_code=status_code, headers=headers)
    
    def _fetch(self) -> tuple:
        """
        Internal helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        
        headers["Accept"] = "application/json"
        
        
        return self._version.fetch_with_response_info(method='GET', uri=self._uri, headers=headers)

    def fetch(self) -> DomainCertsInstance:
        """
        Fetch the DomainCertsInstance

        
        :returns: The fetched DomainCertsInstance
        """
        payload, _, _ = self._fetch()
        return DomainCertsInstance(self._version, payload, domain_sid=self._solution['domain_sid'])

    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the DomainCertsInstance and return response metadata

        
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = self._fetch()
        instance = DomainCertsInstance(self._version, payload, domain_sid=self._solution['domain_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)

    async def _fetch_async(self) -> tuple:
        """
        Internal async helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        
        headers["Accept"] = "application/json"
        
        
        return await self._version.fetch_with_response_info_async(method='GET', uri=self._uri, headers=headers)

    async def fetch_async(self) -> DomainCertsInstance:
        """
        Asynchronously fetch the DomainCertsInstance

        
        :returns: The fetched DomainCertsInstance
        """
        payload, _, _ = await self._fetch_async()
        return DomainCertsInstance(self._version, payload, domain_sid=self._solution['domain_sid'])

    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronously fetch the DomainCertsInstance and return response metadata

        
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = await self._fetch_async()
        instance = DomainCertsInstance(self._version, payload, domain_sid=self._solution['domain_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)
    
    def list(self, 
    ) -> List[DomainCertsInstance]:
        """
        Lists DomainCertsInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = self._version.fetch_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [DomainCertsInstance(self._version, item, domain_sid=self._solution['domain_sid']) for item in payload[""]]
        

    async def list_async(self, 
    ) -> List[DomainCertsInstance]:
        """
        Asynchronously lists DomainCertsInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [DomainCertsInstance(self._version, item, domain_sid=self._solution['domain_sid']) for item in payload[""]]
        


    def list_with_http_info(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists DomainCertsInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists DomainCertsInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> DomainCertsPage:
        """
        Retrieve a single page of DomainCertsInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of DomainCertsInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = self._version.page(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return DomainCertsPage(self._version, response, solution=self._solution)

    async def page_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> DomainCertsPage:
        """
        Asynchronously retrieve a single page of DomainCertsInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of DomainCertsInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = await self._version.page_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return DomainCertsPage(self._version, response, solution=self._solution)

    def page_with_http_info(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with DomainCertsPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = self._version.page_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = DomainCertsPage(self._version, response, solution=self._solution)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with DomainCertsPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = DomainCertsPage(self._version, response, solution=self._solution)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> DomainCertsPage:
        """
        Retrieve a specific page of DomainCertsInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of DomainCertsInstance
        """
        response = self._version.domain.twilio.request(
            'OPTIONS',
            target_url
        )
        return DomainCertsPage(self._version, response, solution=self._solution)

    async def get_page_async(self, target_url: str) -> DomainCertsPage:
        """
        Asynchronously retrieve a specific page of DomainCertsInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of DomainCertsInstance
        """
        response = await self._version.domain.twilio.request_async(
            'OPTIONS',
            target_url
        )
        return DomainCertsPage(self._version, response, solution=self._solution)

    

    def _update(self, tls_cert: str) -> tuple:
        """
        Internal helper for update operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        
        data = values.of({ 
            'TlsCert': tls_cert,
        })
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        headers["Content-Type"] = "application/x-www-form-urlencoded"
        
        
        headers["Accept"] = "application/json"
        
        
        return self._version.update_with_response_info(method='POST', uri=self._uri, data=data, headers=headers)

    def update(self, tls_cert: str) -> DomainCertsInstance:
        """
        Update the DomainCertsInstance

        :param tls_cert: Contains the full TLS certificate and private for this domain in PEM format: https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail. Twilio uses this information to process HTTPS traffic sent to your domain.
        
        :returns: The updated DomainCertsInstance
        """
        payload, _, _ = self._update(tls_cert=tls_cert)
        return DomainCertsInstance(self._version, payload, domain_sid=self._solution['domain_sid'])

    def update_with_http_info(self, tls_cert: str) -> ApiResponse:
        """
        Update the DomainCertsInstance and return response metadata

        :param tls_cert: Contains the full TLS certificate and private for this domain in PEM format: https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail. Twilio uses this information to process HTTPS traffic sent to your domain.
        
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = self._update(tls_cert=tls_cert)
        instance = DomainCertsInstance(self._version, payload, domain_sid=self._solution['domain_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)

    async def _update_async(self, tls_cert: str) -> tuple:
        """
        Internal async helper for update operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        
        data = values.of({ 
            'TlsCert': tls_cert,
        })
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        headers["Content-Type"] = "application/x-www-form-urlencoded"
        
        
        headers["Accept"] = "application/json"
        
        
        return await self._version.update_with_response_info_async(method='POST', uri=self._uri, data=data, headers=headers)

    async def update_async(self, tls_cert: str) -> DomainCertsInstance:
        """
        Asynchronously update the DomainCertsInstance

        :param tls_cert: Contains the full TLS certificate and private for this domain in PEM format: https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail. Twilio uses this information to process HTTPS traffic sent to your domain.
        
        :returns: The updated DomainCertsInstance
        """
        payload, _, _ = await self._update_async(tls_cert=tls_cert)
        return DomainCertsInstance(self._version, payload, domain_sid=self._solution['domain_sid'])

    async def update_with_http_info_async(self, tls_cert: str) -> ApiResponse:
        """
        Asynchronously update the DomainCertsInstance and return response metadata

        :param tls_cert: Contains the full TLS certificate and private for this domain in PEM format: https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail. Twilio uses this information to process HTTPS traffic sent to your domain.
        
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = await self._update_async(tls_cert=tls_cert)
        instance = DomainCertsInstance(self._version, payload, domain_sid=self._solution['domain_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)



    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return '<Twilio.Messaging.Users_manisingh_codehq_open_api_spec_messaging_v1_openapi_yaml.DomainCertsList>'


