r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Preview
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""


from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator, Protocol
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse

from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version









class ValidateVersionInstance(InstanceResource):



    """
    :ivar message: A string message with details of the result of the validation.
    """

    def __init__(self, version: Version, payload:Dict[str, Any], instance_sid: Optional[str] = None):
        super().__init__(version)

        
        self.message: Optional[str] = payload.get("message")

        
        
        self._solution = { 
            "instance_sid": instance_sid or self.instance_sid,
        }
        
        
        
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = ' '.join('{}={}'.format(k, v) for k, v in self._solution.items())
        return '<Twilio.Preview.Users_manisingh_codehq_open_api_spec_preview_flex_openapi_yaml.ValidateVersionInstance {}>'.format(context)




class ValidateVersionList(ListResource):
    
    def __init__(self, version: Version, instance_sid: str):
        """
        Initialize the ValidateVersionList

        :param version: Version that contains the resource
        :param instance_sid: The unique ID of the Instance
        
        """
        super().__init__(version)

        
        # Path Solution
        self._solution = { 'instance_sid': instance_sid,  }
        self._uri = '/Instances/{instance_sid}/ValidateVersion'.format(**self._solution)
        
        
    
    def _create(self, mobile_version: str) -> tuple:
        """
        Internal helper for create operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        
        data = values.of({ 
            'MobileVersion': mobile_version,
        })
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        headers["Content-Type"] = "application/x-www-form-urlencoded"
        
        
        headers["Accept"] = "application/json"
        
        
        return self._version.create_with_response_info(method='POST', uri=self._uri, data=data, headers=headers)

    def create(self, mobile_version: str) -> ValidateVersionInstance:
        """
        Create the ValidateVersionInstance

        :param mobile_version: The mobile version string to be validated. This must follow Semantic Versioning.
        
        :returns: The created ValidateVersionInstance
        """
        payload, _, _ = self._create(mobile_version=mobile_version)
        return ValidateVersionInstance(self._version, payload, instance_sid=self._solution['instance_sid'])

    def create_with_http_info(self, mobile_version: str) -> ApiResponse:
        """
        Create the ValidateVersionInstance and return response metadata

        :param mobile_version: The mobile version string to be validated. This must follow Semantic Versioning.
        
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = self._create(mobile_version=mobile_version)
        instance = ValidateVersionInstance(self._version, payload, instance_sid=self._solution['instance_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)

    async def _create_async(self, mobile_version: str) -> tuple:
        """
        Internal async helper for create operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        
        data = values.of({ 
            'MobileVersion': mobile_version,
        })
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        headers["Content-Type"] = "application/x-www-form-urlencoded"
        
        
        headers["Accept"] = "application/json"
        
        
        return await self._version.create_with_response_info_async(method='POST', uri=self._uri, data=data, headers=headers)

    async def create_async(self, mobile_version: str) -> ValidateVersionInstance:
        """
        Asynchronously create the ValidateVersionInstance

        :param mobile_version: The mobile version string to be validated. This must follow Semantic Versioning.
        
        :returns: The created ValidateVersionInstance
        """
        payload, _, _ = await self._create_async(mobile_version=mobile_version)
        return ValidateVersionInstance(self._version, payload, instance_sid=self._solution['instance_sid'])

    async def create_with_http_info_async(self, mobile_version: str) -> ApiResponse:
        """
        Asynchronously create the ValidateVersionInstance and return response metadata

        :param mobile_version: The mobile version string to be validated. This must follow Semantic Versioning.
        
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = await self._create_async(mobile_version=mobile_version)
        instance = ValidateVersionInstance(self._version, payload, instance_sid=self._solution['instance_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)
    
    
    def list(self, 
    ) -> List[ValidateVersionInstance]:
        """
        Lists ValidateVersionInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = self._version.fetch_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [ValidateVersionInstance(self._version, item, instance_sid=self._solution['instance_sid']) for item in payload[""]]
        

    async def list_async(self, 
    ) -> List[ValidateVersionInstance]:
        """
        Asynchronously lists ValidateVersionInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [ValidateVersionInstance(self._version, item, instance_sid=self._solution['instance_sid']) for item in payload[""]]
        


    def list_with_http_info(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists ValidateVersionInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists ValidateVersionInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ValidateVersionPage:
        """
        Retrieve a single page of ValidateVersionInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of ValidateVersionInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = self._version.page(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return ValidateVersionPage(self._version, response, solution=self._solution)

    async def page_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ValidateVersionPage:
        """
        Asynchronously retrieve a single page of ValidateVersionInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of ValidateVersionInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = await self._version.page_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return ValidateVersionPage(self._version, response, solution=self._solution)

    def page_with_http_info(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with ValidateVersionPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = self._version.page_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = ValidateVersionPage(self._version, response, solution=self._solution)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with ValidateVersionPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = ValidateVersionPage(self._version, response, solution=self._solution)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> ValidateVersionPage:
        """
        Retrieve a specific page of ValidateVersionInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of ValidateVersionInstance
        """
        response = self._version.domain.twilio.request(
            'OPTIONS',
            target_url
        )
        return ValidateVersionPage(self._version, response, solution=self._solution)

    async def get_page_async(self, target_url: str) -> ValidateVersionPage:
        """
        Asynchronously retrieve a specific page of ValidateVersionInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of ValidateVersionInstance
        """
        response = await self._version.domain.twilio.request_async(
            'OPTIONS',
            target_url
        )
        return ValidateVersionPage(self._version, response, solution=self._solution)




    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return '<Twilio.Preview.Users_manisingh_codehq_open_api_spec_preview_flex_openapi_yaml.ValidateVersionList>'


