language: java
install:
- make install
script:
- make test-docker
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: EtSk9CnO7KeFTVOJ+GXkcHCiATgVyQV6Yi1Y9aiVzKLKXyXLeBxCQjDGfO5w04/NR3RY+uLDA4ALmJnPVITME5YxIiVcAFwZ7N4PvvZL67a72mPrGSq6CRnG0OYTA1TvGxF61H3cgOoyPwkVe2PPjkBrVcFH8+mKIxyYdjY0WvM8OEQm+0TNt7g51tojGUIU4B8km8aZgm0EDPG2/IKdoTkVqr1d8K1VBsQMNTqX2/dIyaYGMq60tsSZDOOODbdmhfn69smO65q0ZZX2aIW438Pxhs6Uxyeb9MU4fsOdKDNmB6GeauMViEIdyVwIth0k8PXypxIDJbAc8sed9M2fBftZbrargG/FltYfCxNYubPJS7S7GivdEJhzoR0lTw4PsXDgajE3D1c+o+29LLXrbJuTfMb6R6trGN2S1oTfQzSZGsA2t0eC98Be+UDKg66M6qLD2+hl3h4ftLWo0n7OxJkGb6eDB1wcsm1H2bFWfm4mkcg1RnIFMyo20BLRc+5xAkOgxUpSPgQ8hqoa1YShE8iRmFv/VKSL816cHNNW/x78gw7xWw3SAAhtYnW7NxvDPYll+9UF9gUfAbuMzubjMkVlfjDLypXsAEEeBq56hgRYC0smwRvUcZ9Uw8AsXeS3BrClZCVWE2y4+YSs9yxqyL1OMSCyiHpViPojzD/bufc=
