# coding: utf-8

"""
    Twilio - Versionless

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: DeployedDevices
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.deployed_devices_fleets.post import CreateDeployedDevicesFleet
from openapi_client.paths.deployed_devices_fleets_sid.get import FetchDeployedDevicesFleet


class Fleet(
    CreateDeployedDevicesFleet,
    FetchDeployedDevicesFleet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
