# coding: utf-8

"""
    Twilio - Accounts

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 2010-04-01
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths._2010_04_01_accounts_account_sid_calls_feedback_summary_sid_json.post import UpdateCallFeedbackSummary


class Account1234567890Call1234567890FeedbackCallSummary(
    UpdateCallFeedbackSummary,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
