r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Ai
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""


from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator, Protocol
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse

from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page








class OotbPrimitiveAvailableInstance(InstanceResource):



    """
    :ivar provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
    :ivar model_identifier: Unique string to identify the model.
    :ivar latest_model_sid: The unique SID identifier of the latest Model.
    :ivar canary_model_sid: The unique SID identifier of the canary Model.
    :ivar date_created: The date that this Primitive was created, given in ISO 8601 format.
    :ivar date_updated: The date that this Primitive was updated, given in ISO 8601 format.
    :ivar url: The URL of this resource.
    """

    def __init__(self, version: Version, payload:Dict[str, Any]):
        super().__init__(version)

        
        self.provider: Optional[str] = payload.get("provider")
        self.model_identifier: Optional[str] = payload.get("model_identifier")
        self.latest_model_sid: Optional[str] = payload.get("latest_model_sid")
        self.canary_model_sid: Optional[str] = payload.get("canary_model_sid")
        self.date_created: Optional[datetime] = deserialize.iso8601_datetime(payload.get("date_created"))
        self.date_updated: Optional[datetime] = deserialize.iso8601_datetime(payload.get("date_updated"))
        self.url: Optional[str] = payload.get("url")

        
        
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        
        return '<Twilio.Ai.Users_manisingh_codehq_open_api_spec_ai_v1_openapi_yaml.OotbPrimitiveAvailableInstance>'




class OotbPrimitiveAvailablePage(Page):

    def get_instance(self, payload: Dict[str, Any]) -> OotbPrimitiveAvailableInstance:
        """
        Build an instance of OotbPrimitiveAvailableInstance

        :param payload: Payload response from the API
        """
        
        return OotbPrimitiveAvailableInstance(self._version, payload)
        

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return "<Twilio.Ai.Users_manisingh_codehq_open_api_spec_ai_v1_openapi_yaml.OotbPrimitiveAvailablePage>"




class OotbPrimitiveAvailablePage(Page):

    def get_instance(self, payload: Dict[str, Any]) -> OotbPrimitiveAvailableInstance:
        """
        Build an instance of OotbPrimitiveAvailableInstance

        :param payload: Payload response from the API
        """
        
        return OotbPrimitiveAvailableInstance(self._version, payload)
        

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return "<Twilio.Ai.Users_manisingh_codehq_open_api_spec_ai_v1_openapi_yaml.OotbPrimitiveAvailablePage>"





class OotbPrimitiveAvailableList(ListResource):
    
    def __init__(self, version: Version):
        """
        Initialize the OotbPrimitiveAvailableList

        :param version: Version that contains the resource
        
        """
        super().__init__(version)

        
        self._uri = '/Primitives/Predefined/Available'
        
        
    
    def stream(self, 
        provider: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> Iterator[OotbPrimitiveAvailableInstance]:
        """
        Streams OotbPrimitiveAvailableInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.
        
        :param str provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        limits = self._version.read_limits(limit, page_size)
        page = self.page(
            provider=provider,
            page_size=limits['page_size']
        )

        return self._version.stream(page, limits['limit'])

    async def stream_async(self, 
        provider: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> AsyncIterator[OotbPrimitiveAvailableInstance]:
        """
        Asynchronously streams OotbPrimitiveAvailableInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.
        
        :param str provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        limits = self._version.read_limits(limit, page_size)
        page = await self.page_async(
            provider=provider,
            page_size=limits['page_size']
        )

        return self._version.stream_async(page, limits['limit'])

    def stream_with_http_info(self, 
        provider: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> tuple:
        """
        Streams OotbPrimitiveAvailableInstance and returns headers from first page

        
        :param str provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        limits = self._version.read_limits(limit, page_size)
        page_response = self.page_with_http_info(
            provider=provider,
            page_size=limits['page_size']
        )

        generator = self._version.stream(page_response.data, limits['limit'])
        return (generator, page_response.status_code, page_response.headers)

    async def stream_with_http_info_async(self, 
        provider: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> tuple:
        """
        Asynchronously streams OotbPrimitiveAvailableInstance and returns headers from first page

        
        :param str provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        limits = self._version.read_limits(limit, page_size)
        page_response = await self.page_with_http_info_async(
            provider=provider,
            page_size=limits['page_size']
        )

        generator = self._version.stream_async(page_response.data, limits['limit'])
        return (generator, page_response.status_code, page_response.headers)

    def list(self, 
        provider: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> List[OotbPrimitiveAvailableInstance]:
        """
        Lists OotbPrimitiveAvailableInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.
        
        :param str provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)
        
        :returns: list that will contain up to limit results
        """

        return list(self.stream(
            provider=provider,
            limit=limit,
            page_size=page_size,
        ))

    async def list_async(self, 
        provider: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> List[OotbPrimitiveAvailableInstance]:
        """
        Asynchronously lists OotbPrimitiveAvailableInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.
        
        :param str provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)
        
        :returns: list that will contain up to limit results
        """

        return [record async for record in await self.stream_async(
            provider=provider,
            limit=limit,
            page_size=page_size,
        )]


    def list_with_http_info(self, 
        provider: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists OotbPrimitiveAvailableInstance and returns headers from first page

        
        :param str provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            provider=provider,
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        provider: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists OotbPrimitiveAvailableInstance and returns headers from first page

        
        :param str provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            provider=provider,
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
      provider: Union[str, object] = values.unset,
      
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> OotbPrimitiveAvailablePage:
        """
        Retrieve a single page of OotbPrimitiveAvailableInstance records from the API.
        Request is executed immediately
        
        :param provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of OotbPrimitiveAvailableInstance
        """
        data = values.of({ 
            'Provider': provider,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = self._version.page(method='GET', uri=self._uri, params=data, headers=headers)
        return OotbPrimitiveAvailablePage(self._version, response)

    async def page_async(self, 
      provider: Union[str, object] = values.unset,
      
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> OotbPrimitiveAvailablePage:
        """
        Asynchronously retrieve a single page of OotbPrimitiveAvailableInstance records from the API.
        Request is executed immediately
        
        :param provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of OotbPrimitiveAvailableInstance
        """
        data = values.of({ 
            'Provider': provider,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = await self._version.page_async(method='GET', uri=self._uri, params=data, headers=headers)
        return OotbPrimitiveAvailablePage(self._version, response)

    def page_with_http_info(self, 
        provider: Union[str, object] = values.unset,
        
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with OotbPrimitiveAvailablePage, status code, and headers
        """
        data = values.of({ 
            'Provider': provider,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = self._version.page_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        page = OotbPrimitiveAvailablePage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        provider: Union[str, object] = values.unset,
        
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param provider: Where the identified model is provided from. Can be `twilio` or a specific account sid.
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with OotbPrimitiveAvailablePage, status code, and headers
        """
        data = values.of({ 
            'Provider': provider,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        page = OotbPrimitiveAvailablePage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> OotbPrimitiveAvailablePage:
        """
        Retrieve a specific page of OotbPrimitiveAvailableInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of OotbPrimitiveAvailableInstance
        """
        response = self._version.domain.twilio.request(
            'GET',
            target_url
        )
        return OotbPrimitiveAvailablePage(self._version, response)

    async def get_page_async(self, target_url: str) -> OotbPrimitiveAvailablePage:
        """
        Asynchronously retrieve a specific page of OotbPrimitiveAvailableInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of OotbPrimitiveAvailableInstance
        """
        response = await self._version.domain.twilio.request_async(
            'GET',
            target_url
        )
        return OotbPrimitiveAvailablePage(self._version, response)

    
    def list(self, 
    ) -> List[OotbPrimitiveAvailableInstance]:
        """
        Lists OotbPrimitiveAvailableInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = self._version.fetch_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [OotbPrimitiveAvailableInstance(self._version, item) for item in payload["primitives"]]
        

    async def list_async(self, 
    ) -> List[OotbPrimitiveAvailableInstance]:
        """
        Asynchronously lists OotbPrimitiveAvailableInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [OotbPrimitiveAvailableInstance(self._version, item) for item in payload["primitives"]]
        


    def list_with_http_info(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists OotbPrimitiveAvailableInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists OotbPrimitiveAvailableInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> OotbPrimitiveAvailablePage:
        """
        Retrieve a single page of OotbPrimitiveAvailableInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of OotbPrimitiveAvailableInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = self._version.page(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return OotbPrimitiveAvailablePage(self._version, response)

    async def page_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> OotbPrimitiveAvailablePage:
        """
        Asynchronously retrieve a single page of OotbPrimitiveAvailableInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of OotbPrimitiveAvailableInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = await self._version.page_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return OotbPrimitiveAvailablePage(self._version, response)

    def page_with_http_info(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with OotbPrimitiveAvailablePage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = self._version.page_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = OotbPrimitiveAvailablePage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with OotbPrimitiveAvailablePage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = OotbPrimitiveAvailablePage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> OotbPrimitiveAvailablePage:
        """
        Retrieve a specific page of OotbPrimitiveAvailableInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of OotbPrimitiveAvailableInstance
        """
        response = self._version.domain.twilio.request(
            'OPTIONS',
            target_url
        )
        return OotbPrimitiveAvailablePage(self._version, response)

    async def get_page_async(self, target_url: str) -> OotbPrimitiveAvailablePage:
        """
        Asynchronously retrieve a specific page of OotbPrimitiveAvailableInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of OotbPrimitiveAvailableInstance
        """
        response = await self._version.domain.twilio.request_async(
            'OPTIONS',
            target_url
        )
        return OotbPrimitiveAvailablePage(self._version, response)




    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return '<Twilio.Ai.Users_manisingh_codehq_open_api_spec_ai_v1_openapi_yaml.OotbPrimitiveAvailableList>'


