r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Voice Recording Access Service API
    API for managing recording-related properties including storage credentials and encryption settings. Supports recording storage configuration and transcription metadata. 

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""

from typing import Optional
from twilio.base.version import Version
from twilio.base.domain import Domain


class Users_manisingh_codehq_open_api_spec_voice_recording_access_v1_openapi_yaml(Version):

    def __init__(self, domain: Domain):
        """
        Initialize the Users_manisingh_codehq_open_api_spec_voice_recording_access_v1_openapi_yaml version of Voice

        :param domain: The Twilio.voice domain
        """
        super().__init__(domain, "v1")
        
    def __repr__(self) -> str:
        """
        Provide a friendly representation
        :returns: Machine friendly representation
        """
        return "<Twilio.Voice.Users_manisingh_codehq_open_api_spec_voice_recording_access_v1_openapi_yaml>"
