/*
    * Twilio - Accounts
    *
    * This is the public Twilio REST API.
    *
    * API version: 1.11.0
    * Contact: support@twilio.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi
// ApiV2010CallFeedbackSummary struct for ApiV2010CallFeedbackSummary
type ApiV2010CallFeedbackSummary struct {
        // Issues experienced during the call
    Issues *[]ApiV2010AccountCallCallFeedbackSummaryIssues `json:"issues,omitempty"`
}

