r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Stytch Domain Unified API
    Customer Identity and Access Management API

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""


from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator, Protocol
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse

from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version









class AuthorizeInstance(InstanceResource):



    """
    :ivar code: Twilio-specific error code. This numeric code uniquely identifies the error type within Twilio's error taxonomy and can be used for programmatic handling. 
    :ivar detail: A human-readable explanation specific to this occurrence of the problem. This field's value can change between different occurrences of the same problem type. 
    :ivar errors: Array of validation errors for HTTP 400/422 responses. Each error contains a human-readable detail message and a JSON Pointer indicating the location of the error in the request. 
    :ivar instance: A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. 
    :ivar status: The HTTP status code generated by the origin server for this occurrence of the problem. This MUST match the HTTP status code returned in the response. 
    :ivar title: A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization. 
    :ivar type: A URI reference that identifies the problem type. This URI should resolve to human-readable documentation for the problem type. 
    """

    def __init__(self, version: Version, payload:Dict[str, Any]):
        super().__init__(version)

        
        self.code: Optional[int] = deserialize.integer(payload.get("code"))
        self.detail: Optional[str] = payload.get("detail")
        self.errors: Optional[List[str]] = payload.get("errors")
        self.instance: Optional[str] = payload.get("instance")
        self.status: Optional[int] = deserialize.integer(payload.get("status"))
        self.title: Optional[str] = payload.get("title")
        self.type: Optional[str] = payload.get("type")

        
        
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        
        return '<Twilio.Ciam.Users_manisingh_codehq_open_api_spec_ciam_tenanted_openapi_yaml.AuthorizeInstance>'




class AuthorizeList(ListResource):
    
    def __init__(self, version: Version):
        """
        Initialize the AuthorizeList

        :param version: Version that contains the resource
        
        """
        super().__init__(version)

        
        self._uri = '/backchannel/authorize'
        
        
    
    def list(self, 
        sid: Union[str, object] = values.unset,
        client_id: Union[str, object] = values.unset,
        state: Union[str, object] = values.unset,
        scope: Union[str, object] = values.unset,
        nonce: Union[str, object] = values.unset,
        code_challenge_method: Union[str, object] = values.unset,
        code_challenge: Union[str, object] = values.unset,
        redirect_uri: Union[str, object] = values.unset,
        response_type: Union[str, object] = values.unset,
        authorization_details: Union[str, object] = values.unset,
        screen_hint: Union[str, object] = values.unset,
        prompt: Union[str, object] = values.unset,
        acr_values: Union[str, object] = values.unset,
        max_age: Union[int, object] = values.unset,
    ) -> List[AuthorizeInstance]:
        """
        Lists AuthorizeInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "text/html"
        
        data = values.of({ 
            'sid': sid,
            'client_id': client_id,
            'state': state,
            'scope': scope,
            'nonce': nonce,
            'code_challenge_method': code_challenge_method,
            'code_challenge': code_challenge,
            'redirect_uri': redirect_uri,
            'response_type': response_type,
            'authorization_details': authorization_details,
            'screen_hint': screen_hint,
            'prompt': prompt,
            'acr_values': acr_values,
            'max_age': max_age,
        })
        payload, _, _ = self._version.fetch_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [AuthorizeInstance(self._version, item) for item in payload[""]]
        

    async def list_async(self, 
        sid: Union[str, object] = values.unset,
        client_id: Union[str, object] = values.unset,
        state: Union[str, object] = values.unset,
        scope: Union[str, object] = values.unset,
        nonce: Union[str, object] = values.unset,
        code_challenge_method: Union[str, object] = values.unset,
        code_challenge: Union[str, object] = values.unset,
        redirect_uri: Union[str, object] = values.unset,
        response_type: Union[str, object] = values.unset,
        authorization_details: Union[str, object] = values.unset,
        screen_hint: Union[str, object] = values.unset,
        prompt: Union[str, object] = values.unset,
        acr_values: Union[str, object] = values.unset,
        max_age: Union[int, object] = values.unset,
    ) -> List[AuthorizeInstance]:
        """
        Asynchronously lists AuthorizeInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "text/html"
        
        data = values.of({ 
            'sid': sid,
            'client_id': client_id,
            'state': state,
            'scope': scope,
            'nonce': nonce,
            'code_challenge_method': code_challenge_method,
            'code_challenge': code_challenge,
            'redirect_uri': redirect_uri,
            'response_type': response_type,
            'authorization_details': authorization_details,
            'screen_hint': screen_hint,
            'prompt': prompt,
            'acr_values': acr_values,
            'max_age': max_age,
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [AuthorizeInstance(self._version, item) for item in payload[""]]
        


    def list_with_http_info(self, 
        sid: Union[str, object] = values.unset,
        client_id: Union[str, object] = values.unset,
        state: Union[str, object] = values.unset,
        scope: Union[str, object] = values.unset,
        nonce: Union[str, object] = values.unset,
        code_challenge_method: Union[str, object] = values.unset,
        code_challenge: Union[str, object] = values.unset,
        redirect_uri: Union[str, object] = values.unset,
        response_type: Union[str, object] = values.unset,
        authorization_details: Union[str, object] = values.unset,
        screen_hint: Union[str, object] = values.unset,
        prompt: Union[str, object] = values.unset,
        acr_values: Union[str, object] = values.unset,
        max_age: Union[int, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists AuthorizeInstance and returns headers from first page

        
        :param str sid: Session cookie 
        :param str client_id: The client ID of the application making the authorization request. This is a required parameter for all grant types. 
        :param str state: An opaque value used to maintain state between the request and callback. Recommended for CSRF protection. 
        :param str scope: The scope of the access request. Multiple scopes can be separated by spaces. 
        :param str nonce: String value used to associate a Client session with an ID Token (OpenID Connect). This parameter is used to mitigate replay attacks. 
        :param str code_challenge_method: The method used to generate the code challenge for PKCE. Only S256 is supported. 
        :param str code_challenge: The code challenge for PKCE (Proof Key for Code Exchange). Required when using the authorization code flow with PKCE. 
        :param str redirect_uri: The URI to which the response will be sent after authorization. Must match one of the pre-registered redirect URIs for the client. 
        :param str response_type: The type of response desired from the authorization endpoint. Only 'code' (authorization code flow) is supported. 
        :param str authorization_details: A JSON-encoded array of authorization detail objects per RFC 9396. Each object must contain a \"type\" field. Only types allowed by both the client and the user will be granted. 
        :param str screen_hint: Hosted Login UI hint. \"signup\" routes the user to the signup page; any other value (including missing or unknown) routes to the login page. Only meaningful when the account is in MANAGED (hosted login) credential mode. 
        :param str prompt: Space-delimited list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. Currently supported values: - \"consent\": The Authorization Server MUST prompt the End-User for consent,   even if a prior grant exists or the client is first-party. - \"none\": The Authorization Server MUST NOT display any authentication or   consent user interface. If the end user does not have an active session,   the response is an error redirect with `error=login_required`. If   consent would otherwise be required, the response is an error redirect   with `error=consent_required`. Per OpenID Connect Core 1.0, \"none\" MUST   NOT be combined with any other prompt value; doing so returns   `error=invalid_request`. 
        :param str acr_values: Space-separated list of requested Authentication Context Class Reference values (OpenID Connect). The authorization flow must satisfy the requested ACR; a session that already meets it may short-circuit re-authentication. Used by the hosted-login flow to drive step-up authentication. 
        :param int max_age: Maximum authentication age in seconds (OpenID Connect). If the End-User's last authentication is older than this, the Authorization Server re-authenticates the user even when a valid session exists. An exceeded max_age triggers re-authentication but does not lower the session's current ACR. 
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            sid=sid,
            client_id=client_id,
            state=state,
            scope=scope,
            nonce=nonce,
            code_challenge_method=code_challenge_method,
            code_challenge=code_challenge,
            redirect_uri=redirect_uri,
            response_type=response_type,
            authorization_details=authorization_details,
            screen_hint=screen_hint,
            prompt=prompt,
            acr_values=acr_values,
            max_age=max_age,
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        sid: Union[str, object] = values.unset,
        client_id: Union[str, object] = values.unset,
        state: Union[str, object] = values.unset,
        scope: Union[str, object] = values.unset,
        nonce: Union[str, object] = values.unset,
        code_challenge_method: Union[str, object] = values.unset,
        code_challenge: Union[str, object] = values.unset,
        redirect_uri: Union[str, object] = values.unset,
        response_type: Union[str, object] = values.unset,
        authorization_details: Union[str, object] = values.unset,
        screen_hint: Union[str, object] = values.unset,
        prompt: Union[str, object] = values.unset,
        acr_values: Union[str, object] = values.unset,
        max_age: Union[int, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists AuthorizeInstance and returns headers from first page

        
        :param str sid: Session cookie 
        :param str client_id: The client ID of the application making the authorization request. This is a required parameter for all grant types. 
        :param str state: An opaque value used to maintain state between the request and callback. Recommended for CSRF protection. 
        :param str scope: The scope of the access request. Multiple scopes can be separated by spaces. 
        :param str nonce: String value used to associate a Client session with an ID Token (OpenID Connect). This parameter is used to mitigate replay attacks. 
        :param str code_challenge_method: The method used to generate the code challenge for PKCE. Only S256 is supported. 
        :param str code_challenge: The code challenge for PKCE (Proof Key for Code Exchange). Required when using the authorization code flow with PKCE. 
        :param str redirect_uri: The URI to which the response will be sent after authorization. Must match one of the pre-registered redirect URIs for the client. 
        :param str response_type: The type of response desired from the authorization endpoint. Only 'code' (authorization code flow) is supported. 
        :param str authorization_details: A JSON-encoded array of authorization detail objects per RFC 9396. Each object must contain a \"type\" field. Only types allowed by both the client and the user will be granted. 
        :param str screen_hint: Hosted Login UI hint. \"signup\" routes the user to the signup page; any other value (including missing or unknown) routes to the login page. Only meaningful when the account is in MANAGED (hosted login) credential mode. 
        :param str prompt: Space-delimited list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. Currently supported values: - \"consent\": The Authorization Server MUST prompt the End-User for consent,   even if a prior grant exists or the client is first-party. - \"none\": The Authorization Server MUST NOT display any authentication or   consent user interface. If the end user does not have an active session,   the response is an error redirect with `error=login_required`. If   consent would otherwise be required, the response is an error redirect   with `error=consent_required`. Per OpenID Connect Core 1.0, \"none\" MUST   NOT be combined with any other prompt value; doing so returns   `error=invalid_request`. 
        :param str acr_values: Space-separated list of requested Authentication Context Class Reference values (OpenID Connect). The authorization flow must satisfy the requested ACR; a session that already meets it may short-circuit re-authentication. Used by the hosted-login flow to drive step-up authentication. 
        :param int max_age: Maximum authentication age in seconds (OpenID Connect). If the End-User's last authentication is older than this, the Authorization Server re-authenticates the user even when a valid session exists. An exceeded max_age triggers re-authentication but does not lower the session's current ACR. 
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            sid=sid,
            client_id=client_id,
            state=state,
            scope=scope,
            nonce=nonce,
            code_challenge_method=code_challenge_method,
            code_challenge=code_challenge,
            redirect_uri=redirect_uri,
            response_type=response_type,
            authorization_details=authorization_details,
            screen_hint=screen_hint,
            prompt=prompt,
            acr_values=acr_values,
            max_age=max_age,
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
      sid: Union[str, object] = values.unset,
      client_id: Union[str, object] = values.unset,
      state: Union[str, object] = values.unset,
      scope: Union[str, object] = values.unset,
      nonce: Union[str, object] = values.unset,
      code_challenge_method: Union[str, object] = values.unset,
      code_challenge: Union[str, object] = values.unset,
      redirect_uri: Union[str, object] = values.unset,
      response_type: Union[str, object] = values.unset,
      authorization_details: Union[str, object] = values.unset,
      screen_hint: Union[str, object] = values.unset,
      prompt: Union[str, object] = values.unset,
      acr_values: Union[str, object] = values.unset,
      max_age: Union[int, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> AuthorizePage:
        """
        Retrieve a single page of AuthorizeInstance records from the API.
        Request is executed immediately
        
        :param sid: Session cookie 
        :param client_id: The client ID of the application making the authorization request. This is a required parameter for all grant types. 
        :param state: An opaque value used to maintain state between the request and callback. Recommended for CSRF protection. 
        :param scope: The scope of the access request. Multiple scopes can be separated by spaces. 
        :param nonce: String value used to associate a Client session with an ID Token (OpenID Connect). This parameter is used to mitigate replay attacks. 
        :param code_challenge_method: The method used to generate the code challenge for PKCE. Only S256 is supported. 
        :param code_challenge: The code challenge for PKCE (Proof Key for Code Exchange). Required when using the authorization code flow with PKCE. 
        :param redirect_uri: The URI to which the response will be sent after authorization. Must match one of the pre-registered redirect URIs for the client. 
        :param response_type: The type of response desired from the authorization endpoint. Only 'code' (authorization code flow) is supported. 
        :param authorization_details: A JSON-encoded array of authorization detail objects per RFC 9396. Each object must contain a \"type\" field. Only types allowed by both the client and the user will be granted. 
        :param screen_hint: Hosted Login UI hint. \"signup\" routes the user to the signup page; any other value (including missing or unknown) routes to the login page. Only meaningful when the account is in MANAGED (hosted login) credential mode. 
        :param prompt: Space-delimited list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. Currently supported values: - \"consent\": The Authorization Server MUST prompt the End-User for consent,   even if a prior grant exists or the client is first-party. - \"none\": The Authorization Server MUST NOT display any authentication or   consent user interface. If the end user does not have an active session,   the response is an error redirect with `error=login_required`. If   consent would otherwise be required, the response is an error redirect   with `error=consent_required`. Per OpenID Connect Core 1.0, \"none\" MUST   NOT be combined with any other prompt value; doing so returns   `error=invalid_request`. 
        :param acr_values: Space-separated list of requested Authentication Context Class Reference values (OpenID Connect). The authorization flow must satisfy the requested ACR; a session that already meets it may short-circuit re-authentication. Used by the hosted-login flow to drive step-up authentication. 
        :param max_age: Maximum authentication age in seconds (OpenID Connect). If the End-User's last authentication is older than this, the Authorization Server re-authenticates the user even when a valid session exists. An exceeded max_age triggers re-authentication but does not lower the session's current ACR. 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of AuthorizeInstance
        """
        data = values.of({ 
            'sid': sid,
            'client_id': client_id,
            'state': state,
            'scope': scope,
            'nonce': nonce,
            'code_challenge_method': code_challenge_method,
            'code_challenge': code_challenge,
            'redirect_uri': redirect_uri,
            'response_type': response_type,
            'authorization_details': authorization_details,
            'screen_hint': screen_hint,
            'prompt': prompt,
            'acr_values': acr_values,
            'max_age': max_age,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "text/html"
        

        response = self._version.page(method='GET', uri=self._uri, params=data, headers=headers)
        return AuthorizePage(self._version, response)

    async def page_async(self, 
      sid: Union[str, object] = values.unset,
      client_id: Union[str, object] = values.unset,
      state: Union[str, object] = values.unset,
      scope: Union[str, object] = values.unset,
      nonce: Union[str, object] = values.unset,
      code_challenge_method: Union[str, object] = values.unset,
      code_challenge: Union[str, object] = values.unset,
      redirect_uri: Union[str, object] = values.unset,
      response_type: Union[str, object] = values.unset,
      authorization_details: Union[str, object] = values.unset,
      screen_hint: Union[str, object] = values.unset,
      prompt: Union[str, object] = values.unset,
      acr_values: Union[str, object] = values.unset,
      max_age: Union[int, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> AuthorizePage:
        """
        Asynchronously retrieve a single page of AuthorizeInstance records from the API.
        Request is executed immediately
        
        :param sid: Session cookie 
        :param client_id: The client ID of the application making the authorization request. This is a required parameter for all grant types. 
        :param state: An opaque value used to maintain state between the request and callback. Recommended for CSRF protection. 
        :param scope: The scope of the access request. Multiple scopes can be separated by spaces. 
        :param nonce: String value used to associate a Client session with an ID Token (OpenID Connect). This parameter is used to mitigate replay attacks. 
        :param code_challenge_method: The method used to generate the code challenge for PKCE. Only S256 is supported. 
        :param code_challenge: The code challenge for PKCE (Proof Key for Code Exchange). Required when using the authorization code flow with PKCE. 
        :param redirect_uri: The URI to which the response will be sent after authorization. Must match one of the pre-registered redirect URIs for the client. 
        :param response_type: The type of response desired from the authorization endpoint. Only 'code' (authorization code flow) is supported. 
        :param authorization_details: A JSON-encoded array of authorization detail objects per RFC 9396. Each object must contain a \"type\" field. Only types allowed by both the client and the user will be granted. 
        :param screen_hint: Hosted Login UI hint. \"signup\" routes the user to the signup page; any other value (including missing or unknown) routes to the login page. Only meaningful when the account is in MANAGED (hosted login) credential mode. 
        :param prompt: Space-delimited list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. Currently supported values: - \"consent\": The Authorization Server MUST prompt the End-User for consent,   even if a prior grant exists or the client is first-party. - \"none\": The Authorization Server MUST NOT display any authentication or   consent user interface. If the end user does not have an active session,   the response is an error redirect with `error=login_required`. If   consent would otherwise be required, the response is an error redirect   with `error=consent_required`. Per OpenID Connect Core 1.0, \"none\" MUST   NOT be combined with any other prompt value; doing so returns   `error=invalid_request`. 
        :param acr_values: Space-separated list of requested Authentication Context Class Reference values (OpenID Connect). The authorization flow must satisfy the requested ACR; a session that already meets it may short-circuit re-authentication. Used by the hosted-login flow to drive step-up authentication. 
        :param max_age: Maximum authentication age in seconds (OpenID Connect). If the End-User's last authentication is older than this, the Authorization Server re-authenticates the user even when a valid session exists. An exceeded max_age triggers re-authentication but does not lower the session's current ACR. 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of AuthorizeInstance
        """
        data = values.of({ 
            'sid': sid,
            'client_id': client_id,
            'state': state,
            'scope': scope,
            'nonce': nonce,
            'code_challenge_method': code_challenge_method,
            'code_challenge': code_challenge,
            'redirect_uri': redirect_uri,
            'response_type': response_type,
            'authorization_details': authorization_details,
            'screen_hint': screen_hint,
            'prompt': prompt,
            'acr_values': acr_values,
            'max_age': max_age,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "text/html"
        
        headers["Accept"] = "application/problem+json"
        

        response = await self._version.page_async(method='GET', uri=self._uri, params=data, headers=headers)
        return AuthorizePage(self._version, response)

    def page_with_http_info(self, 
        sid: Union[str, object] = values.unset,
        client_id: Union[str, object] = values.unset,
        state: Union[str, object] = values.unset,
        scope: Union[str, object] = values.unset,
        nonce: Union[str, object] = values.unset,
        code_challenge_method: Union[str, object] = values.unset,
        code_challenge: Union[str, object] = values.unset,
        redirect_uri: Union[str, object] = values.unset,
        response_type: Union[str, object] = values.unset,
        authorization_details: Union[str, object] = values.unset,
        screen_hint: Union[str, object] = values.unset,
        prompt: Union[str, object] = values.unset,
        acr_values: Union[str, object] = values.unset,
        max_age: Union[int, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param sid: Session cookie 
        :param client_id: The client ID of the application making the authorization request. This is a required parameter for all grant types. 
        :param state: An opaque value used to maintain state between the request and callback. Recommended for CSRF protection. 
        :param scope: The scope of the access request. Multiple scopes can be separated by spaces. 
        :param nonce: String value used to associate a Client session with an ID Token (OpenID Connect). This parameter is used to mitigate replay attacks. 
        :param code_challenge_method: The method used to generate the code challenge for PKCE. Only S256 is supported. 
        :param code_challenge: The code challenge for PKCE (Proof Key for Code Exchange). Required when using the authorization code flow with PKCE. 
        :param redirect_uri: The URI to which the response will be sent after authorization. Must match one of the pre-registered redirect URIs for the client. 
        :param response_type: The type of response desired from the authorization endpoint. Only 'code' (authorization code flow) is supported. 
        :param authorization_details: A JSON-encoded array of authorization detail objects per RFC 9396. Each object must contain a \"type\" field. Only types allowed by both the client and the user will be granted. 
        :param screen_hint: Hosted Login UI hint. \"signup\" routes the user to the signup page; any other value (including missing or unknown) routes to the login page. Only meaningful when the account is in MANAGED (hosted login) credential mode. 
        :param prompt: Space-delimited list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. Currently supported values: - \"consent\": The Authorization Server MUST prompt the End-User for consent,   even if a prior grant exists or the client is first-party. - \"none\": The Authorization Server MUST NOT display any authentication or   consent user interface. If the end user does not have an active session,   the response is an error redirect with `error=login_required`. If   consent would otherwise be required, the response is an error redirect   with `error=consent_required`. Per OpenID Connect Core 1.0, \"none\" MUST   NOT be combined with any other prompt value; doing so returns   `error=invalid_request`. 
        :param acr_values: Space-separated list of requested Authentication Context Class Reference values (OpenID Connect). The authorization flow must satisfy the requested ACR; a session that already meets it may short-circuit re-authentication. Used by the hosted-login flow to drive step-up authentication. 
        :param max_age: Maximum authentication age in seconds (OpenID Connect). If the End-User's last authentication is older than this, the Authorization Server re-authenticates the user even when a valid session exists. An exceeded max_age triggers re-authentication but does not lower the session's current ACR. 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with AuthorizePage, status code, and headers
        """
        data = values.of({ 
            'sid': sid,
            'client_id': client_id,
            'state': state,
            'scope': scope,
            'nonce': nonce,
            'code_challenge_method': code_challenge_method,
            'code_challenge': code_challenge,
            'redirect_uri': redirect_uri,
            'response_type': response_type,
            'authorization_details': authorization_details,
            'screen_hint': screen_hint,
            'prompt': prompt,
            'acr_values': acr_values,
            'max_age': max_age,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "text/html"
        

        response, status_code, response_headers = self._version.page_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        page = AuthorizePage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        sid: Union[str, object] = values.unset,
        client_id: Union[str, object] = values.unset,
        state: Union[str, object] = values.unset,
        scope: Union[str, object] = values.unset,
        nonce: Union[str, object] = values.unset,
        code_challenge_method: Union[str, object] = values.unset,
        code_challenge: Union[str, object] = values.unset,
        redirect_uri: Union[str, object] = values.unset,
        response_type: Union[str, object] = values.unset,
        authorization_details: Union[str, object] = values.unset,
        screen_hint: Union[str, object] = values.unset,
        prompt: Union[str, object] = values.unset,
        acr_values: Union[str, object] = values.unset,
        max_age: Union[int, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param sid: Session cookie 
        :param client_id: The client ID of the application making the authorization request. This is a required parameter for all grant types. 
        :param state: An opaque value used to maintain state between the request and callback. Recommended for CSRF protection. 
        :param scope: The scope of the access request. Multiple scopes can be separated by spaces. 
        :param nonce: String value used to associate a Client session with an ID Token (OpenID Connect). This parameter is used to mitigate replay attacks. 
        :param code_challenge_method: The method used to generate the code challenge for PKCE. Only S256 is supported. 
        :param code_challenge: The code challenge for PKCE (Proof Key for Code Exchange). Required when using the authorization code flow with PKCE. 
        :param redirect_uri: The URI to which the response will be sent after authorization. Must match one of the pre-registered redirect URIs for the client. 
        :param response_type: The type of response desired from the authorization endpoint. Only 'code' (authorization code flow) is supported. 
        :param authorization_details: A JSON-encoded array of authorization detail objects per RFC 9396. Each object must contain a \"type\" field. Only types allowed by both the client and the user will be granted. 
        :param screen_hint: Hosted Login UI hint. \"signup\" routes the user to the signup page; any other value (including missing or unknown) routes to the login page. Only meaningful when the account is in MANAGED (hosted login) credential mode. 
        :param prompt: Space-delimited list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. Currently supported values: - \"consent\": The Authorization Server MUST prompt the End-User for consent,   even if a prior grant exists or the client is first-party. - \"none\": The Authorization Server MUST NOT display any authentication or   consent user interface. If the end user does not have an active session,   the response is an error redirect with `error=login_required`. If   consent would otherwise be required, the response is an error redirect   with `error=consent_required`. Per OpenID Connect Core 1.0, \"none\" MUST   NOT be combined with any other prompt value; doing so returns   `error=invalid_request`. 
        :param acr_values: Space-separated list of requested Authentication Context Class Reference values (OpenID Connect). The authorization flow must satisfy the requested ACR; a session that already meets it may short-circuit re-authentication. Used by the hosted-login flow to drive step-up authentication. 
        :param max_age: Maximum authentication age in seconds (OpenID Connect). If the End-User's last authentication is older than this, the Authorization Server re-authenticates the user even when a valid session exists. An exceeded max_age triggers re-authentication but does not lower the session's current ACR. 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with AuthorizePage, status code, and headers
        """
        data = values.of({ 
            'sid': sid,
            'client_id': client_id,
            'state': state,
            'scope': scope,
            'nonce': nonce,
            'code_challenge_method': code_challenge_method,
            'code_challenge': code_challenge,
            'redirect_uri': redirect_uri,
            'response_type': response_type,
            'authorization_details': authorization_details,
            'screen_hint': screen_hint,
            'prompt': prompt,
            'acr_values': acr_values,
            'max_age': max_age,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "text/html"
        
        headers["Accept"] = "application/problem+json"
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        page = AuthorizePage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> AuthorizePage:
        """
        Retrieve a specific page of AuthorizeInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of AuthorizeInstance
        """
        response = self._version.domain.twilio.request(
            'GET',
            target_url
        )
        return AuthorizePage(self._version, response)

    async def get_page_async(self, target_url: str) -> AuthorizePage:
        """
        Asynchronously retrieve a specific page of AuthorizeInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of AuthorizeInstance
        """
        response = await self._version.domain.twilio.request_async(
            'GET',
            target_url
        )
        return AuthorizePage(self._version, response)

    
    def list(self, 
        ciba_request_id: Union[str, object] = values.unset,
        sid: Union[str, object] = values.unset,
    ) -> List[AuthorizeInstance]:
        """
        Lists AuthorizeInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "text/html"
        
        data = values.of({ 
            'ciba_request_id': ciba_request_id,
            'sid': sid,
        })
        payload, _, _ = self._version.fetch_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [AuthorizeInstance(self._version, item) for item in payload[""]]
        

    async def list_async(self, 
        ciba_request_id: Union[str, object] = values.unset,
        sid: Union[str, object] = values.unset,
    ) -> List[AuthorizeInstance]:
        """
        Asynchronously lists AuthorizeInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "text/html"
        
        data = values.of({ 
            'ciba_request_id': ciba_request_id,
            'sid': sid,
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [AuthorizeInstance(self._version, item) for item in payload[""]]
        


    def list_with_http_info(self, 
        ciba_request_id: Union[str, object] = values.unset,
        sid: Union[str, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists AuthorizeInstance and returns headers from first page

        
        :param str ciba_request_id: The internal CIBA request ID identifying the backchannel authentication request to display the consent screen for. 
        :param str sid: Session cookie 
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            ciba_request_id=ciba_request_id,
            sid=sid,
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        ciba_request_id: Union[str, object] = values.unset,
        sid: Union[str, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists AuthorizeInstance and returns headers from first page

        
        :param str ciba_request_id: The internal CIBA request ID identifying the backchannel authentication request to display the consent screen for. 
        :param str sid: Session cookie 
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            ciba_request_id=ciba_request_id,
            sid=sid,
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
      ciba_request_id: Union[str, object] = values.unset,
      sid: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> AuthorizePage:
        """
        Retrieve a single page of AuthorizeInstance records from the API.
        Request is executed immediately
        
        :param ciba_request_id: The internal CIBA request ID identifying the backchannel authentication request to display the consent screen for. 
        :param sid: Session cookie 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of AuthorizeInstance
        """
        data = values.of({ 
            'ciba_request_id': ciba_request_id,
            'sid': sid,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "text/html"
        

        response = self._version.page(method='GET', uri=self._uri, params=data, headers=headers)
        return AuthorizePage(self._version, response)

    async def page_async(self, 
      ciba_request_id: Union[str, object] = values.unset,
      sid: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> AuthorizePage:
        """
        Asynchronously retrieve a single page of AuthorizeInstance records from the API.
        Request is executed immediately
        
        :param ciba_request_id: The internal CIBA request ID identifying the backchannel authentication request to display the consent screen for. 
        :param sid: Session cookie 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of AuthorizeInstance
        """
        data = values.of({ 
            'ciba_request_id': ciba_request_id,
            'sid': sid,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "text/html"
        
        headers["Accept"] = "application/problem+json"
        

        response = await self._version.page_async(method='GET', uri=self._uri, params=data, headers=headers)
        return AuthorizePage(self._version, response)

    def page_with_http_info(self, 
        ciba_request_id: Union[str, object] = values.unset,
        sid: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param ciba_request_id: The internal CIBA request ID identifying the backchannel authentication request to display the consent screen for. 
        :param sid: Session cookie 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with AuthorizePage, status code, and headers
        """
        data = values.of({ 
            'ciba_request_id': ciba_request_id,
            'sid': sid,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "text/html"
        

        response, status_code, response_headers = self._version.page_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        page = AuthorizePage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        ciba_request_id: Union[str, object] = values.unset,
        sid: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param ciba_request_id: The internal CIBA request ID identifying the backchannel authentication request to display the consent screen for. 
        :param sid: Session cookie 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with AuthorizePage, status code, and headers
        """
        data = values.of({ 
            'ciba_request_id': ciba_request_id,
            'sid': sid,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "text/html"
        
        headers["Accept"] = "application/problem+json"
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        page = AuthorizePage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> AuthorizePage:
        """
        Retrieve a specific page of AuthorizeInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of AuthorizeInstance
        """
        response = self._version.domain.twilio.request(
            'GET',
            target_url
        )
        return AuthorizePage(self._version, response)

    async def get_page_async(self, target_url: str) -> AuthorizePage:
        """
        Asynchronously retrieve a specific page of AuthorizeInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of AuthorizeInstance
        """
        response = await self._version.domain.twilio.request_async(
            'GET',
            target_url
        )
        return AuthorizePage(self._version, response)




    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return '<Twilio.Ciam.Users_manisingh_codehq_open_api_spec_ciam_tenanted_openapi_yaml.AuthorizeList>'


