# This spec tests followings
# 1. All types of parameters(query, header, path)

info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - PARAMETERS
  version: 1.11.0
openapi: 3.0.1

paths:
  /v1/parameter/{id}:
    servers:
      - url: https://testparameter.twilio.com
    post:
      operationId: CreateParameter
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier for the enum item
          schema:
            type: string
        - name: queryParamDoubleRequired
          in: query
          description: A single enum value as a query parameter
          required: required
          schema:
            type: string
        - name: queryParamBoolean
          in: query
          description: A single enum value as a query parameter
          required: false
          schema:
            type: boolean
        - name: queryParamString
          in: query
          description: A single enum value as a query parameter
          required: false
          schema:
            type: string
        - name: queryParamInteger
          in: query
          description: A single enum value as a query parameter
          required: false
          schema:
            type: integer

        
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              title: CreateParameterRequest
              properties:
                To:
                  type: string
                  format: phone-number
      responses:
        '201':
          description: Parameter created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  status:
                    type: string
