# This spec tests the token pagination strategy as per Twilio API Standards V1.0

info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - REQUEST BODY TEST
  version: 1.11.0
  x-twilio:
    apiStandards: v1.0
openapi: 3.0.1

components:
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
  schemas:
    SampleResponseObject:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
paths:
  /v2/Services:
    servers:
      - url: https://testparameter.twilio.com
    get:
      operationId: ListService
      description: Retrieve a list of all Services
      parameters:
        - name: pageSize
          in: query
          description: Maximum number of items to return in a single response
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            example: 50
        - name: pageToken
          in: query
          description: A URL-safe, base64-encoded token representing the page of results to return
          required: false
          schema:
            type: string
            example: "eyJwYWdlIjoyLCJxdWVyeSI6ImJvb2tzIn0="
      security:
        - accountSid_authToken: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - services
                  - meta
                properties:
                  services:
                    type: array
                    minItems: 0
                    items:
                      $ref: '#/components/schemas/SampleResponseObject'
                  meta:
                    type: object
                    required:
                      - key
                      - pageSize
                    properties:
                      key:
                        type: string
                        description: The key of the list property contains the actual data items
                        example: "services"
                      pageSize:
                        type: integer
                        description: The actual number of items returned in this response
                        example: 20
                      previousToken:
                        type: string
                        description: Token to fetch the previous page of results
                        example: "eyJwYWdlIjowLCJxdWVyeSI6ImJvb2tzIn0="
                      nextToken:
                        type: string
                        description: Token to fetch the next page of results
                        example: "eyJwYWdlIjoyLCJxdWVyeSI6ImJvb2tzIn0="