components:
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
  schemas:
    RichContent:
      type: object
      properties:
        title:
          type: string
        actions:
          type: object
          properties:
            url:
              type: string

info:
  title: Twilio - Api
  description: This is the public Twilio REST API.
  termsOfService: https://www.twilio.com/legal/tos
  contact:
    name: Twilio Support
    url: https://support.twilio.com
    email: support@twilio.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
openapi: 3.0.1
paths:
  /2010-04-01/Accounts/{AccountSid}/Messages.json:
    servers:
      - url: https://api.twilio.com
    description: A Message resource represents an inbound or outbound message.
    x-twilio:
      defaultOutputProperties:
        - sid
        - from
        - to
        - status
        - direction
        - date_sent
      dependentProperties:
        media:
          mapping:
            account_sid: account_sid
            message_sid: sid
          resource_url: /2010-04-01/Accounts/{account_sid}/Messages/{message_sid}/Media.json
        feedback:
          mapping:
            account_sid: account_sid
            message_sid: sid
          resource_url: /2010-04-01/Accounts/{account_sid}/Messages/{message_sid}/Feedback.json
      parent: /Accounts/{Sid}.json
      pathType: list
    post:
      description: Send a message
      summary: Send a message
      tags:
        - Api20100401Message
      parameters:
        - name: AccountSid
          in: path
          description: The SID of the [Account](https://www.twilio.com/docs/iam/api/account)
            creating the Message resource.
          schema:
            type: string
            minLength: 34
            maxLength: 34
            pattern: ^AC[0-9a-fA-F]{32}$
          required: true
      responses:
        '200':
          description: ok
      security:
        - accountSid_authToken: []
      operationId: CreateMessage
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                content: # name of new property
                  $ref: '#/components/schemas/RichContent'
            encoding:
              content:
                contentType: application/json   # <-- serialize this property as JSON
servers:
  - url: https://api.twilio.com
security:
  - accountSid_authToken: []
