/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Number Pool Service
 * This service is an entry point for all Number Pool CRUD requests.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.twilio.rest.messaging.v1;

import com.twilio.base.Reader;
import com.twilio.base.ResourceSet;
import com.twilio.converter.Promoter;
import com.twilio.exception.ApiConnectionException;
import com.twilio.converter.PrefixedCollapsibleMap;
import com.twilio.converter.Converter;
import com.twilio.exception.ApiException;
import com.twilio.exception.RestException;
import com.twilio.http.HttpMethod;
import com.twilio.http.Request;
import com.twilio.http.Response;
import com.twilio.http.TwilioRestClient;
import com.twilio.rest.Domains;
import com.twilio.base.Page;
import java.time.LocalDate;
import java.time.ZonedDateTime;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.net.URI;
import java.time.format.DateTimeFormatter;
import com.twilio.converter.DateConverter;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import lombok.ToString;

public class UseCaseReader extends Reader<UseCase> {
    private String pathUseCaseSID;

    public UseCaseReader(final String pathUseCaseSID){
        this.pathUseCaseSID = pathUseCaseSID;
    }


    @Override
    public ResourceSet<UseCase> read(final TwilioRestClient client) {
        return new ResourceSet<>(this, client, firstPage(client));
    }

    public Page<UseCase> firstPage(final TwilioRestClient client) {
        String path = "/v2/UseCases/{useCaseSID}";
        path = path.replace("{"+"UseCaseSID"+"}", this.pathUseCaseSID.toString());

        Request request = new Request(
            HttpMethod.GET,
            Domains.MESSAGING.toString(),
            path
        );

        return pageForRequest(client, request);
    }

    private Page<UseCase> pageForRequest(final TwilioRestClient client, final Request request) {
        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException("UseCase read failed: Unable to connect to server");
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(response.getStream(), client.getObjectMapper());
            if (restException == null) {
                throw new ApiException("Server Error, no content");
            }
            throw new ApiException(restException);
        }

        return Page.fromJson(
            "",
            response.getContent(),
            UseCase.class,
            client.getObjectMapper()
        );
    }

    @Override
    public Page<UseCase> previousPage(final Page<UseCase> page, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            page.getPreviousPageUrl(Domains.MESSAGING.toString())
        );
        return pageForRequest(client, request);
    }


    @Override
    public Page<UseCase> nextPage(final Page<UseCase> page, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            page.getNextPageUrl(Domains.MESSAGING.toString())
        );
        return pageForRequest(client, request);
    }

    @Override
    public Page<UseCase> getPage(final String targetUrl, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            targetUrl
        );

        return pageForRequest(client, request);
    }
}
public class UseCaseReader extends Reader<UseCase> {

    public UseCaseReader(){
    }


    @Override
    public ResourceSet<UseCase> read(final TwilioRestClient client) {
        return new ResourceSet<>(this, client, firstPage(client));
    }

    public Page<UseCase> firstPage(final TwilioRestClient client) {
        String path = "/v2/UseCases";

        Request request = new Request(
            HttpMethod.GET,
            Domains.MESSAGING.toString(),
            path
        );

        return pageForRequest(client, request);
    }

    private Page<UseCase> pageForRequest(final TwilioRestClient client, final Request request) {
        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException("UseCase read failed: Unable to connect to server");
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(response.getStream(), client.getObjectMapper());
            if (restException == null) {
                throw new ApiException("Server Error, no content");
            }
            throw new ApiException(restException);
        }

        return Page.fromJson(
            "",
            response.getContent(),
            UseCase.class,
            client.getObjectMapper()
        );
    }

    @Override
    public Page<UseCase> previousPage(final Page<UseCase> page, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            page.getPreviousPageUrl(Domains.MESSAGING.toString())
        );
        return pageForRequest(client, request);
    }


    @Override
    public Page<UseCase> nextPage(final Page<UseCase> page, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            page.getNextPageUrl(Domains.MESSAGING.toString())
        );
        return pageForRequest(client, request);
    }

    @Override
    public Page<UseCase> getPage(final String targetUrl, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            targetUrl
        );

        return pageForRequest(client, request);
    }
}
public class UseCaseReader extends Reader<UseCase> {
    private UseCaseModel.UseCaseRequest useCaseRequest;

    public UseCaseReader(final UseCaseModel.UseCaseRequest useCaseRequest){
        this.useCaseRequest = useCaseRequest;
    }

    public UseCaseReader setUseCaseRequest(final UseCaseModel.UseCaseRequest useCaseRequest){
        this.useCaseRequest = useCaseRequest;
        return this;
    }

    @Override
    public ResourceSet<UseCase> read(final TwilioRestClient client) {
        return new ResourceSet<>(this, client, firstPage(client));
    }

    public Page<UseCase> firstPage(final TwilioRestClient client) {
        String path = "/v2/UseCases";
        path = path.replace("{"+"UseCaseRequest"+"}", this.useCaseRequest.toString());

        Request request = new Request(
            HttpMethod.GET,
            Domains.MESSAGING.toString(),
            path
        );

        return pageForRequest(client, request);
    }

    private Page<UseCase> pageForRequest(final TwilioRestClient client, final Request request) {
        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException("UseCase read failed: Unable to connect to server");
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(response.getStream(), client.getObjectMapper());
            if (restException == null) {
                throw new ApiException("Server Error, no content");
            }
            throw new ApiException(restException);
        }

        return Page.fromJson(
            "",
            response.getContent(),
            UseCase.class,
            client.getObjectMapper()
        );
    }

    @Override
    public Page<UseCase> previousPage(final Page<UseCase> page, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            page.getPreviousPageUrl(Domains.MESSAGING.toString())
        );
        return pageForRequest(client, request);
    }


    @Override
    public Page<UseCase> nextPage(final Page<UseCase> page, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            page.getNextPageUrl(Domains.MESSAGING.toString())
        );
        return pageForRequest(client, request);
    }

    @Override
    public Page<UseCase> getPage(final String targetUrl, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            targetUrl
        );

        return pageForRequest(client, request);
    }
}
public class UseCaseReader extends Reader<UseCase> {
    private String pathUseCaseSID;
    private UseCaseModel.UseCaseRequest useCaseRequest;

    public UseCaseReader(final String pathUseCaseSID, final UseCaseModel.UseCaseRequest useCaseRequest){
        this.pathUseCaseSID = pathUseCaseSID;
        this.useCaseRequest = useCaseRequest;
    }

    public UseCaseReader setUseCaseRequest(final UseCaseModel.UseCaseRequest useCaseRequest){
        this.useCaseRequest = useCaseRequest;
        return this;
    }

    @Override
    public ResourceSet<UseCase> read(final TwilioRestClient client) {
        return new ResourceSet<>(this, client, firstPage(client));
    }

    public Page<UseCase> firstPage(final TwilioRestClient client) {
        String path = "/v2/UseCases/{useCaseSID}";
        path = path.replace("{"+"UseCaseSID"+"}", this.pathUseCaseSID.toString());
        path = path.replace("{"+"UseCaseRequest"+"}", this.useCaseRequest.toString());

        Request request = new Request(
            HttpMethod.GET,
            Domains.MESSAGING.toString(),
            path
        );

        return pageForRequest(client, request);
    }

    private Page<UseCase> pageForRequest(final TwilioRestClient client, final Request request) {
        Response response = client.request(request);

        if (response == null) {
            throw new ApiConnectionException("UseCase read failed: Unable to connect to server");
        } else if (!TwilioRestClient.SUCCESS.test(response.getStatusCode())) {
            RestException restException = RestException.fromJson(response.getStream(), client.getObjectMapper());
            if (restException == null) {
                throw new ApiException("Server Error, no content");
            }
            throw new ApiException(restException);
        }

        return Page.fromJson(
            "",
            response.getContent(),
            UseCase.class,
            client.getObjectMapper()
        );
    }

    @Override
    public Page<UseCase> previousPage(final Page<UseCase> page, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            page.getPreviousPageUrl(Domains.MESSAGING.toString())
        );
        return pageForRequest(client, request);
    }


    @Override
    public Page<UseCase> nextPage(final Page<UseCase> page, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            page.getNextPageUrl(Domains.MESSAGING.toString())
        );
        return pageForRequest(client, request);
    }

    @Override
    public Page<UseCase> getPage(final String targetUrl, final TwilioRestClient client) {
        Request request = new Request(
            HttpMethod.GET,
            targetUrl
        );

        return pageForRequest(client, request);
    }
}
