r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Lookups
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""


from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator, Protocol
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version









class LogInstance(InstanceResource):



    """
    :ivar account_sid: 
    :ivar request_sid: 
    :ivar originating_ip_address: 
    :ivar partition_date: 
    :ivar timestamp: 
    :ivar response_data: 
    :ivar logs: 
    :ivar metadata: 
    """

    def __init__(self, version: Version, payload:Dict[str, Any], request_sid: Optional[str] = None):
        super().__init__(version)

        
        self.account_sid: Optional[str] = payload.get("AccountSid")
        self.request_sid: Optional[str] = payload.get("RequestSid")
        self.originating_ip_address: Optional[str] = payload.get("OriginatingIpAddress")
        self.partition_date: Optional[str] = payload.get("PartitionDate")
        self.timestamp: Optional[str] = payload.get("Timestamp")
        self.response_data: Optional[Dict[str, object]] = payload.get("ResponseData")
        self.logs: Optional[List[str]] = payload.get("Logs")
        self.metadata: Optional[str] = payload.get("Metadata")

        
        
        self._solution = { 
            "request_sid": request_sid or self.request_sid,
        }
        
        
        self._context: Optional[LogContext] = None

    @property
    def _proxy(self) -> "LogContext":
        """
        Generate an instance context for the instance, the context is capable of
        performing various actions. All instance actions are proxied to the context

        :returns: LogContext for this LogInstance
        """
        if self._context is None:
            self._context = LogContext(self._version, request_sid=self._solution['request_sid'],)
        return self._context
    
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = ' '.join('{}={}'.format(k, v) for k, v in self._solution.items())
        return '<Twilio.Lookups.Users_manisingh_codehq_open_api_spec_lookups_v1_openapi_yaml.LogInstance {}>'.format(context)

class LogContext(InstanceContext):


    def __init__(self, version: Version, request_sid: str):
        """
        Initialize the LogContext

        :param version: Version that contains the resource
        :param request_sid: The unique identifier for the log entry
        """
        super().__init__(version)

        
        # Path Solution
        self._solution = { 
            'request_sid': request_sid,
        }
        self._uri = '/Logs/{request_sid}'.format(**self._solution)
        
    
    
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = ' '.join('{}={}'.format(k, v) for k, v in self._solution.items())
        return '<Twilio.Lookups.Users_manisingh_codehq_open_api_spec_lookups_v1_openapi_yaml.LogContext {}>'.format(context)



class LogList(ListResource):
    
    def __init__(self, version: Version):
        """
        Initialize the LogList

        :param version: Version that contains the resource
        
        """
        super().__init__(version)

        
        self._uri = '/Logs'
        
        
    
    def list(self, 
    ) -> List[LogInstance]:
        """
        Lists LogInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "application/json"
        
        data = values.of({ 
        })
        payload, _, _ = self._version.fetch_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [LogInstance(self._version, item) for item in payload[""]]
        

    async def list_async(self, 
    ) -> List[LogInstance]:
        """
        Asynchronously lists LogInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "application/json"
        
        data = values.of({ 
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [LogInstance(self._version, item) for item in payload[""]]
        


    def list_with_http_info(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists LogInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists LogInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> LogPage:
        """
        Retrieve a single page of LogInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of LogInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = self._version.page(method='GET', uri=self._uri, params=data, headers=headers)
        return LogPage(self._version, response)

    async def page_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> LogPage:
        """
        Asynchronously retrieve a single page of LogInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of LogInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = await self._version.page_async(method='GET', uri=self._uri, params=data, headers=headers)
        return LogPage(self._version, response)

    def page_with_http_info(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with LogPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = self._version.page_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        page = LogPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with LogPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        page = LogPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> LogPage:
        """
        Retrieve a specific page of LogInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of LogInstance
        """
        response = self._version.domain.twilio.request(
            'GET',
            target_url
        )
        return LogPage(self._version, response)

    async def get_page_async(self, target_url: str) -> LogPage:
        """
        Asynchronously retrieve a specific page of LogInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of LogInstance
        """
        response = await self._version.domain.twilio.request_async(
            'GET',
            target_url
        )
        return LogPage(self._version, response)

    
    def list(self, 
        
        start_time: Union[str, object] = values.unset,
        end_time: Union[str, object] = values.unset,
        phone_number: Union[str, object] = values.unset,
    ) -> List[LogInstance]:
        """
        Lists LogInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "application/json"
        
        data = values.of({ 
            'StartTime': start_time,
            'EndTime': end_time,
            'PhoneNumber': phone_number,
        })
        payload, _, _ = self._version.fetch_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [LogInstance(self._version, item) for item in payload[""]]
        

    async def list_async(self, 
        
        start_time: Union[str, object] = values.unset,
        end_time: Union[str, object] = values.unset,
        phone_number: Union[str, object] = values.unset,
    ) -> List[LogInstance]:
        """
        Asynchronously lists LogInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "application/json"
        
        data = values.of({ 
            'StartTime': start_time,
            'EndTime': end_time,
            'PhoneNumber': phone_number,
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [LogInstance(self._version, item) for item in payload[""]]
        


    def list_with_http_info(self, 
        
        start_time: Union[str, object] = values.unset,
        end_time: Union[str, object] = values.unset,
        phone_number: Union[str, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists LogInstance and returns headers from first page

        
        :param str start_time: Start time for log entries
        :param str end_time: End time for log entries
        :param str phone_number: Phone number (or part of it) to search logs in E.164 format
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            start_time=start_time,
            end_time=end_time,
            phone_number=phone_number,
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        
        start_time: Union[str, object] = values.unset,
        end_time: Union[str, object] = values.unset,
        phone_number: Union[str, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists LogInstance and returns headers from first page

        
        :param str start_time: Start time for log entries
        :param str end_time: End time for log entries
        :param str phone_number: Phone number (or part of it) to search logs in E.164 format
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            start_time=start_time,
            end_time=end_time,
            phone_number=phone_number,
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
      
      start_time: Union[str, object] = values.unset,
      end_time: Union[str, object] = values.unset,
      phone_number: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> LogPage:
        """
        Retrieve a single page of LogInstance records from the API.
        Request is executed immediately
        
        :param start_time: Start time for log entries
        :param end_time: End time for log entries
        :param phone_number: Phone number (or part of it) to search logs in E.164 format
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of LogInstance
        """
        data = values.of({ 
            'StartTime': start_time,
            'EndTime': end_time,
            'PhoneNumber': phone_number,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = self._version.page(method='GET', uri=self._uri, params=data, headers=headers)
        return LogPage(self._version, response)

    async def page_async(self, 
      
      start_time: Union[str, object] = values.unset,
      end_time: Union[str, object] = values.unset,
      phone_number: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> LogPage:
        """
        Asynchronously retrieve a single page of LogInstance records from the API.
        Request is executed immediately
        
        :param start_time: Start time for log entries
        :param end_time: End time for log entries
        :param phone_number: Phone number (or part of it) to search logs in E.164 format
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of LogInstance
        """
        data = values.of({ 
            'StartTime': start_time,
            'EndTime': end_time,
            'PhoneNumber': phone_number,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = await self._version.page_async(method='GET', uri=self._uri, params=data, headers=headers)
        return LogPage(self._version, response)

    def page_with_http_info(self, 
        
        start_time: Union[str, object] = values.unset,
        end_time: Union[str, object] = values.unset,
        phone_number: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param start_time: Start time for log entries
        :param end_time: End time for log entries
        :param phone_number: Phone number (or part of it) to search logs in E.164 format
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with LogPage, status code, and headers
        """
        data = values.of({ 
            'StartTime': start_time,
            'EndTime': end_time,
            'PhoneNumber': phone_number,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = self._version.page_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        page = LogPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        
        start_time: Union[str, object] = values.unset,
        end_time: Union[str, object] = values.unset,
        phone_number: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param start_time: Start time for log entries
        :param end_time: End time for log entries
        :param phone_number: Phone number (or part of it) to search logs in E.164 format
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with LogPage, status code, and headers
        """
        data = values.of({ 
            'StartTime': start_time,
            'EndTime': end_time,
            'PhoneNumber': phone_number,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        page = LogPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> LogPage:
        """
        Retrieve a specific page of LogInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of LogInstance
        """
        response = self._version.domain.twilio.request(
            'GET',
            target_url
        )
        return LogPage(self._version, response)

    async def get_page_async(self, target_url: str) -> LogPage:
        """
        Asynchronously retrieve a specific page of LogInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of LogInstance
        """
        response = await self._version.domain.twilio.request_async(
            'GET',
            target_url
        )
        return LogPage(self._version, response)



    def get(self, request_sid: str) -> LogContext:
        """
        Constructs a LogContext
        
        :param request_sid: The unique identifier for the log entry
        """
        return LogContext(self._version, request_sid=request_sid)

    def __call__(self, request_sid: str) -> LogContext:
        """
        Constructs a LogContext
        
        :param request_sid: The unique identifier for the log entry
        """
        return LogContext(self._version, request_sid=request_sid)

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return '<Twilio.Lookups.Users_manisingh_codehq_open_api_spec_lookups_v1_openapi_yaml.LogList>'


