r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Conversations
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""


from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator, Protocol
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse

from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version









class NotificationInstance(InstanceResource):



    """
    :ivar account_sid: The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this configuration.
    :ivar chat_service_sid: The SID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) the Configuration applies to.
    :ivar new_message: The Push Notification configuration for New Messages.
    :ivar added_to_conversation: The Push Notification configuration for being added to a Conversation.
    :ivar removed_from_conversation: The Push Notification configuration for being removed from a Conversation.
    :ivar log_enabled: Weather the notification logging is enabled.
    :ivar url: An absolute API resource URL for this configuration.
    """

    def __init__(self, version: Version, payload:Dict[str, Any], chat_service_sid: str):
        super().__init__(version)

        
        self.account_sid: Optional[str] = payload.get("account_sid")
        self.chat_service_sid: Optional[str] = payload.get("chat_service_sid")
        self.new_message: Optional[Dict[str, object]] = payload.get("new_message")
        self.added_to_conversation: Optional[Dict[str, object]] = payload.get("added_to_conversation")
        self.removed_from_conversation: Optional[Dict[str, object]] = payload.get("removed_from_conversation")
        self.log_enabled: Optional[bool] = payload.get("log_enabled")
        self.url: Optional[str] = payload.get("url")

        
        
        self._solution = { 
            "chat_service_sid": chat_service_sid,
        }
        
        
        
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = ' '.join('{}={}'.format(k, v) for k, v in self._solution.items())
        return '<Twilio.Conversations.Users_manisingh_codehq_open_api_spec_conversations_v1_openapi_yaml.NotificationInstance {}>'.format(context)




class NotificationList(ListResource):
    
    def __init__(self, version: Version, chat_service_sid: str):
        """
        Initialize the NotificationList

        :param version: Version that contains the resource
        :param chat_service_sid: The SID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) the Configuration applies to.
        
        """
        super().__init__(version)

        
        # Path Solution
        self._solution = { 'chat_service_sid': chat_service_sid,  }
        self._uri = '/Services/{chat_service_sid}/Configuration/Notifications'.format(**self._solution)
        
        
    
    def _fetch(self) -> tuple:
        """
        Internal helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        
        headers["Accept"] = "application/json"
        
        
        return self._version.fetch_with_response_info(method='GET', uri=self._uri, headers=headers)

    def fetch(self) -> NotificationInstance:
        """
        Fetch the NotificationInstance

        
        :returns: The fetched NotificationInstance
        """
        payload, _, _ = self._fetch()
        return NotificationInstance(self._version, payload, chat_service_sid=self._solution['chat_service_sid'])

    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the NotificationInstance and return response metadata

        
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = self._fetch()
        instance = NotificationInstance(self._version, payload, chat_service_sid=self._solution['chat_service_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)

    async def _fetch_async(self) -> tuple:
        """
        Internal async helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        
        headers["Accept"] = "application/json"
        
        
        return await self._version.fetch_with_response_info_async(method='GET', uri=self._uri, headers=headers)

    async def fetch_async(self) -> NotificationInstance:
        """
        Asynchronously fetch the NotificationInstance

        
        :returns: The fetched NotificationInstance
        """
        payload, _, _ = await self._fetch_async()
        return NotificationInstance(self._version, payload, chat_service_sid=self._solution['chat_service_sid'])

    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronously fetch the NotificationInstance and return response metadata

        
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = await self._fetch_async()
        instance = NotificationInstance(self._version, payload, chat_service_sid=self._solution['chat_service_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)
    
    def list(self, 
    ) -> List[NotificationInstance]:
        """
        Lists NotificationInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = self._version.fetch_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [NotificationInstance(self._version, item, chat_service_sid=self._solution['chat_service_sid']) for item in payload[""]]
        

    async def list_async(self, 
    ) -> List[NotificationInstance]:
        """
        Asynchronously lists NotificationInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [NotificationInstance(self._version, item, chat_service_sid=self._solution['chat_service_sid']) for item in payload[""]]
        


    def list_with_http_info(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists NotificationInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists NotificationInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> NotificationPage:
        """
        Retrieve a single page of NotificationInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of NotificationInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = self._version.page(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return NotificationPage(self._version, response, solution=self._solution)

    async def page_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> NotificationPage:
        """
        Asynchronously retrieve a single page of NotificationInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of NotificationInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = await self._version.page_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return NotificationPage(self._version, response, solution=self._solution)

    def page_with_http_info(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with NotificationPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = self._version.page_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = NotificationPage(self._version, response, solution=self._solution)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with NotificationPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = NotificationPage(self._version, response, solution=self._solution)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> NotificationPage:
        """
        Retrieve a specific page of NotificationInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of NotificationInstance
        """
        response = self._version.domain.twilio.request(
            'OPTIONS',
            target_url
        )
        return NotificationPage(self._version, response, solution=self._solution)

    async def get_page_async(self, target_url: str) -> NotificationPage:
        """
        Asynchronously retrieve a specific page of NotificationInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of NotificationInstance
        """
        response = await self._version.domain.twilio.request_async(
            'OPTIONS',
            target_url
        )
        return NotificationPage(self._version, response, solution=self._solution)

    

    def _update(self, log_enabled: Union[bool, object]=values.unset, new_message_enabled: Union[bool, object]=values.unset, new_message_template: Union[str, object]=values.unset, new_message_sound: Union[str, object]=values.unset, new_message_badge_count_enabled: Union[bool, object]=values.unset, added_to_conversation_enabled: Union[bool, object]=values.unset, added_to_conversation_template: Union[str, object]=values.unset, added_to_conversation_sound: Union[str, object]=values.unset, removed_from_conversation_enabled: Union[bool, object]=values.unset, removed_from_conversation_template: Union[str, object]=values.unset, removed_from_conversation_sound: Union[str, object]=values.unset, new_message_with_media_enabled: Union[bool, object]=values.unset, new_message_with_media_template: Union[str, object]=values.unset) -> tuple:
        """
        Internal helper for update operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        
        data = values.of({ 
            'LogEnabled': serialize.boolean_to_string(log_enabled),
            'NewMessage.Enabled': serialize.boolean_to_string(new_message_enabled),
            'NewMessage.Template': new_message_template,
            'NewMessage.Sound': new_message_sound,
            'NewMessage.BadgeCountEnabled': serialize.boolean_to_string(new_message_badge_count_enabled),
            'AddedToConversation.Enabled': serialize.boolean_to_string(added_to_conversation_enabled),
            'AddedToConversation.Template': added_to_conversation_template,
            'AddedToConversation.Sound': added_to_conversation_sound,
            'RemovedFromConversation.Enabled': serialize.boolean_to_string(removed_from_conversation_enabled),
            'RemovedFromConversation.Template': removed_from_conversation_template,
            'RemovedFromConversation.Sound': removed_from_conversation_sound,
            'NewMessage.WithMedia.Enabled': serialize.boolean_to_string(new_message_with_media_enabled),
            'NewMessage.WithMedia.Template': new_message_with_media_template,
        })
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        headers["Content-Type"] = "application/x-www-form-urlencoded"
        
        
        headers["Accept"] = "application/json"
        
        
        return self._version.update_with_response_info(method='POST', uri=self._uri, data=data, headers=headers)

    def update(self, log_enabled: Union[bool, object]=values.unset, new_message_enabled: Union[bool, object]=values.unset, new_message_template: Union[str, object]=values.unset, new_message_sound: Union[str, object]=values.unset, new_message_badge_count_enabled: Union[bool, object]=values.unset, added_to_conversation_enabled: Union[bool, object]=values.unset, added_to_conversation_template: Union[str, object]=values.unset, added_to_conversation_sound: Union[str, object]=values.unset, removed_from_conversation_enabled: Union[bool, object]=values.unset, removed_from_conversation_template: Union[str, object]=values.unset, removed_from_conversation_sound: Union[str, object]=values.unset, new_message_with_media_enabled: Union[bool, object]=values.unset, new_message_with_media_template: Union[str, object]=values.unset) -> NotificationInstance:
        """
        Update the NotificationInstance

        :param log_enabled: Weather the notification logging is enabled.
        :param new_message_enabled: Whether to send a notification when a new message is added to a conversation. The default is `false`.
        :param new_message_template: The template to use to create the notification text displayed when a new message is added to a conversation and `new_message.enabled` is `true`.
        :param new_message_sound: The name of the sound to play when a new message is added to a conversation and `new_message.enabled` is `true`.
        :param new_message_badge_count_enabled: Whether the new message badge is enabled. The default is `false`.
        :param added_to_conversation_enabled: Whether to send a notification when a participant is added to a conversation. The default is `false`.
        :param added_to_conversation_template: The template to use to create the notification text displayed when a participant is added to a conversation and `added_to_conversation.enabled` is `true`.
        :param added_to_conversation_sound: The name of the sound to play when a participant is added to a conversation and `added_to_conversation.enabled` is `true`.
        :param removed_from_conversation_enabled: Whether to send a notification to a user when they are removed from a conversation. The default is `false`.
        :param removed_from_conversation_template: The template to use to create the notification text displayed to a user when they are removed from a conversation and `removed_from_conversation.enabled` is `true`.
        :param removed_from_conversation_sound: The name of the sound to play to a user when they are removed from a conversation and `removed_from_conversation.enabled` is `true`.
        :param new_message_with_media_enabled: Whether to send a notification when a new message with media/file attachments is added to a conversation. The default is `false`.
        :param new_message_with_media_template: The template to use to create the notification text displayed when a new message with media/file attachments is added to a conversation and `new_message.attachments.enabled` is `true`.
        
        :returns: The updated NotificationInstance
        """
        payload, _, _ = self._update(log_enabled=log_enabled, new_message_enabled=new_message_enabled, new_message_template=new_message_template, new_message_sound=new_message_sound, new_message_badge_count_enabled=new_message_badge_count_enabled, added_to_conversation_enabled=added_to_conversation_enabled, added_to_conversation_template=added_to_conversation_template, added_to_conversation_sound=added_to_conversation_sound, removed_from_conversation_enabled=removed_from_conversation_enabled, removed_from_conversation_template=removed_from_conversation_template, removed_from_conversation_sound=removed_from_conversation_sound, new_message_with_media_enabled=new_message_with_media_enabled, new_message_with_media_template=new_message_with_media_template)
        return NotificationInstance(self._version, payload, chat_service_sid=self._solution['chat_service_sid'])

    def update_with_http_info(self, log_enabled: Union[bool, object]=values.unset, new_message_enabled: Union[bool, object]=values.unset, new_message_template: Union[str, object]=values.unset, new_message_sound: Union[str, object]=values.unset, new_message_badge_count_enabled: Union[bool, object]=values.unset, added_to_conversation_enabled: Union[bool, object]=values.unset, added_to_conversation_template: Union[str, object]=values.unset, added_to_conversation_sound: Union[str, object]=values.unset, removed_from_conversation_enabled: Union[bool, object]=values.unset, removed_from_conversation_template: Union[str, object]=values.unset, removed_from_conversation_sound: Union[str, object]=values.unset, new_message_with_media_enabled: Union[bool, object]=values.unset, new_message_with_media_template: Union[str, object]=values.unset) -> ApiResponse:
        """
        Update the NotificationInstance and return response metadata

        :param log_enabled: Weather the notification logging is enabled.
        :param new_message_enabled: Whether to send a notification when a new message is added to a conversation. The default is `false`.
        :param new_message_template: The template to use to create the notification text displayed when a new message is added to a conversation and `new_message.enabled` is `true`.
        :param new_message_sound: The name of the sound to play when a new message is added to a conversation and `new_message.enabled` is `true`.
        :param new_message_badge_count_enabled: Whether the new message badge is enabled. The default is `false`.
        :param added_to_conversation_enabled: Whether to send a notification when a participant is added to a conversation. The default is `false`.
        :param added_to_conversation_template: The template to use to create the notification text displayed when a participant is added to a conversation and `added_to_conversation.enabled` is `true`.
        :param added_to_conversation_sound: The name of the sound to play when a participant is added to a conversation and `added_to_conversation.enabled` is `true`.
        :param removed_from_conversation_enabled: Whether to send a notification to a user when they are removed from a conversation. The default is `false`.
        :param removed_from_conversation_template: The template to use to create the notification text displayed to a user when they are removed from a conversation and `removed_from_conversation.enabled` is `true`.
        :param removed_from_conversation_sound: The name of the sound to play to a user when they are removed from a conversation and `removed_from_conversation.enabled` is `true`.
        :param new_message_with_media_enabled: Whether to send a notification when a new message with media/file attachments is added to a conversation. The default is `false`.
        :param new_message_with_media_template: The template to use to create the notification text displayed when a new message with media/file attachments is added to a conversation and `new_message.attachments.enabled` is `true`.
        
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = self._update(log_enabled=log_enabled, new_message_enabled=new_message_enabled, new_message_template=new_message_template, new_message_sound=new_message_sound, new_message_badge_count_enabled=new_message_badge_count_enabled, added_to_conversation_enabled=added_to_conversation_enabled, added_to_conversation_template=added_to_conversation_template, added_to_conversation_sound=added_to_conversation_sound, removed_from_conversation_enabled=removed_from_conversation_enabled, removed_from_conversation_template=removed_from_conversation_template, removed_from_conversation_sound=removed_from_conversation_sound, new_message_with_media_enabled=new_message_with_media_enabled, new_message_with_media_template=new_message_with_media_template)
        instance = NotificationInstance(self._version, payload, chat_service_sid=self._solution['chat_service_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)

    async def _update_async(self, log_enabled: Union[bool, object]=values.unset, new_message_enabled: Union[bool, object]=values.unset, new_message_template: Union[str, object]=values.unset, new_message_sound: Union[str, object]=values.unset, new_message_badge_count_enabled: Union[bool, object]=values.unset, added_to_conversation_enabled: Union[bool, object]=values.unset, added_to_conversation_template: Union[str, object]=values.unset, added_to_conversation_sound: Union[str, object]=values.unset, removed_from_conversation_enabled: Union[bool, object]=values.unset, removed_from_conversation_template: Union[str, object]=values.unset, removed_from_conversation_sound: Union[str, object]=values.unset, new_message_with_media_enabled: Union[bool, object]=values.unset, new_message_with_media_template: Union[str, object]=values.unset) -> tuple:
        """
        Internal async helper for update operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        
        data = values.of({ 
            'LogEnabled': serialize.boolean_to_string(log_enabled),
            'NewMessage.Enabled': serialize.boolean_to_string(new_message_enabled),
            'NewMessage.Template': new_message_template,
            'NewMessage.Sound': new_message_sound,
            'NewMessage.BadgeCountEnabled': serialize.boolean_to_string(new_message_badge_count_enabled),
            'AddedToConversation.Enabled': serialize.boolean_to_string(added_to_conversation_enabled),
            'AddedToConversation.Template': added_to_conversation_template,
            'AddedToConversation.Sound': added_to_conversation_sound,
            'RemovedFromConversation.Enabled': serialize.boolean_to_string(removed_from_conversation_enabled),
            'RemovedFromConversation.Template': removed_from_conversation_template,
            'RemovedFromConversation.Sound': removed_from_conversation_sound,
            'NewMessage.WithMedia.Enabled': serialize.boolean_to_string(new_message_with_media_enabled),
            'NewMessage.WithMedia.Template': new_message_with_media_template,
        })
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        headers["Content-Type"] = "application/x-www-form-urlencoded"
        
        
        headers["Accept"] = "application/json"
        
        
        return await self._version.update_with_response_info_async(method='POST', uri=self._uri, data=data, headers=headers)

    async def update_async(self, log_enabled: Union[bool, object]=values.unset, new_message_enabled: Union[bool, object]=values.unset, new_message_template: Union[str, object]=values.unset, new_message_sound: Union[str, object]=values.unset, new_message_badge_count_enabled: Union[bool, object]=values.unset, added_to_conversation_enabled: Union[bool, object]=values.unset, added_to_conversation_template: Union[str, object]=values.unset, added_to_conversation_sound: Union[str, object]=values.unset, removed_from_conversation_enabled: Union[bool, object]=values.unset, removed_from_conversation_template: Union[str, object]=values.unset, removed_from_conversation_sound: Union[str, object]=values.unset, new_message_with_media_enabled: Union[bool, object]=values.unset, new_message_with_media_template: Union[str, object]=values.unset) -> NotificationInstance:
        """
        Asynchronously update the NotificationInstance

        :param log_enabled: Weather the notification logging is enabled.
        :param new_message_enabled: Whether to send a notification when a new message is added to a conversation. The default is `false`.
        :param new_message_template: The template to use to create the notification text displayed when a new message is added to a conversation and `new_message.enabled` is `true`.
        :param new_message_sound: The name of the sound to play when a new message is added to a conversation and `new_message.enabled` is `true`.
        :param new_message_badge_count_enabled: Whether the new message badge is enabled. The default is `false`.
        :param added_to_conversation_enabled: Whether to send a notification when a participant is added to a conversation. The default is `false`.
        :param added_to_conversation_template: The template to use to create the notification text displayed when a participant is added to a conversation and `added_to_conversation.enabled` is `true`.
        :param added_to_conversation_sound: The name of the sound to play when a participant is added to a conversation and `added_to_conversation.enabled` is `true`.
        :param removed_from_conversation_enabled: Whether to send a notification to a user when they are removed from a conversation. The default is `false`.
        :param removed_from_conversation_template: The template to use to create the notification text displayed to a user when they are removed from a conversation and `removed_from_conversation.enabled` is `true`.
        :param removed_from_conversation_sound: The name of the sound to play to a user when they are removed from a conversation and `removed_from_conversation.enabled` is `true`.
        :param new_message_with_media_enabled: Whether to send a notification when a new message with media/file attachments is added to a conversation. The default is `false`.
        :param new_message_with_media_template: The template to use to create the notification text displayed when a new message with media/file attachments is added to a conversation and `new_message.attachments.enabled` is `true`.
        
        :returns: The updated NotificationInstance
        """
        payload, _, _ = await self._update_async(log_enabled=log_enabled, new_message_enabled=new_message_enabled, new_message_template=new_message_template, new_message_sound=new_message_sound, new_message_badge_count_enabled=new_message_badge_count_enabled, added_to_conversation_enabled=added_to_conversation_enabled, added_to_conversation_template=added_to_conversation_template, added_to_conversation_sound=added_to_conversation_sound, removed_from_conversation_enabled=removed_from_conversation_enabled, removed_from_conversation_template=removed_from_conversation_template, removed_from_conversation_sound=removed_from_conversation_sound, new_message_with_media_enabled=new_message_with_media_enabled, new_message_with_media_template=new_message_with_media_template)
        return NotificationInstance(self._version, payload, chat_service_sid=self._solution['chat_service_sid'])

    async def update_with_http_info_async(self, log_enabled: Union[bool, object]=values.unset, new_message_enabled: Union[bool, object]=values.unset, new_message_template: Union[str, object]=values.unset, new_message_sound: Union[str, object]=values.unset, new_message_badge_count_enabled: Union[bool, object]=values.unset, added_to_conversation_enabled: Union[bool, object]=values.unset, added_to_conversation_template: Union[str, object]=values.unset, added_to_conversation_sound: Union[str, object]=values.unset, removed_from_conversation_enabled: Union[bool, object]=values.unset, removed_from_conversation_template: Union[str, object]=values.unset, removed_from_conversation_sound: Union[str, object]=values.unset, new_message_with_media_enabled: Union[bool, object]=values.unset, new_message_with_media_template: Union[str, object]=values.unset) -> ApiResponse:
        """
        Asynchronously update the NotificationInstance and return response metadata

        :param log_enabled: Weather the notification logging is enabled.
        :param new_message_enabled: Whether to send a notification when a new message is added to a conversation. The default is `false`.
        :param new_message_template: The template to use to create the notification text displayed when a new message is added to a conversation and `new_message.enabled` is `true`.
        :param new_message_sound: The name of the sound to play when a new message is added to a conversation and `new_message.enabled` is `true`.
        :param new_message_badge_count_enabled: Whether the new message badge is enabled. The default is `false`.
        :param added_to_conversation_enabled: Whether to send a notification when a participant is added to a conversation. The default is `false`.
        :param added_to_conversation_template: The template to use to create the notification text displayed when a participant is added to a conversation and `added_to_conversation.enabled` is `true`.
        :param added_to_conversation_sound: The name of the sound to play when a participant is added to a conversation and `added_to_conversation.enabled` is `true`.
        :param removed_from_conversation_enabled: Whether to send a notification to a user when they are removed from a conversation. The default is `false`.
        :param removed_from_conversation_template: The template to use to create the notification text displayed to a user when they are removed from a conversation and `removed_from_conversation.enabled` is `true`.
        :param removed_from_conversation_sound: The name of the sound to play to a user when they are removed from a conversation and `removed_from_conversation.enabled` is `true`.
        :param new_message_with_media_enabled: Whether to send a notification when a new message with media/file attachments is added to a conversation. The default is `false`.
        :param new_message_with_media_template: The template to use to create the notification text displayed when a new message with media/file attachments is added to a conversation and `new_message.attachments.enabled` is `true`.
        
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = await self._update_async(log_enabled=log_enabled, new_message_enabled=new_message_enabled, new_message_template=new_message_template, new_message_sound=new_message_sound, new_message_badge_count_enabled=new_message_badge_count_enabled, added_to_conversation_enabled=added_to_conversation_enabled, added_to_conversation_template=added_to_conversation_template, added_to_conversation_sound=added_to_conversation_sound, removed_from_conversation_enabled=removed_from_conversation_enabled, removed_from_conversation_template=removed_from_conversation_template, removed_from_conversation_sound=removed_from_conversation_sound, new_message_with_media_enabled=new_message_with_media_enabled, new_message_with_media_template=new_message_with_media_template)
        instance = NotificationInstance(self._version, payload, chat_service_sid=self._solution['chat_service_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)



    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return '<Twilio.Conversations.Users_manisingh_codehq_open_api_spec_conversations_v1_openapi_yaml.NotificationList>'


