r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Powers the Alerts product within One Admin
    API specifications for the Alerts product within One Admin

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""


from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator, Protocol
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page








class AccountSidInstance(InstanceResource):



    """
    :ivar friendly_name: 
    :ivar alert_config_sid: 
    :ivar date_updated_epoch_milli: 
    :ivar enabled: 
    :ivar is_sub_account_wide: 
    :ivar priority: 
    """

    def __init__(self, version: Version, payload:Dict[str, Any], account_sid: Optional[str] = None, dataset_name: Optional[str] = None):
        super().__init__(version)

        
        self.friendly_name: Optional[str] = payload.get("friendlyName")
        self.alert_config_sid: Optional[str] = payload.get("alertConfigSid")
        self.date_updated_epoch_milli: Optional[int] = payload.get("dateUpdatedEpochMilli")
        self.enabled: Optional[bool] = payload.get("enabled")
        self.is_sub_account_wide: Optional[bool] = payload.get("isSubAccountWide")
        self.priority: Optional["AccountSidInstance.str"] = payload.get("priority")

        
        
        self._solution = { 
            "account_sid": account_sid or self.account_sid,
            "dataset_name": dataset_name or self.dataset_name,
        }
        
        
        self._context: Optional[AccountSidContext] = None

    @property
    def _proxy(self) -> "AccountSidContext":
        """
        Generate an instance context for the instance, the context is capable of
        performing various actions. All instance actions are proxied to the context

        :returns: AccountSidContext for this AccountSidInstance
        """
        if self._context is None:
            self._context = AccountSidContext(self._version, account_sid=self._solution['account_sid'], dataset_name=self._solution['dataset_name'],)
        return self._context
    
    
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = ' '.join('{}={}'.format(k, v) for k, v in self._solution.items())
        return '<Twilio.AlertsAdminApiUs1.Users_manisingh_codehq_open_api_spec_alerts_v1_openapi_yaml.AccountSidInstance {}>'.format(context)

class AccountSidContext(InstanceContext):


    def __init__(self, version: Version, account_sid: str, dataset_name: str):
        """
        Initialize the AccountSidContext

        :param version: Version that contains the resource
        :param account_sid: 
        :param dataset_name: 
        """
        super().__init__(version)

        
        # Path Solution
        self._solution = { 
            'account_sid': account_sid,
            'dataset_name': dataset_name,
        }
        self._uri = '/alerts/{account_sid}/{dataset_name}'.format(**self._solution)
        
    
    
    
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = ' '.join('{}={}'.format(k, v) for k, v in self._solution.items())
        return '<Twilio.AlertsAdminApiUs1.Users_manisingh_codehq_open_api_spec_alerts_v1_openapi_yaml.AccountSidContext {}>'.format(context)



class AccountSidPage(Page):

    def get_instance(self, payload: Dict[str, Any]) -> AccountSidInstance:
        """
        Build an instance of AccountSidInstance

        :param payload: Payload response from the API
        """
        
        return AccountSidInstance(self._version, payload)
        

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return "<Twilio.AlertsAdminApiUs1.Users_manisingh_codehq_open_api_spec_alerts_v1_openapi_yaml.AccountSidPage>"




class AccountSidPage(Page):

    def get_instance(self, payload: Dict[str, Any]) -> AccountSidInstance:
        """
        Build an instance of AccountSidInstance

        :param payload: Payload response from the API
        """
        
        return AccountSidInstance(self._version, payload)
        

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return "<Twilio.AlertsAdminApiUs1.Users_manisingh_codehq_open_api_spec_alerts_v1_openapi_yaml.AccountSidPage>"





class AccountSidList(ListResource):
    
    def __init__(self, version: Version):
        """
        Initialize the AccountSidList

        :param version: Version that contains the resource
        
        """
        super().__init__(version)

        
        
        
        

    def get(self, account_sid: str, dataset_name: str) -> AccountSidContext:
        """
        Constructs a AccountSidContext
        
        :param account_sid: 
        :param dataset_name: 
        """
        return AccountSidContext(self._version, account_sid=account_sid, dataset_name=dataset_name)

    def __call__(self, account_sid: str, dataset_name: str) -> AccountSidContext:
        """
        Constructs a AccountSidContext
        
        :param account_sid: 
        :param dataset_name: 
        """
        return AccountSidContext(self._version, account_sid=account_sid, dataset_name=dataset_name)

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return '<Twilio.AlertsAdminApiUs1.Users_manisingh_codehq_open_api_spec_alerts_v1_openapi_yaml.AccountSidList>'


