    ##
#    This code was generated by
#    ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
#    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
#    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
#
#    Twilio - Accounts
#    This is the public Twilio REST API.
#
#    NOTE: This class is auto generated by OpenAPI Generator.
#    https://openapi-generator.tech
#    Do not edit the class manually.
#


module Twilio
    module REST
        class FlexApi < Domain
            class V1 < Version
                class CredentialList < ListResource
                    ##
                    # Initialize the CredentialList
                    # @param [Version] version Version that contains the resource
                    # @return [CredentialList] CredentialList
                    def initialize(version)
                        super(version)
                        # Path Solution
                        @solution = {  }
                        @uri = "/Credentials"
                        #Components
                        @aws = nil
                    end
                
                    
                    ##
                ##
                # Access the aws
                # @return [AwsList]
                # @return [AwsContext] if sid was passed.
                def aws(sid=:unset)
                    raise ArgumentError, 'sid cannot be nil' if sid.nil?

                    if sid != :unset
                        return AwsContext.new(@version,sid )
                    end

                    @aws ||= AwsList.new(@version )
                end

                    # Provide a user friendly representation
                    def to_s
                        '#<Twilio.FlexApi.V1.CredentialList>'
                    end
                end
            end
        end
    end
end
