r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Video
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""


from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator, Protocol
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse

from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version









class MediaInstance(InstanceResource):



    """
    :ivar redirect_to: The URL of the media file.
    """

    def __init__(self, version: Version, payload:Dict[str, Any], composition_sid: str):
        super().__init__(version)

        
        self.redirect_to: Optional[str] = payload.get("redirect_to")

        
        
        self._solution = { 
            "composition_sid": composition_sid,
        }
        
        
        
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = ' '.join('{}={}'.format(k, v) for k, v in self._solution.items())
        return '<Twilio.Video.Users_manisingh_codehq_open_api_spec_video_v1_openapi_yaml.MediaInstance {}>'.format(context)




class MediaList(ListResource):
    
    def __init__(self, version: Version, composition_sid: str):
        """
        Initialize the MediaList

        :param version: Version that contains the resource
        :param composition_sid: The SID of the Composition resource with the media to fetch.
        
        """
        super().__init__(version)

        
        # Path Solution
        self._solution = { 'composition_sid': composition_sid,  }
        self._uri = '/Compositions/{composition_sid}/Media'.format(**self._solution)
        
        
    
    def _fetch(self, ttl: Union[int, object]=values.unset, content_disposition: Union[str, object]=values.unset) -> tuple:
        """
        Internal helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        
        headers["Accept"] = "application/json"
        
        params = values.of({
                'Ttl': ttl,
                'ContentDisposition': content_disposition,
                
            })
        
        return self._version.fetch_with_response_info(method='GET', uri=self._uri, headers=headers, params=params)

    def fetch(self, ttl: Union[int, object]=values.unset, content_disposition: Union[str, object]=values.unset) -> MediaInstance:
        """
        Fetch the MediaInstance

        :param ttl: The time in seconds that the `redirect_to` URL can be used to retrieve the media file. The maximum duration is 604,800 seconds (7 days).:param content_disposition: The `Content-Disposition` header value to set in the `redirect_to` response. Can be: `attachment` or `inline`. The default value is `attachment%3B%20filename%3D%22RTxx.xxx%22`
        :returns: The fetched MediaInstance
        """
        payload, _, _ = self._fetch(ttl=ttl, content_disposition=content_disposition)
        return MediaInstance(self._version, payload, composition_sid=self._solution['composition_sid'])

    def fetch_with_http_info(self, ttl: Union[int, object]=values.unset, content_disposition: Union[str, object]=values.unset) -> ApiResponse:
        """
        Fetch the MediaInstance and return response metadata

        :param ttl: The time in seconds that the `redirect_to` URL can be used to retrieve the media file. The maximum duration is 604,800 seconds (7 days).:param content_disposition: The `Content-Disposition` header value to set in the `redirect_to` response. Can be: `attachment` or `inline`. The default value is `attachment%3B%20filename%3D%22RTxx.xxx%22`
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = self._fetch(ttl=ttl, content_disposition=content_disposition)
        instance = MediaInstance(self._version, payload, composition_sid=self._solution['composition_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)

    async def _fetch_async(self, ttl: Union[int, object]=values.unset, content_disposition: Union[str, object]=values.unset) -> tuple:
        """
        Internal async helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        headers = values.of({
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        
        
        headers["Accept"] = "application/json"
        
        params = values.of({
                'Ttl': ttl,
                'ContentDisposition': content_disposition,
                
            })
        
        return await self._version.fetch_with_response_info_async(method='GET', uri=self._uri, headers=headers, params=params)

    async def fetch_async(self, ttl: Union[int, object]=values.unset, content_disposition: Union[str, object]=values.unset) -> MediaInstance:
        """
        Asynchronously fetch the MediaInstance

        :param ttl: The time in seconds that the `redirect_to` URL can be used to retrieve the media file. The maximum duration is 604,800 seconds (7 days).:param content_disposition: The `Content-Disposition` header value to set in the `redirect_to` response. Can be: `attachment` or `inline`. The default value is `attachment%3B%20filename%3D%22RTxx.xxx%22`
        :returns: The fetched MediaInstance
        """
        payload, _, _ = await self._fetch_async(ttl=ttl, content_disposition=content_disposition)
        return MediaInstance(self._version, payload, composition_sid=self._solution['composition_sid'])

    async def fetch_with_http_info_async(self, ttl: Union[int, object]=values.unset, content_disposition: Union[str, object]=values.unset) -> ApiResponse:
        """
        Asynchronously fetch the MediaInstance and return response metadata

        :param ttl: The time in seconds that the `redirect_to` URL can be used to retrieve the media file. The maximum duration is 604,800 seconds (7 days).:param content_disposition: The `Content-Disposition` header value to set in the `redirect_to` response. Can be: `attachment` or `inline`. The default value is `attachment%3B%20filename%3D%22RTxx.xxx%22`
        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = await self._fetch_async(ttl=ttl, content_disposition=content_disposition)
        instance = MediaInstance(self._version, payload, composition_sid=self._solution['composition_sid'])
        return ApiResponse(data=instance, status_code=status_code, headers=headers)
    
    def list(self, 
    ) -> List[MediaInstance]:
        """
        Lists MediaInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = self._version.fetch_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [MediaInstance(self._version, item, composition_sid=self._solution['composition_sid']) for item in payload[""]]
        

    async def list_async(self, 
    ) -> List[MediaInstance]:
        """
        Asynchronously lists MediaInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [MediaInstance(self._version, item, composition_sid=self._solution['composition_sid']) for item in payload[""]]
        


    def list_with_http_info(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists MediaInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists MediaInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> MediaPage:
        """
        Retrieve a single page of MediaInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of MediaInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = self._version.page(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return MediaPage(self._version, response, solution=self._solution)

    async def page_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> MediaPage:
        """
        Asynchronously retrieve a single page of MediaInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of MediaInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = await self._version.page_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return MediaPage(self._version, response, solution=self._solution)

    def page_with_http_info(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with MediaPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = self._version.page_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = MediaPage(self._version, response, solution=self._solution)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with MediaPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = MediaPage(self._version, response, solution=self._solution)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> MediaPage:
        """
        Retrieve a specific page of MediaInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of MediaInstance
        """
        response = self._version.domain.twilio.request(
            'OPTIONS',
            target_url
        )
        return MediaPage(self._version, response, solution=self._solution)

    async def get_page_async(self, target_url: str) -> MediaPage:
        """
        Asynchronously retrieve a specific page of MediaInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of MediaInstance
        """
        response = await self._version.domain.twilio.request_async(
            'OPTIONS',
            target_url
        )
        return MediaPage(self._version, response, solution=self._solution)




    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return '<Twilio.Video.Users_manisingh_codehq_open_api_spec_video_v1_openapi_yaml.MediaList>'


