components:
  schemas:
    test.response_object:
      properties:
        account_sid:
          nullable: true
          format: foobar
          type: string
        sid:
          nullable: true
          type: string
        test_string:
          nullable: true
          type: string
        test_integer:
          nullable: true
          type: integer
        test_object:
          nullable: true
          format: phone-number-capabilities
          properties:
            fax:
              type: boolean
            mms:
              type: boolean
            sms:
              type: boolean
            voice:
              type: boolean
          type: object
        test_date_time:
          format: date-time-rfc-2822
          nullable: true
          type: string
        test_number:
          nullable: true
          type: number
        price_unit:
          nullable: true
          format: currency
          type: string
          example: "USD"
        test_number_float:
          nullable: true
          type: number
          format: float
        test_enum:
          enum:
            - DialVerb
            - Trunking
          nullable: true
          type: string
        test_array_of_integers:
          items:
            type: integer
          type: array
        test_array_of_array_of_integers:
          type: array
          items:
            type: array
            items:
              type: integer
        test_array_of_objects:
          items:
            format: feedback-issue
            properties:
              count:
                type: number
              description:
                type: string
            type: object
          nullable: true
          type: array
      type: object
  examples:
    test.response_object.example:
      value:
        sid: "CR12345678123456781234567812345678"
        test_string: "Ahoy"
        test_object:
          fax: false
          mms: false
          sms: true
          voice: true
        test_number_float: 100.22
        test_enum: "Trunking"
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Accounts
  version: 1.11.0
openapi: 3.0.1
paths:
  /v1/Credentials/AWS:
    get:
      operationId: ListCredentialAws
      parameters:
        - in: query
          name: PageSize
          schema:
            maximum: 1000
            minimum: 1
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  credentials:
                    items:
                      $ref: '#/components/schemas/test.response_object'
                    type: array
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                    type: object
                title: ListCredentialAwsResponse
                type: object
              examples:
                creds_response_example:
                  summary: Example of a Credential
                  value:
                    credentials: [
                      {
                        "account_sid": "AC12345678123456781234567812345678",
                        "sid": "CR12345678123456781234567812345678",
                        "test_string": "Ahoy",
                      }
                    ]
                    meta: {
                      first_page_url: "http://example.com/page1",
                      next_page_url: "http://example.com/page2",
                      page: 1,
                      page_size: 3,
                      previous_page_url: "http://example.com/page0",
                      url: "http://example.com"
                    }
          description: OK
      security:
        - accountSid_authToken: [ ]
    post:
      operationId: CreateCredentialAws
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                TestString:
                  type: string
                TestBoolean:
                  type: boolean
                TestInteger:
                  type: integer
                TestNumber:
                  type: number
                TestNumberFloat:
                  type: number
                  format: float
                TestNumberDouble:
                  type: number
                  format: double
                TestNumberInt32:
                  type: number
                  format: int32
                TestNumberInt64:
                  type: integer
                  format: int64
                TestObject:
                  type: object
                  format: object
                TestDateTime:
                  type: string
                  format: date-time
                TestDate:
                  type: string
                  format: date
                TestEnum:
                  enum:
                    - consumer-checking
                    - consumer-savings
                    - commercial-checking
                TestObjectArray:
                  items:
                    type: object
                  type: array
                TestAnyType: { }
              required:
                - TestString
              title: CreateCredentialAwsRequest
              type: object
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test.response_object'
              examples:
                example:
                  $ref: '#/components/examples/test.response_object.example'
          description: Created
      security:
        - accountSid_authToken: [ ]
    servers:
      - url: https://api.twilio.com
  /v1/Credentials/AWS/{Sid}:
    delete:
      operationId: DeleteCredentialAws
      parameters:
        - in: path
          name: Sid
          required: true
          schema:
            maxLength: 34
            minLength: 34
            pattern: ^CR[0-9a-fA-F]{32}$
            type: string
      responses:
        '204':
          description: The resource was deleted successfully.
      security:
        - accountSid_authToken: [ ]
    get:
      operationId: FetchCredentialAws
      parameters:
        - in: path
          name: Sid
          required: true
          schema:
            maxLength: 34
            minLength: 34
            pattern: ^CR[0-9a-fA-F]{32}$
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test.response_object'
              examples:
                example:
                  $ref: '#/components/examples/test.response_object.example'
          description: OK
      security:
        - accountSid_authToken: [ ]
    post:
      operationId: UpdateCredentialAws
      parameters:
        - in: path
          name: Sid
          required: true
          schema:
            maxLength: 34
            minLength: 34
            pattern: ^CR[0-9a-fA-F]{32}$
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                TestString:
                  type: string
              title: UpdateCredentialAwsRequest
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test.response_object'
              examples:
                example:
                  $ref: '#/components/examples/test.response_object.example'
          description: OK
      security:
        - accountSid_authToken: [ ]
    servers:
      - url: https://api.twilio.com
  /2010-04-01/Accounts/{AccountSid}/Calls.json:
    description: A top-level resource, dose not support listing
    post:
      operationId: CreateCall
      parameters:
        - in: path
          name: AccountSid
          required: true
          schema:
            maxLength: 34
            minLength: 34
            pattern: ^AC[0-9a-fA-F]{32}$
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                RequiredStringProperty:
                  type: string
                TestArrayOfStrings:
                  items:
                    type: string
                  type: array
              required:
                - RequiredStringProperty
              title: CreateCallRequest
              type: object
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test.response_object'
          description: Created
      security:
        - accountSid_authToken: [ ]
    servers:
      - url: https://api.twilio.com
  /2010-04-01/Accounts/{AccountSid}/Calls/{Sid}.json:
    description: A top-level resource instance that cannot be updated
    delete:
      operationId: DeleteCall
      parameters:
        - in: path
          name: AccountSid
          required: true
          schema:
            type: string
        - in: path
          name: Sid
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The resource was deleted successfully.
      security:
        - accountSid_authToken: [ ]
    get:
      operationId: FetchCall
      parameters:
        - in: path
          name: AccountSid
          required: true
          schema:
            type: string
        - in: path
          name: Sid
          required: true
          schema:
            type: string
      responses:
        '307':
          description: Test that an operation with no 2XX responses is handled properly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test.response_object'
              examples:
                example:
                  $ref: '#/components/examples/test.response_object.example'
      security:
        - accountSid_authToken: [ ]
    servers:
      - url: https://api.twilio.com
  /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings.json:
    description: A nested resource
    get:
      operationId: ListCallRecording
      parameters:
        - in: path
          name: AccountSid
          required: true
          schema:
            type: string
        - in: path
          name: CallSid
          required: true
          schema:
            type: string
        - in: query
          name: DateCreated
          schema:
            format: date-time
            type: string
        - in: query
          name: Date.Test
          schema:
            format: date
            type: string
        - in: query
          name: DateCreated<
          schema:
            format: date-time
            type: string
        - in: query
          name: DateCreated>
          schema:
            format: date-time
            type: string
        - in: query
          name: PageSize
          schema:
            maximum: 1000
            minimum: 1
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  end:
                    type: integer
                  first_page_uri:
                    format: uri
                    type: string
                  next_page_uri:
                    format: uri
                    type: string
                  page:
                    type: integer
                  page_size:
                    type: integer
                  previous_page_uri:
                    format: uri
                    type: string
                  recordings:
                    items:
                      $ref: '#/components/schemas/test.response_object'
                    type: array
                  start:
                    type: integer
                  uri:
                    format: uri
                    type: string
                title: ListCallRecordingResponse
                type: object
              examples:
                call_recording_response:
                  summary: Example of Call Recodings
                  value: {
                    "end": 5,
                    "first_page_uri": "http://example.com/page1",
                    "next_page_uri": "http://example.com/page2",
                    "page": 1,
                    "page_size": 4,
                    "previous_page_uri": "http://example.com/page0",
                    "recordings": [
                      {
                        "test_string": "Ahoy",
                      },
                      {
                        "test_string": "Matey"
                      }
                    ],
                    "start": 0,
                    "uri": "http://example.com",
                    "response_nested_array": [ 1,2,3 ]
                  }
          description: OK
      security:
        - accountSid_authToken: [ ]
    post:
      operationId: CreateCallRecording
      parameters:
        - in: header
          name: X-Twilio-Webhook-Enabled
          schema:
            enum:
              - 'true'
              - 'false'
            type: string
        - in: path
          name: AccountSid
          required: true
          schema:
            type: string
        - in: path
          name: CallSid
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                RecordingStatusCallback:
                  format: uri
                  type: string
                RecordingStatusCallbackEvent:
                  items:
                    type: string
                  type: array
              title: CreateCallRecordingRequest
              type: object
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test.response_object'
              examples:
                example:
                  $ref: '#/components/examples/test.response_object.example'
          description: Created
      security:
        - accountSid_authToken: [ ]
    servers:
      - url: https://api.twilio.com
  /2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{TestInteger}.json:
    description: A nested resource instance
    delete:
      operationId: DeleteCallRecording
      parameters:
        - in: path
          name: AccountSid
          required: true
          schema:
            type: string
        - in: path
          name: CallSid
          required: true
          schema:
            type: string
        - description: INTEGER ID param!!!
          in: path
          name: TestInteger
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: The resource was deleted successfully.
      security:
        - accountSid_authToken: [ ]
    get:
      operationId: FetchCallRecording
      parameters:
        - in: path
          name: AccountSid
          required: true
          schema:
            type: string
        - in: path
          name: CallSid
          required: true
          schema:
            type: string
        - description: INTEGER ID param!!!
          in: path
          name: TestInteger
          required: true
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test.response_object'
          description: OK
      security:
        - accountSid_authToken: [ ]
    post:
      operationId: UpdateCallRecording
      parameters:
        - in: path
          name: AccountSid
          required: true
          schema:
            type: string
        - in: path
          name: CallSid
          required: true
          schema:
            type: string
        - description: INTEGER ID param!!!
          in: path
          name: TestInteger
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                PauseBehavior:
                  type: string
                Status:
                  enum:
                    - in-progress
                    - paused
                    - stopped
                    - processing
                    - completed
                    - absent
                  type: string
              required:
                - Status
              title: UpdateCallRecordingRequest
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test.response_object'
          description: OK
      security:
        - accountSid_authToken: [ ]
    servers:
      - url: https://api.twilio.com
  /2010-04-01/Accounts/{AccountSid}/Calls/FeedbackSummary.json:
    description: A resource that can only be created
    post:
      operationId: CreateCallFeedbackSummary
      parameters:
        - in: path
          name: AccountSid
          required: true
          schema:
            maxLength: 34
            minLength: 34
            pattern: ^AC[0-9a-fA-F]{32}$
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                EndDate:
                  format: date
                  type: string
                StartDate:
                  format: date
                  type: string
              required:
                - StartDate
                - EndDate
              title: CreateCallFeedbackSummaryRequest
              type: object
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test.response_object'
              examples:
                custom_type_response_example:
                  summary: Example of a Feedback Summary
                  value: {
                    "test_array_of_objects": [ {
                      "count": 4,
                      "description": "issue description",
                    } ],
                  }
          description: Created
      security:
        - accountSid_authToken: [ ]
    servers:
      - url: https://api.twilio.com
    x-twilio:
      className: feedback_call_summary
      parent: custom_call
