openapi: 3.0.3
info:
  title: Bulk Messaging API
  description: This is the public Twilio REST API for 1:Many Message creation.
  termsOfService: https://www.twilio.com/legal/tos
  version: 1.0.0-alpha.1
  contact:
    name: Twilio Support
    url: https://support.twilio.com
    email: support@twilio.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://preview.messaging.twilio.com
paths:
  /v1/Messages:
    post:
      description: Send messages to multiple recipients
      operationId: CreateMessages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: CreateMessagesRequest
              properties:
                Messages:
                  type: array
                  items:
                    $ref: '#/components/schemas/messaging.v1.Message'
                From:
                  type: string
                  format: phone-number
                  description: A Twilio phone number in [E.164](https://www.twilio.com/docs/glossary/what-e164)
                    format, an [alphanumeric sender ID](https://www.twilio.com/docs/sms/send-messages#use-an-alphanumeric-sender-id),
                    or a [Channel Endpoint address](https://www.twilio.com/docs/sms/channels#channel-addresses)
                    that is enabled for the type of message you want to send. Phone
                    numbers or [short codes](https://www.twilio.com/docs/sms/api/short-code)
                    purchased from Twilio also work here. You cannot, for example,
                    spoof messages from a private cell phone number. If you are using
                    `messaging_service_sid`, this parameter must be empty.
                MessagingServiceSid:
                  type: string
                  minLength: 34
                  maxLength: 34
                  pattern: ^MG[0-9a-fA-F]{32}$
                  description: The SID of the [Messaging Service](https://www.twilio.com/docs/sms/services#send-a-message-with-copilot)
                    you want to associate with the Message. Set this parameter to
                    use the [Messaging Service Settings and Copilot Features](https://www.twilio.com/console/sms/services)
                    you have configured and leave the `from` parameter empty. When
                    only this parameter is set, Twilio will use your enabled Copilot
                    Features to select the `from` phone number for delivery.
                phone_number_prices:
                  type: array
                  items:
                    type: object
                    format: phone-number-price
                    properties:
                      base_price:
                        type: number
                      current_price:
                        type: number
                      number_type:
                        type: string
                  nullable: true
                  description: The list of [PhoneNumberPrice](https://www.twilio.com/docs/phone-numbers/pricing#phone-number-price)
                    records.
                StatusCallbackMethod2:
                  type: string
                  format: http-method
                  enum:
                    - HEAD
                    - GET
                    - POST
                    - PATCH
                    - PUT
                    - DELETE
                  description: 'The HTTP method we should use when requesting the
                    `status_callback` URL. Can be: `GET` or `POST` and the default
                    is `POST`. If an `application_sid` parameter is present, this
                    parameter is ignored.'
                ScheduleType2:
                  type: string
                  $ref: '#/components/schemas/message_enum_schedule_type'
                  description: 'For Messaging Services only: Include this parameter
                                    with a value of `fixed` in conjuction with the `send_time` parameter
                                    in order to [schedule a Message](https://www.twilio.com/docs/messaging/features/message-scheduling).'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messaging.v1.CreateMessagesResult'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messaging.v1.Error'
      security:
      - accountSid_authToken: []
components:
  schemas:
    messaging.v1.Message:
      type: object
      properties:
        To:
          type: string
          format: phone-number
          description: The destination phone number in [E.164](https://www.twilio.com/docs/glossary/what-e164)
            format for SMS/MMS or [Channel user address](https://www.twilio.com/docs/sms/channels#channel-addresses)
            for other 3rd-party channels.
        Body:
          type: string
          description: The text of the message you want to send. Can be up to 1,600
            characters in length. Overrides the request-level body and content template
            if provided.
        ContentVariables:
          type: object
          additionalProperties:
            type: string
          description: Key-value pairs of variable names to substitution values. Refer
            to the [Twilio Content API Resources](https://www.twilio.com/docs/content-api/content-api-resources#send-a-message-with-preconfigured-content)
            for more details.
          
        test_object:
          nullable: true
          format: phone-number-capabilities
          properties:
            fax:
              type: boolean
            mms:
              type: boolean
            sms:
              type: boolean
            voice:
              type: boolean
          type: object
        StatusCallbackMethod:
          type: string
          format: http-method
          enum:
            - HEAD
            - GET
            - POST
            - PATCH
            - PUT
            - DELETE
          description: 'The HTTP method we should use when requesting the
            `status_callback` URL. Can be: `GET` or `POST` and the default
            is `POST`. If an `application_sid` parameter is present, this
            parameter is ignored.'
        ScheduleType:
          type: string
          $ref: '#/components/schemas/message_enum_schedule_type'
          description: 'For Messaging Services only: Include this parameter
                            with a value of `fixed` in conjuction with the `send_time` parameter
                            in order to [schedule a Message](https://www.twilio.com/docs/messaging/features/message-scheduling).'
    messaging.v1.MessageReceipt:
      type: object
      properties:
        to:
          type: string
          nullable: true
          description: The recipient phone number
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^(SM|MM)[0-9a-fA-F]{32}$
          nullable: true
          description: The unique string that identifies the resource
    messaging.v1.FailedMessageReceipt:
      type: object
      properties:
        to:
          type: string
          description: The recipient phone number
        error_message:
          type: string
          description: The description of the error_code
        error_code:
          type: integer
          description: The error code associated with the message creation attempt
    messaging.v1.CreateMessagesResult:
      properties:
        total_message_count:
          type: integer
          description: The number of Messages processed in the request, equal to the
            sum of success_count and error_count.
        success_count:
          type: integer
          description: The number of Messages successfully created.
        error_count:
          type: integer
          description: The number of Messages unsuccessfully processed in the request.
        message_receipts:
          type: array
          items:
            $ref: '#/components/schemas/messaging.v1.MessageReceipt'
        failed_message_receipts:
          type: array
          items:
            $ref: '#/components/schemas/messaging.v1.FailedMessageReceipt'
    messaging.v1.Error:
      type: object
      properties:
        message:
          type: string
          description: The error message details
        code:
          type: integer
          description: The Twilio error code
        status:
          type: integer
          description: The HTTP status code
        more_info:
          type: string
          description: More information on the error
    message_enum_schedule_type:
      type: string
      enum:
        - fixed
        - variable
  securitySchemes:
    accountSid_authToken:
      type: http
      scheme: basic
