openapi: 3.0.3
info:
  title: Number Pool Service
  description: |-
    This service is an entry point for all Number Pool CRUD requests.
  version: 1.0.0
  contact:
    name: 'Number Pool Service'
    url: 'https://wiki.hq.twilio.com/display/MSG/Messaging+Services'
  license:
    name: 'Proprietary and protected.'
    url: 'https://www.twilio.com'
paths:
  '/v2/Accounts/{AccountSid}/NumberPools':
    servers:
      - url: https://messaging.twilio.com
    get:
      tags:
        - NumberPools
      summary: Gets a Page of Number Pool instances.
      description: >
        Returns a Page of Number Pool instances with HATEOS style navigation
      operationId: ListNumberPools
      parameters:
        - name: AccountSid
          in: path
          description: AccountSid
          required: true
          schema:
            type: string
        - name: DateCreated
          in: query
          schema:
            format: date-time
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                properties:
                  numberpools:
                    items:
                      $ref: '#/components/schemas/NumberPoolResponse'
              examples:
                example:
                  $ref: '#/components/examples/NumberPoolResponse.example'
        '5XX':
          description: Unexpected error.
      externalDocs:
        description: Learn more about user operations provided by this API.
        url: https://www.twilio.com/docs/nextgen/api/number-pools
    post:
      tags:
        - NumberPools
      summary: Creates a new Number Pool instances
      description: >
        Creates a Number Pool and it's details
      operationId: CreateNumberPool
      parameters:
        - name: AccountSid
          in: path
          description: AccountSid
          required: true
          schema:
            type: string
      requestBody:
        description: The Number Pool to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NumberPoolRequest'
      responses:
        '201':
          description: Successful creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NumberPoolResponse'
        '404':
          description: A Number Pool with the specified ID was not found.
        '5XX':
          description: Unexpected error.
      externalDocs:
        description: Learn more about user operations provided by this API.
        url: https://www.twilio.com/docs/nextgen/api/number-pools
  '/v2/Accounts/{AccountSid}/NumberPools/{NumberPoolSID}':
    servers:
      - url: https://messaging.twilio.com
    get:
      tags:
        - NumberPools
      summary: Gets a Number Pool by ID.
      description: >
        Return a specific number pool and it's details
      operationId: FetchNumberPoolById
      parameters:
        - name: AccountSid
          in: path
          description: AccountSid
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/numberPoolSID'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NumberPoolResponse'
        '404':
          description: A Number Pool with the specified ID was not found.
        '5XX':
          description: Unexpected error.
      externalDocs:
        description: Learn more about user operations provided by this API.
        url: https://www.twilio.com/docs/nextgen/api/number-pools
    post:
      tags:
        - NumberPools
      summary: Updates a Number Pool by ID.
      description: >
        Updates a Number Pool and it's details
      operationId: UpdateNumberPoolById
      parameters:
        - name: AccountSid
          in: path
          description: AccountSid
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/numberPoolSID'
      requestBody:
        description: The Number Pool to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NumberPoolRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NumberPoolResponse'
        '404':
          description: A Number Pool with the specified ID was not found.
        '5XX':
          description: Unexpected error.
      externalDocs:
        description: Learn more about user operations provided by this API.
        url: https://www.twilio.com/docs/nextgen/api/number-pools
    delete:
      tags:
        - NumberPools
      summary: Deletes a Number Pool by ID.
      description: >
        Deletes a Number Pool and it's details
      operationId: DeleteNumberPoolById
      parameters:
        - name: AccountSid
          in: path
          description: AccountSid
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/numberPoolSID'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NumberPoolResponse'
        '404':
          description: A Number Pool with the specified ID was not found.
        '5XX':
          description: Unexpected error.
      externalDocs:
        description: Learn more about user operations provided by this API.
        url: https://www.twilio.com/docs/nextgen/api/number-pools
components:
  schemas:
    NumberPoolRequest:
      type: object
      properties:
        name:
          type: string
        senders:
          type: array
          items:
            type: string
        callback_url:
          type: string
        mode:
          type: string
          enum:
            - sms
            - voice
            - vedio
        number_test_date_time:
          format: date-time-rfc-2822
          nullable: true
          type: string
          example: "Thu, 01 Sep 2016 10:11:12.123456 -0500"
        number_test_object:
          nullable: true
          format: phone-number-capabilities
          properties:
            fax:
              type: boolean
            mms:
              type: boolean
            sms:
              type: boolean
            voice:
              type: boolean
        nested_number_object:
          $ref: '#/components/schemas/NumberNestedTest'
      required:
        - name
        - senders
    NumberPoolResponse:
      type: object
      properties:
        name:
          type: string
    NumberNestedTest:
      type: object
      properties:
        nested_mode:
          type: string
          enum:
            - sms
            - voice
            - vedio
        nested_number_test_date_time:
          format: date-time-rfc-2822
          nullable: true
          type: string
          example: "Thu, 01 Sep 2016 10:11:12.123456 -0500"
        nested_number_phone_number:
          nullable: true
          format: phone-number-capabilities
          properties:
            fax:
              type: boolean
            mms:
              type: boolean
            sms:
              type: boolean
            voice:
              type: boolean
      required:
        - nested_mode
  examples:
    NumberPoolResponse.example:
      value:
        meta:
          url: "http://localhost:8000/v2/Accounts/123456789/NumberPools/"
          next_page_url: "http://localhost:8000/v2/Accounts/123456789/NumberPools/"
          previous_page_url: "http://localhost:8000/v2/Accounts/123456789/NumberPools/"
          first_page_url: "http://localhost:8000/v2/Accounts/123456789/NumberPools/"
          page_size: 5
        numberPools:
          - id: "123"
            name: "Number"
            sender: ["math01"]
            callback_url: "math.twilio.com/123"
            mode: "sms"
            number_test_date_time: "Thu, 01 Sep 2016 10:11:12.123456 -0500"
            number_test_object:
              fax: false
              mms: false
              sms: true
              voice: true
            nested_number_object:
              nested_mode: ""
              nested_number_test_date_time: "Mon, 22 Oct 2003 09:01:02.323232 -0500"
              nested_number_phone_number:
                  fax: false
                  mms: false
                  sms: true
                  voice: true

  parameters:
    numberPoolSID:
      name: numberPoolSID
      in: path
      description: Number Pool ID
      required: true
      schema:
        type: string
    useCaseSID:
      name: useCaseSID
      in: path
      description: Use Case ID
      required: true
      schema:
        type: string
