openapi: 3.0.3
info:
  title: Request Body with oneOf Example
  version: 1.0.0

paths:
  /submit_shape:
    servers:
      - url: https://messaging.twilio.com
    post:
      summary: Submit a shape
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: CreateShapeRequest
              oneOf:
                - $ref: '#/components/schemas/Circle'
                - $ref: '#/components/schemas/Square'
                - $ref: '#/components/schemas/Triangle'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

components:
  schemas:
    Circle:
      type: object
      properties:
        shapeType:
          type: string
          enum: [circle]
        radius:
          type: number
      required:
        - shapeType
        - radius

    Square:
      type: object
      properties:
        shapeType:
          type: string
          enum: [square]
        sideLength:
          type: number
      required:
        - shapeType
        - sideLength

    Triangle:
      type: object
      properties:
        shapeType:
          type: string
          enum: [triangle]
        base:
          type: number
        height:
          type: number
      required:
        - shapeType
        - base
        - height
