r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    API definition for fx console api
    Powers console UI

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""


from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator, Protocol
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse

from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version









class PaymentHistoryInstance(InstanceResource):



    """
    :ivar results: 
    :ivar meta: 
    :ivar payment_history_meta: 
    """

    def __init__(self, version: Version, payload:Dict[str, Any], billing_profile_id: Optional[str] = None):
        super().__init__(version)

        
        self.results: Optional[List[str]] = payload.get("results")
        self.meta: Optional[str] = payload.get("meta")
        self.payment_history_meta: Optional[str] = payload.get("paymentHistoryMeta")

        
        
        self._solution = { 
            "billing_profile_id": billing_profile_id or self.billing_profile_id,
        }
        
        
        
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = ' '.join('{}={}'.format(k, v) for k, v in self._solution.items())
        return '<Twilio.Billing.Users_manisingh_codehq_open_api_spec_billing_v1_openapi_yaml.PaymentHistoryInstance {}>'.format(context)




class PaymentHistoryList(ListResource):
    
    def __init__(self, version: Version, billing_profile_id: str):
        """
        Initialize the PaymentHistoryList

        :param version: Version that contains the resource
        :param billing_profile_id: 
        
        """
        super().__init__(version)

        
        # Path Solution
        self._solution = { 'billing_profile_id': billing_profile_id,  }
        self._uri = '/BillingProfiles/{billing_profile_id}/Billing/PaymentHistory'.format(**self._solution)
        
        
    
    def list(self, 
        year: Union[str, object] = values.unset,
        month: Union[str, object] = values.unset,
        
        sort_by: Union[str, object] = values.unset,
        sort_order: Union[str, object] = values.unset,
    ) -> List[PaymentHistoryInstance]:
        """
        Lists PaymentHistoryInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "application/json"
        
        data = values.of({ 
            'year': year,
            'month': month,
            'sortBy': sort_by,
            'sortOrder': sort_order,
        })
        payload, _, _ = self._version.fetch_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [PaymentHistoryInstance(self._version, item, billing_profile_id=self._solution['billing_profile_id']) for item in payload[""]]
        

    async def list_async(self, 
        year: Union[str, object] = values.unset,
        month: Union[str, object] = values.unset,
        
        sort_by: Union[str, object] = values.unset,
        sort_order: Union[str, object] = values.unset,
    ) -> List[PaymentHistoryInstance]:
        """
        Asynchronously lists PaymentHistoryInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "application/json"
        
        data = values.of({ 
            'year': year,
            'month': month,
            'sortBy': sort_by,
            'sortOrder': sort_order,
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [PaymentHistoryInstance(self._version, item, billing_profile_id=self._solution['billing_profile_id']) for item in payload[""]]
        


    def list_with_http_info(self, 
        year: Union[str, object] = values.unset,
        month: Union[str, object] = values.unset,
        
        sort_by: Union[str, object] = values.unset,
        sort_order: Union[str, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists PaymentHistoryInstance and returns headers from first page

        
        :param str year: The year to filter payment history by.
        :param str month: The month to filter payment history by.
        :param str sort_by: Field to sort by
        :param str sort_order: 
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            year=year,
            month=month,
            sort_by=sort_by,
            sort_order=sort_order,
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        year: Union[str, object] = values.unset,
        month: Union[str, object] = values.unset,
        
        sort_by: Union[str, object] = values.unset,
        sort_order: Union[str, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists PaymentHistoryInstance and returns headers from first page

        
        :param str year: The year to filter payment history by.
        :param str month: The month to filter payment history by.
        :param str sort_by: Field to sort by
        :param str sort_order: 
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            year=year,
            month=month,
            sort_by=sort_by,
            sort_order=sort_order,
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
      year: Union[str, object] = values.unset,
      month: Union[str, object] = values.unset,
      
      sort_by: Union[str, object] = values.unset,
      sort_order: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> PaymentHistoryPage:
        """
        Retrieve a single page of PaymentHistoryInstance records from the API.
        Request is executed immediately
        
        :param year: The year to filter payment history by.
        :param month: The month to filter payment history by.
        :param sort_by: Field to sort by
        :param sort_order: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of PaymentHistoryInstance
        """
        data = values.of({ 
            'year': year,
            'month': month,
            'sortBy': sort_by,
            'sortOrder': sort_order,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = self._version.page(method='GET', uri=self._uri, params=data, headers=headers)
        return PaymentHistoryPage(self._version, response, solution=self._solution)

    async def page_async(self, 
      year: Union[str, object] = values.unset,
      month: Union[str, object] = values.unset,
      
      sort_by: Union[str, object] = values.unset,
      sort_order: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> PaymentHistoryPage:
        """
        Asynchronously retrieve a single page of PaymentHistoryInstance records from the API.
        Request is executed immediately
        
        :param year: The year to filter payment history by.
        :param month: The month to filter payment history by.
        :param sort_by: Field to sort by
        :param sort_order: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of PaymentHistoryInstance
        """
        data = values.of({ 
            'year': year,
            'month': month,
            'sortBy': sort_by,
            'sortOrder': sort_order,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = await self._version.page_async(method='GET', uri=self._uri, params=data, headers=headers)
        return PaymentHistoryPage(self._version, response, solution=self._solution)

    def page_with_http_info(self, 
        year: Union[str, object] = values.unset,
        month: Union[str, object] = values.unset,
        
        sort_by: Union[str, object] = values.unset,
        sort_order: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param year: The year to filter payment history by.
        :param month: The month to filter payment history by.
        :param sort_by: Field to sort by
        :param sort_order: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with PaymentHistoryPage, status code, and headers
        """
        data = values.of({ 
            'year': year,
            'month': month,
            'sortBy': sort_by,
            'sortOrder': sort_order,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = self._version.page_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        page = PaymentHistoryPage(self._version, response, solution=self._solution)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        year: Union[str, object] = values.unset,
        month: Union[str, object] = values.unset,
        
        sort_by: Union[str, object] = values.unset,
        sort_order: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param year: The year to filter payment history by.
        :param month: The month to filter payment history by.
        :param sort_by: Field to sort by
        :param sort_order: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with PaymentHistoryPage, status code, and headers
        """
        data = values.of({ 
            'year': year,
            'month': month,
            'sortBy': sort_by,
            'sortOrder': sort_order,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        page = PaymentHistoryPage(self._version, response, solution=self._solution)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> PaymentHistoryPage:
        """
        Retrieve a specific page of PaymentHistoryInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of PaymentHistoryInstance
        """
        response = self._version.domain.twilio.request(
            'GET',
            target_url
        )
        return PaymentHistoryPage(self._version, response, solution=self._solution)

    async def get_page_async(self, target_url: str) -> PaymentHistoryPage:
        """
        Asynchronously retrieve a specific page of PaymentHistoryInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of PaymentHistoryInstance
        """
        response = await self._version.domain.twilio.request_async(
            'GET',
            target_url
        )
        return PaymentHistoryPage(self._version, response, solution=self._solution)




    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return '<Twilio.Billing.Users_manisingh_codehq_open_api_spec_billing_v1_openapi_yaml.PaymentHistoryList>'


