components:
  schemas:
    accounts.v1.credential:
      properties: { }
      type: object
    accounts.v1.credential.credential_aws:
      properties:
        account_sid:
          description: The SID of the Account that created the resource
          maxLength: 34
          minLength: 34
          nullable: true
          pattern: ^AC[0-9a-fA-F]{32}$
          type: string
        date_created:
          description: The RFC 2822 date and time in GMT when the resource was created
          format: date-time
          nullable: true
          type: string
        date_updated:
          description: The RFC 2822 date and time in GMT when the resource was last
            updated
          format: date-time
          nullable: true
          type: string
        friendly_name:
          description: The string that you assigned to describe the resource
          nullable: true
          type: string
        sid:
          description: The unique string that identifies the resource
          maxLength: 34
          minLength: 34
          nullable: true
          pattern: ^CR[0-9a-fA-F]{32}$
          type: string
        url:
          description: The URI for this resource, relative to `https://accounts.twilio.com`
          format: uri
          nullable: true
          type: string
      type: object
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Accounts
  version: 1.11.0
openapi: 3.0.1
paths:
  /v1/Credentials/AWS:
    description: User provided AWS keys
    get:
      description: Retrieves a collection of AWS Credentials belonging to the account
        used to make the request
      operationId: ListCredentialAws
      parameters:
        - description: How many resources to return in each list page. The default is
            50, and the maximum is 1000.
          in: query
          name: PageSize
          schema:
            maximum: 1000
            minimum: 1
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  credentials:
                    items:
                      $ref: '#/components/schemas/accounts.v1.credential.credential_aws'
                    type: array
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                    type: object
                title: ListCredentialAwsResponse
                type: object
              examples:
                creds_response_example:
                  summary: Example of a Credential
                  value:
                    credentials: [
                      {
                        "account_sid": "AC2C5555A9A7eBBAAACaD0D010eAd2Ec2c",
                        "date_created": "2021-03-23T08:30:00Z",
                        "date_updated": "2021-03-26T08:30:00Z",
                        "friendly_name": "Ahoy",
                        "sid": "CR2C5555A9A7eBBAAACaD0D010eAd2Ec2d",
                        "url": "http://example.com"
                      }
                    ]
                    meta: {
                      first_page_url: "http://example.com/page1",
                      next_page_url: "http://example.com/page2",
                      page: 1,
                      page_size: 3,
                      previous_page_url: "http://example.com/page0",
                      url: "http://example.com"
                    }
          description: OK
      security:
        - accountSid_authToken: [ ]
      x-maturity:
        - GA
    post:
      description: Create a new AWS Credential
      operationId: CreateCredentialAws
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                AccountSid:
                  description: The SID of the Subaccount that this Credential should
                    be associated with. Must be a valid Subaccount of the account
                    issuing the request.
                  maxLength: 34
                  minLength: 34
                  pattern: ^AC[0-9a-fA-F]{32}$
                  type: string
                Credentials:
                  description: A string that contains the AWS access credentials in
                    the format `<AWS_ACCESS_KEY_ID>:<AWS_SECRET_ACCESS_KEY>`. For
                    example, `AKIAIOSFODNN7EXAMPLE:wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY`
                  type: string
                FriendlyName:
                  description: A descriptive string that you create to describe the
                    resource. It can be up to 64 characters long.
                  type: string
              required:
                - Credentials
              title: CreateCredentialAwsRequest
              type: object
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accounts.v1.credential.credential_aws'
          description: Created
      security:
        - accountSid_authToken: [ ]
      x-maturity:
        - GA
    servers:
      - url: https://accounts.twilio.com
    x-default-output-properties: &id001
      - sid
      - friendly_name
      - date_created
    x-path-type: list
  /v1/Credentials/AWS/{Sid}:
    delete:
      description: Delete a Credential from your account
      operationId: DeleteCredentialAws
      parameters:
        - description: The Twilio-provided string that uniquely identifies the AWS resource
            to delete.
          in: path
          name: Sid
          required: true
          schema:
            maxLength: 34
            minLength: 34
            pattern: ^CR[0-9a-fA-F]{32}$
            type: string
      responses:
        '204':
          description: The resource was deleted successfully.
      security:
        - accountSid_authToken: [ ]
      x-maturity:
        - GA
    description: User provided AWS keys
    get:
      description: Fetch the AWS credentials specified by the provided Credential
        Sid
      operationId: FetchCredentialAws
      parameters:
        - description: The Twilio-provided string that uniquely identifies the AWS resource
            to fetch.
          in: path
          name: Sid
          required: true
          schema:
            maxLength: 34
            minLength: 34
            pattern: ^CR[0-9a-fA-F]{32}$
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accounts.v1.credential.credential_aws'
          description: OK
      security:
        - accountSid_authToken: [ ]
      x-maturity:
        - GA
    post:
      description: Modify the properties of a given Account
      operationId: UpdateCredentialAws
      parameters:
        - description: The Twilio-provided string that uniquely identifies the AWS resource
            to update.
          in: path
          name: Sid
          required: true
          schema:
            maxLength: 34
            minLength: 34
            pattern: ^CR[0-9a-fA-F]{32}$
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                FriendlyName:
                  description: A descriptive string that you create to describe the
                    resource. It can be up to 64 characters long.
                  type: string
              title: UpdateCredentialAwsRequest
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accounts.v1.credential.credential_aws'
          description: OK
      security:
        - accountSid_authToken: [ ]
      x-maturity:
        - GA
    servers:
      - url: https://accounts.twilio.com
    x-default-output-properties: *id001
    x-path-type: instance
x-maturity:
  - description: This product is Generally Available.
    name: GA
