r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Preview
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""

from typing import Optional
from twilio.base.version import Version
from twilio.base.domain import Domain
from twilio.rest.preview.profile_connector.configurations import ConfigurationsList
from twilio.rest.preview.profile_connector.connector_instances import ConnectorInstancesList
from twilio.rest.preview.profile_connector.events import EventsList
from twilio.rest.preview.profile_connector.find_profile import FindProfileList
from twilio.rest.preview.profile_connector.identifiers import IdentifiersList
from twilio.rest.preview.profile_connector.instances import InstancesList
from twilio.rest.preview.profile_connector.profile import ProfileList
from twilio.rest.preview.profile_connector.profile_config_secrets import ProfileConfigSecretsList
from twilio.rest.preview.profile_connector.traits import TraitsList


class ProfileConnector(Version):

    def __init__(self, domain: Domain):
        """
        Initialize the ProfileConnector version of Preview

        :param domain: The Twilio.preview domain
        """
        super().__init__(domain, "ProfileConnector")
        self._configurations: Optional[ConfigurationsList] = None
        self._connector_instances: Optional[ConnectorInstancesList] = None
        self._events: Optional[EventsList] = None
        self._find_profile: Optional[FindProfileList] = None
        self._identifiers: Optional[IdentifiersList] = None
        self._instances: Optional[InstancesList] = None
        self._profile: Optional[ProfileList] = None
        self._profile_config_secrets: Optional[ProfileConfigSecretsList] = None
        self._traits: Optional[TraitsList] = None
        
    @property
    def configurations(self) -> ConfigurationsList:
        if self._configurations is None:
            self._configurations = ConfigurationsList(self)
        return self._configurations

    @property
    def connector_instances(self) -> ConnectorInstancesList:
        if self._connector_instances is None:
            self._connector_instances = ConnectorInstancesList(self)
        return self._connector_instances

    @property
    def events(self) -> EventsList:
        if self._events is None:
            self._events = EventsList(self)
        return self._events

    @property
    def find_profile(self) -> FindProfileList:
        if self._find_profile is None:
            self._find_profile = FindProfileList(self)
        return self._find_profile

    @property
    def identifiers(self) -> IdentifiersList:
        if self._identifiers is None:
            self._identifiers = IdentifiersList(self)
        return self._identifiers

    @property
    def instances(self) -> InstancesList:
        if self._instances is None:
            self._instances = InstancesList(self)
        return self._instances

    @property
    def profile(self) -> ProfileList:
        if self._profile is None:
            self._profile = ProfileList(self)
        return self._profile

    @property
    def profile_config_secrets(self) -> ProfileConfigSecretsList:
        if self._profile_config_secrets is None:
            self._profile_config_secrets = ProfileConfigSecretsList(self)
        return self._profile_config_secrets

    @property
    def traits(self) -> TraitsList:
        if self._traits is None:
            self._traits = TraitsList(self)
        return self._traits

    def __repr__(self) -> str:
        """
        Provide a friendly representation
        :returns: Machine friendly representation
        """
        return "<Twilio.Preview.ProfileConnector>"
