r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Suppliers
    Powers Twilio Suppliers Management

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""


from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator, Protocol
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse

from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version









class IgnoredInstance(InstanceResource):


    class CreateIgnoredProvider(object):
        """
            :ivar application: 
            :ivar comments: 
            :ivar created_by: 
            :ivar provider_sid: 
        """

        def __init__(self, payload: Dict[str, Any]):

            
            self.application: Optional[str] = payload.get("application")
            self.comments: Optional[str] = payload.get("comments")
            self.created_by: Optional[str] = payload.get("createdBy")
            self.provider_sid: Optional[str] = payload.get("providerSid")

        def to_dict(self):
            return {
                
                    "application": self.application,
                    "comments": self.comments,
                    "createdBy": self.created_by,
                    "providerSid": self.provider_sid,
            }



    """
    :ivar application: 
    :ivar comments: 
    :ivar created_by: 
    :ivar date_created: 
    :ivar id: 
    :ivar provider_sid: 
    """

    def __init__(self, version: Version, payload:Dict[str, Any]):
        super().__init__(version)

        
        self.application: Optional[str] = payload.get("application")
        self.comments: Optional[str] = payload.get("comments")
        self.created_by: Optional[str] = payload.get("createdBy")
        self.date_created: Optional[datetime] = deserialize.iso8601_datetime(payload.get("dateCreated"))
        self.id: Optional[int] = deserialize.integer(payload.get("id"))
        self.provider_sid: Optional[str] = payload.get("providerSid")

        
        
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        
        return '<Twilio.SuppliersAdminApiUs1.Users_manisingh_codehq_open_api_spec_suppliers_v1_openapi_yaml.IgnoredInstance>'




class IgnoredList(ListResource):
    
    class CreateIgnoredProvider(object):
        """
            :ivar application: 
            :ivar comments: 
            :ivar created_by: 
            :ivar provider_sid: 
        """

        def __init__(self, payload: Dict[str, Any]):

            
            self.application: Optional[str] = payload.get("application")
            self.comments: Optional[str] = payload.get("comments")
            self.created_by: Optional[str] = payload.get("createdBy")
            self.provider_sid: Optional[str] = payload.get("providerSid")

        def to_dict(self):
            return {
                
                    "application": self.application,
                    "comments": self.comments,
                    "createdBy": self.created_by,
                    "providerSid": self.provider_sid,
            }


    def __init__(self, version: Version):
        """
        Initialize the IgnoredList

        :param version: Version that contains the resource
        
        """
        super().__init__(version)

        
        self._uri = '/providers/ignored'
        
        
    
    def list(self, 
        application: Union[str, object] = values.unset,
    ) -> List[IgnoredInstance]:
        """
        Lists IgnoredInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "application/json"
        
        data = values.of({ 
            'application': application,
        })
        payload, _, _ = self._version.fetch_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [IgnoredInstance(self._version, item) for item in payload[""]]
        

    async def list_async(self, 
        application: Union[str, object] = values.unset,
    ) -> List[IgnoredInstance]:
        """
        Asynchronously lists IgnoredInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "application/json"
        
        data = values.of({ 
            'application': application,
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        
        return [IgnoredInstance(self._version, item) for item in payload[""]]
        


    def list_with_http_info(self, 
        application: Union[str, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists IgnoredInstance and returns headers from first page

        
        :param str application: 
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            application=application,
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        application: Union[str, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists IgnoredInstance and returns headers from first page

        
        :param str application: 
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            application=application,
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
      application: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> IgnoredPage:
        """
        Retrieve a single page of IgnoredInstance records from the API.
        Request is executed immediately
        
        :param application: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of IgnoredInstance
        """
        data = values.of({ 
            'application': application,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = self._version.page(method='GET', uri=self._uri, params=data, headers=headers)
        return IgnoredPage(self._version, response)

    async def page_async(self, 
      application: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> IgnoredPage:
        """
        Asynchronously retrieve a single page of IgnoredInstance records from the API.
        Request is executed immediately
        
        :param application: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of IgnoredInstance
        """
        data = values.of({ 
            'application': application,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = await self._version.page_async(method='GET', uri=self._uri, params=data, headers=headers)
        return IgnoredPage(self._version, response)

    def page_with_http_info(self, 
        application: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param application: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with IgnoredPage, status code, and headers
        """
        data = values.of({ 
            'application': application,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = self._version.page_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        page = IgnoredPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        application: Union[str, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param application: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with IgnoredPage, status code, and headers
        """
        data = values.of({ 
            'application': application,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        page = IgnoredPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> IgnoredPage:
        """
        Retrieve a specific page of IgnoredInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of IgnoredInstance
        """
        response = self._version.domain.twilio.request(
            'GET',
            target_url
        )
        return IgnoredPage(self._version, response)

    async def get_page_async(self, target_url: str) -> IgnoredPage:
        """
        Asynchronously retrieve a specific page of IgnoredInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of IgnoredInstance
        """
        response = await self._version.domain.twilio.request_async(
            'GET',
            target_url
        )
        return IgnoredPage(self._version, response)

    
    def list(self, 
        create_ignored_provider: Union[CreateIgnoredProvider, object] = values.unset,
    ) -> List[IgnoredInstance]:
        """
        Lists IgnoredInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "application/json"
        
        data = values.of({ 
            'CreateIgnoredProvider': create_ignored_provider,
        })
        payload, _, _ = self._version.fetch_with_response_info(method='POST', uri=self._uri, params=data, headers=headers)
        
        return [IgnoredInstance(self._version, item) for item in payload[""]]
        

    async def list_async(self, 
        create_ignored_provider: Union[CreateIgnoredProvider, object] = values.unset,
    ) -> List[IgnoredInstance]:
        """
        Asynchronously lists IgnoredInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        headers["Accept"] = "application/json"
        
        data = values.of({ 
            'CreateIgnoredProvider': create_ignored_provider,
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='POST', uri=self._uri, params=data, headers=headers)
        
        return [IgnoredInstance(self._version, item) for item in payload[""]]
        


    def list_with_http_info(self, 
        create_ignored_provider: Union[CreateIgnoredProvider, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists IgnoredInstance and returns headers from first page

        
        :param CreateIgnoredProvider create_ignored_provider: 
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            create_ignored_provider=create_ignored_provider,
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        create_ignored_provider: Union[CreateIgnoredProvider, object] = values.unset,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists IgnoredInstance and returns headers from first page

        
        :param CreateIgnoredProvider create_ignored_provider: 
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            create_ignored_provider=create_ignored_provider,
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
      create_ignored_provider: Union[CreateIgnoredProvider, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> IgnoredPage:
        """
        Retrieve a single page of IgnoredInstance records from the API.
        Request is executed immediately
        
        :param create_ignored_provider: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of IgnoredInstance
        """
        data = values.of({ 
            'CreateIgnoredProvider': create_ignored_provider,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        headers["Content-Type"] = "application/json"
        
        
        headers["Accept"] = "application/json"
        

        response = self._version.page(method='POST', uri=self._uri, params=data, headers=headers)
        return IgnoredPage(self._version, response)

    async def page_async(self, 
      create_ignored_provider: Union[CreateIgnoredProvider, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> IgnoredPage:
        """
        Asynchronously retrieve a single page of IgnoredInstance records from the API.
        Request is executed immediately
        
        :param create_ignored_provider: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of IgnoredInstance
        """
        data = values.of({ 
            'CreateIgnoredProvider': create_ignored_provider,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        headers["Content-Type"] = "application/json"
        
        
        headers["Accept"] = "application/json"
        

        response = await self._version.page_async(method='POST', uri=self._uri, params=data, headers=headers)
        return IgnoredPage(self._version, response)

    def page_with_http_info(self, 
        create_ignored_provider: Union[CreateIgnoredProvider, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param create_ignored_provider: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with IgnoredPage, status code, and headers
        """
        data = values.of({ 
            'CreateIgnoredProvider': create_ignored_provider,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        headers["Content-Type"] = "application/json"
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = self._version.page_with_response_info(method='POST', uri=self._uri, params=data, headers=headers)
        page = IgnoredPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        create_ignored_provider: Union[CreateIgnoredProvider, object] = values.unset,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param create_ignored_provider: 
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with IgnoredPage, status code, and headers
        """
        data = values.of({ 
            'CreateIgnoredProvider': create_ignored_provider,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        headers["Content-Type"] = "application/json"
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='POST', uri=self._uri, params=data, headers=headers)
        page = IgnoredPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> IgnoredPage:
        """
        Retrieve a specific page of IgnoredInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of IgnoredInstance
        """
        response = self._version.domain.twilio.request(
            'POST',
            target_url
        )
        return IgnoredPage(self._version, response)

    async def get_page_async(self, target_url: str) -> IgnoredPage:
        """
        Asynchronously retrieve a specific page of IgnoredInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of IgnoredInstance
        """
        response = await self._version.domain.twilio.request_async(
            'POST',
            target_url
        )
        return IgnoredPage(self._version, response)




    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return '<Twilio.SuppliersAdminApiUs1.Users_manisingh_codehq_open_api_spec_suppliers_v1_openapi_yaml.IgnoredList>'


