components:
  schemas:
    quickReplyActions:
      type: array
      items:
        $ref: "#/components/schemas/quickReplyAction"
    quickReplyActionType:
      type: string
      enum: [ "QUICK_REPLY" ]
    quickReplyAction:
      type: object
      additionalProperties: false
      properties:
        type:
          $ref: "#/components/schemas/quickReplyActionType"
        title:
          type: string
        id:
          type: string
      required:
        - type
        - title
    test.response_object:
      properties:
        account_sid:
          nullable: true
          format: foobar
          type: string
        sid:
          nullable: true
          type: string
      type: object
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  contact:
    email: support@twilio.com
    name: Twilio Support
    url: https://support.twilio.com
  description: This is the public Twilio REST API.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.twilio.com/legal/tos
  title: Twilio - Accounts
  version: 1.11.0
openapi: 3.0.1
paths:
  /2010-04-01/Accounts.json:
    description: A top-level resource
    post:
      operationId: CreateAccount
      requestBody:
        content:
          application/json:
            schema:
              properties:
                RecordingStatusCallback:
                  type: string
                  format: abc
                RecordingStatusCallbackEvent:
                  items:
                    type: string
                    format: abc
                  type: array
                twilioQuickReply:
                  type: object
                  description: twilio/quick-reply templates let recipients tap, rather than type, to respond to the message.
                  nullable: true
                  additionalProperties: false
                  properties:
                    body:
                      type: string
                    actions:
                      $ref: "#/components/schemas/quickReplyActions"
              title: CreateAccountRequest
              type: object
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test.response_object'
              examples:
                example:
                  $ref: '#/components/examples/test.response_object.example'
          description: Created
      security:
        - accountSid_authToken: [ ]
    servers:
      - url: https://api.twilio.com
    x-twilio:
      pathType: list
      dependentProperties:
        address:
          mapping:
            account_sid: sid
          resource_url: /Accounts/{account_sid}/Addresses.json
        application:
          mapping:
            account_sid: sid
          resource_url: /Accounts/{account_sid}/Applications.json
