components:
  schemas:
    accounts.v1.safelist:
      type: object
      properties:
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^GN[0-9a-fA-F]{32}$
          nullable: true
          description: The unique string that we created to identify the SafeList
            resource.
        phone_number:
          type: string
          nullable: true
          description: The phone number in SafeList.
info:
  title: Twilio - Accounts
  description: This is the public Twilio REST API.
  termsOfService: https://www.twilio.com/legal/tos
  contact:
    name: Twilio Support
    url: https://support.twilio.com
    email: support@twilio.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
openapi: 3.0.1
paths:
  /v1/SafeList/Numbers:
    servers:
      - url: https://accounts.twilio.com
    description: ''
    x-twilio:
      defaultOutputProperties:
        - sid
        - phone_number
      mountName: safelist
      pathType: list
    post:
      description: Add a new phone number to SafeList.
      tags:
        - AccountsV1Safelist
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accounts.v1.safelist'
              examples:
                create:
                  value:
                    sid: GNaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    phone_number: '+18001234567'
          description: Created
      security:
        - accountSid_authToken: []
      operationId: CreateSafelist
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              title: CreateSafelistRequest
              properties:
                PhoneNumber:
                  type: string
                  description: The phone number to be added in SafeList. Phone numbers
                    must be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164).
              required:
                - PhoneNumber
            examples:
              create:
                value:
                  PhoneNumber: '+18001234567'
    get:
      description: Check if a phone number exists in SafeList.
      tags:
        - AccountsV1Safelist
      parameters:
        - name: PhoneNumber
          in: query
          description: The phone number to be fetched from SafeList. Phone numbers must
            be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164).
          schema:
            type: string
          examples:
            fetch:
              value: '+18001234567'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accounts.v1.safelist'
              examples:
                fetch:
                  value:
                    sid: GNaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
                    phone_number: '+18001234567'
          description: OK
      security:
        - accountSid_authToken: []
      operationId: FetchSafelist
    delete:
      description: Remove a phone number from SafeList.
      tags:
        - AccountsV1Safelist
      parameters:
        - name: PhoneNumber
          in: query
          description: The phone number to be removed from SafeList. Phone numbers must
            be in [E.164 format](https://www.twilio.com/docs/glossary/what-e164).
          schema:
            type: string
          examples:
            delete:
              value: '+18001234567'
      responses:
        '204':
          description: The resource was deleted successfully.
      security:
        - accountSid_authToken: []
      operationId: DeleteSafelist
servers:
  - url: https://accounts.twilio.com
tags:
  - name: AccountsV1Safelist
