components:
  schemas:
    versionless.fleet:
      type: object
      properties:
        account_sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          nullable: true
          description: The unique SID that identifies this Account.
        friendly_name:
          description: A human readable description for this Fleet.
          nullable: true
          type: string
        sid:
          type: string
          minLength: 34
          maxLength: 34
          pattern: ^TH[0-9a-fA-F]{32}$
          nullable: true
          description: A string that uniquely identifies this Fleet.
  securitySchemes:
    accountSid_authToken:
      scheme: basic
      type: http
info:
  title: Twilio - Versionless
  version: 1.35.0
openapi: 3.0.1
paths:
  /DeployedDevices/Fleets:
    post:
      operationId: CreateDeployedDevicesFleet
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                FriendlyName:
                  type: string
              title: CreateDeployedDevicesFleetRequest
              type: object
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/versionless.fleet'
          description: Created
      security:
        - accountSid_authToken: []
    servers:
      - url: https://versionless.twilio.com
    x-twilio:
      pathType: list
  /DeployedDevices/Fleets/{Sid}:
    get:
      operationId: FetchDeployedDevicesFleet
      parameters:
      - in: path
        name: Sid
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/versionless.fleet'
          description: OK
      security:
      - accountSid_authToken: []
    servers:
      - url: https://versionless.twilio.com
    x-twilio:
      pathType: instance
  /understand/Assistants:
    description: A path for a different product which has no instance operations.
    get:
      operationId: ListUnderstandAssistants
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  assistants:
                    items:
                      $ref: '#/components/schemas/versionless.fleet'
                    type: array
                  meta:
                    properties:
                      first_page_url:
                        format: uri
                        type: string
                      key:
                        type: string
                      next_page_url:
                        format: uri
                        type: string
                      page:
                        type: integer
                      page_size:
                        type: integer
                      previous_page_url:
                        format: uri
                        type: string
                      url:
                        format: uri
                        type: string
                    type: object
                title: ListUnderstandAssistantsResponse
                type: object
          description: OK
      security:
        - accountSid_authToken: []
    servers:
      - url: https://versionless.twilio.com
    x-twilio:
      pathType: list
