/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Intelligence
 * This is a test spec for oneOf with different types.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using Twilio.Base;
using Twilio.Clients;
using Twilio.Constant;
using Twilio.Converters;
using Twilio.Exceptions;
using Twilio.Http;
using Twilio.Types;

namespace Twilio.Rest.Intelligence.V3
{
            public class OperatorResultFetchResource : Resource
{
        
        [JsonProperty("output_format")]
            public OperatorResultResource.OutputFormat OutputFormat { get; private set; }

        ///<summary> The operator_result_id </summary> 
        [JsonProperty("operator_result_id")]
            public string OperatorResultId { get; private set; }

        ///<summary> The result </summary> 
        [JsonProperty("result")]
            public OperatorResultResource.TextResultResult Result { get; private set; }


    public static OperatorResultFetchResource FromJson(string json) {
        try {
            return JsonConvert.DeserializeObject<OperatorResultFetchResource>(json);
        }
        catch (JsonException e) {
            throw new ApiException(e.Message, e);
        }
    }
    public static string ToJson(object model) {
        try {
            return JsonConvert.SerializeObject(model);
        }
        catch (JsonException e) {
            throw new ApiException(e.Message, e);
        }
    }
}
        public class OperatorResultReadResource : Resource
{
            
            [JsonProperty("output_format")]
                public OperatorResultResource.OutputFormat OutputFormat { get; private set; }

            ///<summary> The operator_result_id </summary> 
            [JsonProperty("operator_result_id")]
                public string OperatorResultId { get; private set; }

            ///<summary> The result </summary> 
            [JsonProperty("result")]
                public OperatorResultResource.TextResultResult Result { get; private set; }


    public static OperatorResultReadResource FromJson(string json) {
        try {
            return JsonConvert.DeserializeObject<OperatorResultReadResource>(json);
        }
        catch (JsonException e) {
            throw new ApiException(e.Message, e);
        }
    }
    public static string ToJson(object model) {
        try {
            return JsonConvert.SerializeObject(model);
        }
        catch (JsonException e) {
            throw new ApiException(e.Message, e);
        }
    }
}

    public class OperatorResultResource : Resource
    {
    
        public class TextResultResult
        {
            [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
            public string Text {get; private set;}
            public TextResultResult() { }
            public class Builder
            {
                private TextResultResult _textResultResult = new TextResultResult();
                public Builder()
                {
                }
                public Builder WithText(string text)
                {
                    _textResultResult.Text= text;
                    return this;
                }
                public TextResultResult Build()
                {
                    return _textResultResult;
                }
            }
        }

    
        [JsonConverter(typeof(StringEnumConverter))]
        public sealed class OutputFormat : StringEnum
        {
            private OutputFormat(string value) : base(value) {}
            public OutputFormat() {}
            public static implicit operator OutputFormat(string value)
            {
                return new OutputFormat(value);
            }
            public static readonly OutputFormat Text = new OutputFormat("TEXT");
            public static readonly OutputFormat Json = new OutputFormat("JSON");
            public static readonly OutputFormat Classification = new OutputFormat("CLASSIFICATION");
            public static readonly OutputFormat Extraction = new OutputFormat("EXTRACTION");

        }

            
        private static Request BuildFetchRequest(FetchOperatorResultOptions options, ITwilioRestClient client)
        {
            
            string path = "/v3/OperatorResults/{OperatorResultId}";

            string PathOperatorResultId = options.PathOperatorResultId;
            path = path.Replace("{"+"OperatorResultId"+"}", PathOperatorResultId);

            return new Request(
                HttpMethod.Get,
                Rest.Domain.Intelligence,
                path,
                queryParams: options.GetParams(),
                headerParams: null
            );
        }

        /// <summary> fetch </summary>
        /// <param name="options"> Fetch OperatorResult parameters </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> A single instance of OperatorResult </returns>
        public static OperatorResultFetchResource Fetch(FetchOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = client.Request(BuildFetchRequest(options, client));
            return OperatorResultFetchResource.FromJson(response.Content);
        }

        #if !NET35
        /// <summary> fetch </summary>
        /// <param name="options"> Fetch OperatorResult parameters </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> Task that resolves to A single instance of OperatorResult </returns>
        public static async System.Threading.Tasks.Task<OperatorResultFetchResource> FetchAsync(FetchOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = await client.RequestAsync(BuildFetchRequest(options, client));
            return OperatorResultFetchResource.FromJson(response.Content);
        }
        #endif
        /// <summary> fetch </summary>
        /// <param name="pathOperatorResultId">  </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> A single instance of OperatorResult </returns>
        public static OperatorResultFetchResource Fetch(
                                         string pathOperatorResultId, 
                                        ITwilioRestClient client = null)
        {
            var options = new FetchOperatorResultOptions(pathOperatorResultId){  };
            return Fetch(options, client);
        }

        #if !NET35
        /// <summary> fetch </summary>
        /// <param name="pathOperatorResultId">  </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> Task that resolves to A single instance of OperatorResult </returns>
        public static async System.Threading.Tasks.Task<OperatorResultFetchResource> FetchAsync(string pathOperatorResultId, ITwilioRestClient client = null)
        {
            var options = new FetchOperatorResultOptions(pathOperatorResultId){  };
            return await FetchAsync(options, client);
        }
        #endif
            
        public static TwilioResponse<OperatorResultFetchResource> FetchWithHeaders(FetchOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = client.Request(BuildFetchRequest(options, client));
            var resource = OperatorResultFetchResource.FromJson(response.Content);
            return new TwilioResponse<OperatorResultFetchResource>(resource, response.Headers, response.StatusCode);
        }
        #if !NET35
        public static async System.Threading.Tasks.Task<TwilioResponse<OperatorResultFetchResource>> FetchWithHeadersAsync(FetchOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = await client.RequestAsync(BuildFetchRequest(options, client));
            var resource = OperatorResultFetchResource.FromJson(response.Content);
            return new TwilioResponse<OperatorResultFetchResource>(resource, response.Headers, response.StatusCode);
        }
        #endif
        
        public static TwilioResponse<OperatorResultFetchResource> FetchWithHeaders(
                    string pathOperatorResultId, 
                ITwilioRestClient client = null)
        {
            var options = new FetchOperatorResultOptions(pathOperatorResultId){  };
            return FetchWithHeaders(options, client);
        }
        
        #if !NET35
        public static async System.Threading.Tasks.Task<TwilioResponse<OperatorResultFetchResource>> FetchWithHeadersAsync(string pathOperatorResultId, ITwilioRestClient client = null)
        {
            var options = new FetchOperatorResultOptions(pathOperatorResultId){  };
            return await FetchWithHeadersAsync(options, client);
        }
        #endif
            
        private static Request BuildReadRequest(ReadOperatorResultOptions options, ITwilioRestClient client)
        {
            
            string path = "/v3/OperatorResults";


            return new Request(
                HttpMethod.Get,
                Rest.Domain.Intelligence,
                path,
                queryParams: options.GetParams(),
                headerParams: null
            );
        }
        /// <summary> read </summary>
        /// <param name="options"> Read OperatorResult parameters </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> A single instance of OperatorResult </returns>
        public static ResourceSet<OperatorResultReadResource> Read(ReadOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = client.Request(BuildReadRequest(options, client));
            var page = Page<OperatorResultReadResource>.FromJson("operator_results", response.Content);
            return new ResourceSet<OperatorResultReadResource>(page, options, client);
        }

        #if !NET35
        /// <summary> read </summary>
        /// <param name="options"> Read OperatorResult parameters </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> Task that resolves to A single instance of OperatorResult </returns>
        public static async System.Threading.Tasks.Task<ResourceSet<OperatorResultReadResource>> ReadAsync(ReadOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = await client.RequestAsync(BuildReadRequest(options, client));

            var page = Page<OperatorResultReadResource>.FromJson("operator_results", response.Content);
            return new ResourceSet<OperatorResultReadResource>(page, options, client);
        }
        #endif
        /// <summary> read </summary>
        /// <param name="pageSize">  </param>
        /// <param name="limit"> Record limit </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> A single instance of OperatorResult </returns>
        public static ResourceSet<OperatorResultReadResource> Read(
                                                     int? pageSize = null,
                                                     long? limit = null,
                                                    ITwilioRestClient client = null)
        {
            var options = new ReadOperatorResultOptions(){ PageSize = pageSize, Limit = limit};
            return Read(options, client);
        }

        #if !NET35
        /// <summary> read </summary>
        /// <param name="pageSize">  </param>
        /// <param name="limit"> Record limit </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> Task that resolves to A single instance of OperatorResult </returns>
        public static async System.Threading.Tasks.Task<ResourceSet<OperatorResultReadResource>> ReadAsync(
                                                                                             int? pageSize = null,
                                                                                             long? limit = null,
                                                                                            ITwilioRestClient client = null)
        {
            var options = new ReadOperatorResultOptions(){ PageSize = pageSize, Limit = limit};
            return await ReadAsync(options, client);
        }
        #endif

        public static ResourceSetResponse<OperatorResultReadResource> ReadWithHeaders(ReadOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = client.Request(BuildReadRequest(options, client));
            var page = Page<OperatorResultReadResource>.FromJson("operator_results", response.Content);
            var records = new ResourceSet<OperatorResultReadResource>(page, options, client);
            return new ResourceSetResponse<OperatorResultReadResource>(records, response.Headers, response.StatusCode);
        }

        public static ResourceSetResponse<OperatorResultReadResource> ReadWithHeaders(
            int? pageSize = null,
            long? limit = null,
            ITwilioRestClient client = null)
        {
            var options = new ReadOperatorResultOptions(){ PageSize = pageSize, Limit = limit};
            return ReadWithHeaders(options, client);
        }

        #if !NET35
        public static async System.Threading.Tasks.Task<ResourceSetResponse<OperatorResultReadResource>> ReadWithHeadersAsync(ReadOperatorResultOptions options, ITwilioRestClient client = null)
        {
            client = client ?? TwilioClient.GetRestClient();
            var response = await client.RequestAsync(BuildReadRequest(options, client));

            var page = Page<OperatorResultReadResource>.FromJson("operator_results", response.Content);
            var records = new ResourceSet<OperatorResultReadResource>(page, options, client);
            return new ResourceSetResponse<OperatorResultReadResource>(records, response.Headers, response.StatusCode);
        }
        #endif
        
        
        /// <summary> Fetch the target page of records </summary>
        /// <param name="targetUrl"> API-generated URL for the requested results page </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> The target page of records </returns>
        public static Page<OperatorResultResource> GetPage(string targetUrl, ITwilioRestClient client)
        {
            client = client ?? TwilioClient.GetRestClient();

            var request = new Request(
                HttpMethod.Get,
                targetUrl
            );

            var response = client.Request(request);
            return Page<OperatorResultResource>.FromJson("operator_results", response.Content);
        }

        /// <summary> Fetch the next page of records </summary>
        /// <param name="page"> current page of records </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> The next page of records </returns>
        public static Page<OperatorResultResource> NextPage(Page<OperatorResultResource> page, ITwilioRestClient client)
        {
            var request = new Request(
                HttpMethod.Get,
                page.GetNextPageUrl(Rest.Domain.Api)
            );

            var response = client.Request(request);
            return Page<OperatorResultResource>.FromJson("operator_results", response.Content);
        }

        /// <summary> Fetch the previous page of records </summary>
        /// <param name="page"> current page of records </param>
        /// <param name="client"> Client to make requests to Twilio </param>
        /// <returns> The previous page of records </returns>
        public static Page<OperatorResultResource> PreviousPage(Page<OperatorResultResource> page, ITwilioRestClient client)
        {
            var request = new Request(
                HttpMethod.Get,
                page.GetPreviousPageUrl(Rest.Domain.Api)
            );

            var response = client.Request(request);
            return Page<OperatorResultResource>.FromJson("operator_results", response.Content);
        }

        /// <summary>
    /// Converts an object into a json string
    /// </summary>
    /// <param name="model"> C# model </param>
    /// <returns> JSON string </returns>
    public static string ToJson(object model)
    {
        try
        {
            return JsonConvert.SerializeObject(model);
        }
        catch (JsonException e)
        {
            throw new ApiException(e.Message, e);
        }
    }
    }
}
