# coding: utf-8

"""
    Twilio - Accounts

    This is the public Twilio REST API.  # noqa: E501

    The version of the OpenAPI document: 2010-04-01
    Contact: support@twilio.com
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths._2010_04_01_accounts_account_sid_calls_json.post import CreateCall
from openapi_client.paths._2010_04_01_accounts_account_sid_calls_test_integer_json.delete import DeleteCall
from openapi_client.paths._2010_04_01_accounts_account_sid_calls_test_integer_json.get import FetchCall


class Account1234567890Call(
    CreateCall,
    DeleteCall,
    FetchCall,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
