r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Media
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""


from datetime import date, datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator, Protocol
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page
from twilio.rest.media.users_manisingh_codehq_open_api_spec_media_v1_openapi_yaml.transcription.result import ResultList








class TranscriptionInstance(InstanceResource):



    class Status(object):
        COMPLETED = "completed"
        DELETED = "deleted"
        ENQUEUED = "enqueued"
        FAILED = "failed"
        PROCESSING = "processing"

    """
    :ivar sid: The unique string that we created to identify the Transcription resource.
    :ivar account_sid: The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Transcription resource.
    :ivar url: The absolute URL of the Transcription resource.
    :ivar date_created: The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    :ivar date_updated: The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    :ivar status: 
    :ivar encryption_key_sid: The SID of the optional [CredentialPublicKey](https://www.twilio.com/docs/iam/credentialpublickey-resource) used to encrypt Transcription resource.
    :ivar source: The  source information for the transcription metadata. It contains the SID, duration (seconds), channels, content type and sample rate (Hertz).
    :ivar configuration: The configuration information to transcribe the source. It contains the SID, unique name and language (BCP-47 code).
    :ivar links: The URLs of related resources.
    """

    def __init__(self, version: Version, payload:Dict[str, Any], sid: Optional[str] = None):
        super().__init__(version)

        
        self.sid: Optional[str] = payload.get("sid")
        self.account_sid: Optional[str] = payload.get("account_sid")
        self.url: Optional[str] = payload.get("url")
        self.date_created: Optional[datetime] = deserialize.iso8601_datetime(payload.get("date_created"))
        self.date_updated: Optional[datetime] = deserialize.iso8601_datetime(payload.get("date_updated"))
        self.status: Optional["TranscriptionInstance.Status"] = payload.get("status")
        self.encryption_key_sid: Optional[str] = payload.get("encryption_key_sid")
        self.source: Optional[Dict[str, object]] = payload.get("source")
        self.configuration: Optional[Dict[str, object]] = payload.get("configuration")
        self.links: Optional[Dict[str, object]] = payload.get("links")

        
        
        self._solution = { 
            "sid": sid or self.sid,
        }
        
        
        self._context: Optional[TranscriptionContext] = None

    @property
    def _proxy(self) -> "TranscriptionContext":
        """
        Generate an instance context for the instance, the context is capable of
        performing various actions. All instance actions are proxied to the context

        :returns: TranscriptionContext for this TranscriptionInstance
        """
        if self._context is None:
            self._context = TranscriptionContext(self._version, sid=self._solution['sid'],)
        return self._context
    
    
    def delete(self) -> bool:
        """
        Deletes the TranscriptionInstance
        

        :returns: True if delete succeeds, False otherwise
        """
        return self._proxy.delete()
    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the TranscriptionInstance
        

        :returns: True if delete succeeds, False otherwise
        """
        return await self._proxy.delete_async()

    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the TranscriptionInstance with HTTP info
        

        :returns: ApiResponse with success boolean, status code, and headers
        """
        return self._proxy.delete_with_http_info()

    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the TranscriptionInstance with HTTP info
        

        :returns: ApiResponse with success boolean, status code, and headers
        """
        return await self._proxy.delete_with_http_info_async()
    
    
    def fetch(self) -> "TranscriptionInstance":
        """
        Fetch the TranscriptionInstance
        

        :returns: The fetched TranscriptionInstance
        """
        return self._proxy.fetch()

    async def fetch_async(self) -> "TranscriptionInstance":
        """
        Asynchronous coroutine to fetch the TranscriptionInstance
        

        :returns: The fetched TranscriptionInstance
        """
        return await self._proxy.fetch_async()

    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the TranscriptionInstance with HTTP info
        

        :returns: ApiResponse with instance, status code, and headers
        """
        return self._proxy.fetch_with_http_info()

    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the TranscriptionInstance with HTTP info
        

        :returns: ApiResponse with instance, status code, and headers
        """
        return await self._proxy.fetch_with_http_info_async()
    
    
    @property
    def result(self) -> ResultList:
        """
        Access the result
        """
        return self._proxy.result
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = ' '.join('{}={}'.format(k, v) for k, v in self._solution.items())
        return '<Twilio.Media.Users_manisingh_codehq_open_api_spec_media_v1_openapi_yaml.TranscriptionInstance {}>'.format(context)

class TranscriptionContext(InstanceContext):


    def __init__(self, version: Version, sid: str):
        """
        Initialize the TranscriptionContext

        :param version: Version that contains the resource
        :param sid: The SID of the Transcription resource to fetch.
        """
        super().__init__(version)

        
        # Path Solution
        self._solution = { 
            'sid': sid,
        }
        self._uri = '/Transcriptions/{sid}'.format(**self._solution)
        
        self._result: Optional[ResultList] = None
    
    
    def _delete(self) -> tuple:
        """
        Internal helper for delete operation

        Returns:
            tuple: (success_boolean, status_code, headers)
        """

        
        headers = values.of({})
        
        
        
        return self._version.delete_with_response_info(method='DELETE', uri=self._uri, headers=headers)

    def delete(self) -> bool:
        """
        Deletes the TranscriptionInstance

        
        :returns: True if delete succeeds, False otherwise
        """
        success, _, _ = self._delete()
        return success

    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the TranscriptionInstance and return response metadata

        
        :returns: ApiResponse with success boolean, status code, and headers
        """
        success, status_code, headers = self._delete()
        return ApiResponse(data=success, status_code=status_code, headers=headers)

    async def _delete_async(self) -> tuple:
        """
        Internal async helper for delete operation

        Returns:
            tuple: (success_boolean, status_code, headers)
        """
        
        headers = values.of({})
        
        
        
        return await self._version.delete_with_response_info_async(method='DELETE', uri=self._uri, headers=headers)

    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the TranscriptionInstance

        
        :returns: True if delete succeeds, False otherwise
        """
        success, _, _ = await self._delete_async()
        return success

    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the TranscriptionInstance and return response metadata

        
        :returns: ApiResponse with success boolean, status code, and headers
        """
        success, status_code, headers = await self._delete_async()
        return ApiResponse(data=success, status_code=status_code, headers=headers)
    
    
    def _fetch(self) -> tuple:
        """
        Internal helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        

        headers = values.of({})
        
        
        
        headers["Accept"] = "application/json"
        
        return self._version.fetch_with_response_info(method='GET', uri=self._uri, headers=headers)

    def fetch(self) -> TranscriptionInstance:
        """
        Fetch the TranscriptionInstance
        

        :returns: The fetched TranscriptionInstance
        """
        payload, _, _ = self._fetch()
        return TranscriptionInstance(
            self._version,
            payload,
            sid=self._solution['sid'],
            
        )

    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the TranscriptionInstance and return response metadata
        

        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = self._fetch()
        instance = TranscriptionInstance(
            self._version,
            payload,
            sid=self._solution['sid'],
            
        )
        return ApiResponse(data=instance, status_code=status_code, headers=headers)

    async def _fetch_async(self) -> tuple:
        """
        Internal async helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        

        headers = values.of({})
        
        
        
        headers["Accept"] = "application/json"
        
        return await self._version.fetch_with_response_info_async(method='GET', uri=self._uri, headers=headers)

    async def fetch_async(self) -> TranscriptionInstance:
        """
        Asynchronous coroutine to fetch the TranscriptionInstance
        

        :returns: The fetched TranscriptionInstance
        """
        payload, _, _ = await self._fetch_async()
        return TranscriptionInstance(
            self._version,
            payload,
            sid=self._solution['sid'],
            
        )

    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the TranscriptionInstance and return response metadata
        

        :returns: ApiResponse with instance, status code, and headers
        """
        payload, status_code, headers = await self._fetch_async()
        instance = TranscriptionInstance(
            self._version,
            payload,
            sid=self._solution['sid'],
            
        )
        return ApiResponse(data=instance, status_code=status_code, headers=headers)
    
    
    
    @property
    def result(self) -> ResultList:
        """
        Access the result
        """
        if self._result is None:
            self._result = ResultList(
                self._version, 
                self._solution['sid'],
            )
        return self._result
    
    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = ' '.join('{}={}'.format(k, v) for k, v in self._solution.items())
        return '<Twilio.Media.Users_manisingh_codehq_open_api_spec_media_v1_openapi_yaml.TranscriptionContext {}>'.format(context)







class TranscriptionPage(Page):

    def get_instance(self, payload: Dict[str, Any]) -> TranscriptionInstance:
        """
        Build an instance of TranscriptionInstance

        :param payload: Payload response from the API
        """
        
        return TranscriptionInstance(self._version, payload)
        

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return "<Twilio.Media.Users_manisingh_codehq_open_api_spec_media_v1_openapi_yaml.TranscriptionPage>"




class TranscriptionPage(Page):

    def get_instance(self, payload: Dict[str, Any]) -> TranscriptionInstance:
        """
        Build an instance of TranscriptionInstance

        :param payload: Payload response from the API
        """
        
        return TranscriptionInstance(self._version, payload)
        

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return "<Twilio.Media.Users_manisingh_codehq_open_api_spec_media_v1_openapi_yaml.TranscriptionPage>"




class TranscriptionPage(Page):

    def get_instance(self, payload: Dict[str, Any]) -> TranscriptionInstance:
        """
        Build an instance of TranscriptionInstance

        :param payload: Payload response from the API
        """
        
        return TranscriptionInstance(self._version, payload)
        

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return "<Twilio.Media.Users_manisingh_codehq_open_api_spec_media_v1_openapi_yaml.TranscriptionPage>"





class TranscriptionList(ListResource):
    
    def __init__(self, version: Version):
        """
        Initialize the TranscriptionList

        :param version: Version that contains the resource
        
        """
        super().__init__(version)

        
        self._uri = '/Transcriptions'
        
        
    
    
    
    def list(self, 
    ) -> List[TranscriptionInstance]:
        """
        Lists TranscriptionInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = self._version.fetch_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [TranscriptionInstance(self._version, item) for item in payload["transcriptions"]]
        

    async def list_async(self, 
    ) -> List[TranscriptionInstance]:
        """
        Asynchronously lists TranscriptionInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [TranscriptionInstance(self._version, item) for item in payload["transcriptions"]]
        


    def list_with_http_info(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists TranscriptionInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists TranscriptionInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> TranscriptionPage:
        """
        Retrieve a single page of TranscriptionInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of TranscriptionInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = self._version.page(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return TranscriptionPage(self._version, response)

    async def page_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> TranscriptionPage:
        """
        Asynchronously retrieve a single page of TranscriptionInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of TranscriptionInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = await self._version.page_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return TranscriptionPage(self._version, response)

    def page_with_http_info(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with TranscriptionPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = self._version.page_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = TranscriptionPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with TranscriptionPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = TranscriptionPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> TranscriptionPage:
        """
        Retrieve a specific page of TranscriptionInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of TranscriptionInstance
        """
        response = self._version.domain.twilio.request(
            'OPTIONS',
            target_url
        )
        return TranscriptionPage(self._version, response)

    async def get_page_async(self, target_url: str) -> TranscriptionPage:
        """
        Asynchronously retrieve a specific page of TranscriptionInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of TranscriptionInstance
        """
        response = await self._version.domain.twilio.request_async(
            'OPTIONS',
            target_url
        )
        return TranscriptionPage(self._version, response)

    
    def stream(self, 
        from_date: Union[datetime, object] = values.unset,
        until_date: Union[datetime, object] = values.unset,
        encryption_key_sid: Union[str, object] = values.unset,
        status: Union["TranscriptionInstance.Status", object] = values.unset,
        source_sid: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> Iterator[TranscriptionInstance]:
        """
        Streams TranscriptionInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.
        
        :param datetime from_date: Retrieve transcriptions created after and including this date.
        :param datetime until_date: Retrieve transcriptions created before and including this date.
        :param str encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param &quot;TranscriptionInstance.Status&quot; status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param str source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        limits = self._version.read_limits(limit, page_size)
        page = self.page(
            from_date=from_date,
            until_date=until_date,
            encryption_key_sid=encryption_key_sid,
            status=status,
            source_sid=source_sid,
            page_size=limits['page_size']
        )

        return self._version.stream(page, limits['limit'])

    async def stream_async(self, 
        from_date: Union[datetime, object] = values.unset,
        until_date: Union[datetime, object] = values.unset,
        encryption_key_sid: Union[str, object] = values.unset,
        status: Union["TranscriptionInstance.Status", object] = values.unset,
        source_sid: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> AsyncIterator[TranscriptionInstance]:
        """
        Asynchronously streams TranscriptionInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.
        
        :param datetime from_date: Retrieve transcriptions created after and including this date.
        :param datetime until_date: Retrieve transcriptions created before and including this date.
        :param str encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param &quot;TranscriptionInstance.Status&quot; status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param str source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        limits = self._version.read_limits(limit, page_size)
        page = await self.page_async(
            from_date=from_date,
            until_date=until_date,
            encryption_key_sid=encryption_key_sid,
            status=status,
            source_sid=source_sid,
            page_size=limits['page_size']
        )

        return self._version.stream_async(page, limits['limit'])

    def stream_with_http_info(self, 
        from_date: Union[datetime, object] = values.unset,
        until_date: Union[datetime, object] = values.unset,
        encryption_key_sid: Union[str, object] = values.unset,
        status: Union["TranscriptionInstance.Status", object] = values.unset,
        source_sid: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> tuple:
        """
        Streams TranscriptionInstance and returns headers from first page

        
        :param datetime from_date: Retrieve transcriptions created after and including this date.
        :param datetime until_date: Retrieve transcriptions created before and including this date.
        :param str encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param &quot;TranscriptionInstance.Status&quot; status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param str source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        limits = self._version.read_limits(limit, page_size)
        page_response = self.page_with_http_info(
            from_date=from_date,
            until_date=until_date,
            encryption_key_sid=encryption_key_sid,
            status=status,
            source_sid=source_sid,
            page_size=limits['page_size']
        )

        generator = self._version.stream(page_response.data, limits['limit'])
        return (generator, page_response.status_code, page_response.headers)

    async def stream_with_http_info_async(self, 
        from_date: Union[datetime, object] = values.unset,
        until_date: Union[datetime, object] = values.unset,
        encryption_key_sid: Union[str, object] = values.unset,
        status: Union["TranscriptionInstance.Status", object] = values.unset,
        source_sid: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> tuple:
        """
        Asynchronously streams TranscriptionInstance and returns headers from first page

        
        :param datetime from_date: Retrieve transcriptions created after and including this date.
        :param datetime until_date: Retrieve transcriptions created before and including this date.
        :param str encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param &quot;TranscriptionInstance.Status&quot; status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param str source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        limits = self._version.read_limits(limit, page_size)
        page_response = await self.page_with_http_info_async(
            from_date=from_date,
            until_date=until_date,
            encryption_key_sid=encryption_key_sid,
            status=status,
            source_sid=source_sid,
            page_size=limits['page_size']
        )

        generator = self._version.stream_async(page_response.data, limits['limit'])
        return (generator, page_response.status_code, page_response.headers)

    def list(self, 
        from_date: Union[datetime, object] = values.unset,
        until_date: Union[datetime, object] = values.unset,
        encryption_key_sid: Union[str, object] = values.unset,
        status: Union["TranscriptionInstance.Status", object] = values.unset,
        source_sid: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> List[TranscriptionInstance]:
        """
        Lists TranscriptionInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.
        
        :param datetime from_date: Retrieve transcriptions created after and including this date.
        :param datetime until_date: Retrieve transcriptions created before and including this date.
        :param str encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param &quot;TranscriptionInstance.Status&quot; status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param str source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)
        
        :returns: list that will contain up to limit results
        """

        return list(self.stream(
            from_date=from_date,
            until_date=until_date,
            encryption_key_sid=encryption_key_sid,
            status=status,
            source_sid=source_sid,
            limit=limit,
            page_size=page_size,
        ))

    async def list_async(self, 
        from_date: Union[datetime, object] = values.unset,
        until_date: Union[datetime, object] = values.unset,
        encryption_key_sid: Union[str, object] = values.unset,
        status: Union["TranscriptionInstance.Status", object] = values.unset,
        source_sid: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> List[TranscriptionInstance]:
        """
        Asynchronously lists TranscriptionInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.
        
        :param datetime from_date: Retrieve transcriptions created after and including this date.
        :param datetime until_date: Retrieve transcriptions created before and including this date.
        :param str encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param &quot;TranscriptionInstance.Status&quot; status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param str source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)
        
        :returns: list that will contain up to limit results
        """

        return [record async for record in await self.stream_async(
            from_date=from_date,
            until_date=until_date,
            encryption_key_sid=encryption_key_sid,
            status=status,
            source_sid=source_sid,
            limit=limit,
            page_size=page_size,
        )]


    def list_with_http_info(self, 
        from_date: Union[datetime, object] = values.unset,
        until_date: Union[datetime, object] = values.unset,
        encryption_key_sid: Union[str, object] = values.unset,
        status: Union["TranscriptionInstance.Status", object] = values.unset,
        source_sid: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists TranscriptionInstance and returns headers from first page

        
        :param datetime from_date: Retrieve transcriptions created after and including this date.
        :param datetime until_date: Retrieve transcriptions created before and including this date.
        :param str encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param &quot;TranscriptionInstance.Status&quot; status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param str source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            from_date=from_date,
            until_date=until_date,
            encryption_key_sid=encryption_key_sid,
            status=status,
            source_sid=source_sid,
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        from_date: Union[datetime, object] = values.unset,
        until_date: Union[datetime, object] = values.unset,
        encryption_key_sid: Union[str, object] = values.unset,
        status: Union["TranscriptionInstance.Status", object] = values.unset,
        source_sid: Union[str, object] = values.unset,
        
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists TranscriptionInstance and returns headers from first page

        
        :param datetime from_date: Retrieve transcriptions created after and including this date.
        :param datetime until_date: Retrieve transcriptions created before and including this date.
        :param str encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param &quot;TranscriptionInstance.Status&quot; status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param str source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            from_date=from_date,
            until_date=until_date,
            encryption_key_sid=encryption_key_sid,
            status=status,
            source_sid=source_sid,
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
      from_date: Union[datetime, object] = values.unset,
      until_date: Union[datetime, object] = values.unset,
      encryption_key_sid: Union[str, object] = values.unset,
      status: Union["TranscriptionInstance.Status", object] = values.unset,
      source_sid: Union[str, object] = values.unset,
      
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> TranscriptionPage:
        """
        Retrieve a single page of TranscriptionInstance records from the API.
        Request is executed immediately
        
        :param from_date: Retrieve transcriptions created after and including this date.
        :param until_date: Retrieve transcriptions created before and including this date.
        :param encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of TranscriptionInstance
        """
        data = values.of({ 
            'FromDate': serialize.iso8601_datetime(from_date),
            'UntilDate': serialize.iso8601_datetime(until_date),
            'EncryptionKeySid': encryption_key_sid,
            'Status': status,
            'SourceSid': source_sid,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = self._version.page(method='GET', uri=self._uri, params=data, headers=headers)
        return TranscriptionPage(self._version, response)

    async def page_async(self, 
      from_date: Union[datetime, object] = values.unset,
      until_date: Union[datetime, object] = values.unset,
      encryption_key_sid: Union[str, object] = values.unset,
      status: Union["TranscriptionInstance.Status", object] = values.unset,
      source_sid: Union[str, object] = values.unset,
      
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> TranscriptionPage:
        """
        Asynchronously retrieve a single page of TranscriptionInstance records from the API.
        Request is executed immediately
        
        :param from_date: Retrieve transcriptions created after and including this date.
        :param until_date: Retrieve transcriptions created before and including this date.
        :param encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of TranscriptionInstance
        """
        data = values.of({ 
            'FromDate': serialize.iso8601_datetime(from_date),
            'UntilDate': serialize.iso8601_datetime(until_date),
            'EncryptionKeySid': encryption_key_sid,
            'Status': status,
            'SourceSid': source_sid,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response = await self._version.page_async(method='GET', uri=self._uri, params=data, headers=headers)
        return TranscriptionPage(self._version, response)

    def page_with_http_info(self, 
        from_date: Union[datetime, object] = values.unset,
        until_date: Union[datetime, object] = values.unset,
        encryption_key_sid: Union[str, object] = values.unset,
        status: Union["TranscriptionInstance.Status", object] = values.unset,
        source_sid: Union[str, object] = values.unset,
        
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param from_date: Retrieve transcriptions created after and including this date.
        :param until_date: Retrieve transcriptions created before and including this date.
        :param encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with TranscriptionPage, status code, and headers
        """
        data = values.of({ 
            'FromDate': serialize.iso8601_datetime(from_date),
            'UntilDate': serialize.iso8601_datetime(until_date),
            'EncryptionKeySid': encryption_key_sid,
            'Status': status,
            'SourceSid': source_sid,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = self._version.page_with_response_info(method='GET', uri=self._uri, params=data, headers=headers)
        page = TranscriptionPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        from_date: Union[datetime, object] = values.unset,
        until_date: Union[datetime, object] = values.unset,
        encryption_key_sid: Union[str, object] = values.unset,
        status: Union["TranscriptionInstance.Status", object] = values.unset,
        source_sid: Union[str, object] = values.unset,
        
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param from_date: Retrieve transcriptions created after and including this date.
        :param until_date: Retrieve transcriptions created before and including this date.
        :param encryption_key_sid: Encryption key sid of the transcriptions to retrieve.
        :param status: The status of the transcriptions to retrieve. Can be: `completed`, `deleted`, `enqueued`, `failed` or `processing`.
        :param source_sid: SID of the audio source that was transcribed (e.g. a `RecordingSid` for call recording transcriptions).
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with TranscriptionPage, status code, and headers
        """
        data = values.of({ 
            'FromDate': serialize.iso8601_datetime(from_date),
            'UntilDate': serialize.iso8601_datetime(until_date),
            'EncryptionKeySid': encryption_key_sid,
            'Status': status,
            'SourceSid': source_sid,
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        
        headers["Accept"] = "application/json"
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='GET', uri=self._uri, params=data, headers=headers)
        page = TranscriptionPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> TranscriptionPage:
        """
        Retrieve a specific page of TranscriptionInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of TranscriptionInstance
        """
        response = self._version.domain.twilio.request(
            'GET',
            target_url
        )
        return TranscriptionPage(self._version, response)

    async def get_page_async(self, target_url: str) -> TranscriptionPage:
        """
        Asynchronously retrieve a specific page of TranscriptionInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of TranscriptionInstance
        """
        response = await self._version.domain.twilio.request_async(
            'GET',
            target_url
        )
        return TranscriptionPage(self._version, response)

    
    def list(self, 
    ) -> List[TranscriptionInstance]:
        """
        Lists TranscriptionInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = self._version.fetch_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [TranscriptionInstance(self._version, item) for item in payload["transcriptions"]]
        

    async def list_async(self, 
    ) -> List[TranscriptionInstance]:
        """
        Asynchronously lists TranscriptionInstance records from the API as a list.
        
        :returns: list that will contain up to limit results
        """

        headers = values.of({'Content-Type': 'application/x-www-form-urlencoded'})
        
        data = values.of({ 
        })
        payload, _, _ = await self._version.fetch_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        
        return [TranscriptionInstance(self._version, item) for item in payload["transcriptions"]]
        


    def list_with_http_info(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists TranscriptionInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = self.stream_with_http_info(
            limit=limit,
            page_size=page_size,
        )
        items = list(generator)
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    async def list_with_http_info_async(self, 
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists TranscriptionInstance and returns headers from first page

        
        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        generator, status_code, headers = await self.stream_with_http_info_async(
            limit=limit,
            page_size=page_size,
        )
        items = [record async for record in generator]
        return ApiResponse(data=items, status_code=status_code, headers=headers)

    def page(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> TranscriptionPage:
        """
        Retrieve a single page of TranscriptionInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of TranscriptionInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = self._version.page(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return TranscriptionPage(self._version, response)

    async def page_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> TranscriptionPage:
        """
        Asynchronously retrieve a single page of TranscriptionInstance records from the API.
        Request is executed immediately
        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of TranscriptionInstance
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response = await self._version.page_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        return TranscriptionPage(self._version, response)

    def page_with_http_info(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with TranscriptionPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = self._version.page_with_response_info(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = TranscriptionPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    async def page_with_http_info_async(self, 
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata

        
        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with TranscriptionPage, status code, and headers
        """
        data = values.of({ 
            'PageToken': page_token,
            'Page': page_number,
            'PageSize': page_size,
        })

        headers = values.of({
        'Content-Type': 'application/x-www-form-urlencoded'
        })
        
        

        response, status_code, response_headers = await self._version.page_with_response_info_async(method='OPTIONS', uri=self._uri, params=data, headers=headers)
        page = TranscriptionPage(self._version, response)
        return ApiResponse(data=page, status_code=status_code, headers=response_headers)

    def get_page(self, target_url: str) -> TranscriptionPage:
        """
        Retrieve a specific page of TranscriptionInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of TranscriptionInstance
        """
        response = self._version.domain.twilio.request(
            'OPTIONS',
            target_url
        )
        return TranscriptionPage(self._version, response)

    async def get_page_async(self, target_url: str) -> TranscriptionPage:
        """
        Asynchronously retrieve a specific page of TranscriptionInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of TranscriptionInstance
        """
        response = await self._version.domain.twilio.request_async(
            'OPTIONS',
            target_url
        )
        return TranscriptionPage(self._version, response)





    def get(self, sid: str) -> TranscriptionContext:
        """
        Constructs a TranscriptionContext
        
        :param sid: The SID of the Transcription resource to fetch.
        """
        return TranscriptionContext(self._version, sid=sid)

    def __call__(self, sid: str) -> TranscriptionContext:
        """
        Constructs a TranscriptionContext
        
        :param sid: The SID of the Transcription resource to fetch.
        """
        return TranscriptionContext(self._version, sid=sid)

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return '<Twilio.Media.Users_manisingh_codehq_open_api_spec_media_v1_openapi_yaml.TranscriptionList>'


